### ISSUE TITLE
Failed to query Iceberg TIMESTAMP type

### ISSUE THREAD

**Issue by Wkkkkkkk** [prestodb/presto#16996] opened 2021-11-16 02:24 UTC
名称 | 版本 | 描述
-- | -- | --
flink | 1.3.2 | 开源版本
cdh | 6.3.2 | 开源版本
hive | 2.1.1-cdh6.3.2 | 包含cdh中
hadoop | 3.0.0-cdh6.3.2 | cdh原生版本
presto | 2.591 | 开源版本
trino | 360 | 开源版本
Iceberg | 0.13 | master分支编译

1. Flink create table 

```sql
CREATE TABLE ic17 (
   tinyint0 INT
  , smallint1 SMALLINT
  , int2 INT
  , bigint3 BIGINT
  , float4 FLOAT
  , double5 DOUBLE  
  , decimal6 DECIMAL(12,3)
  , boolean7 BOOLEAN
  ,char8 CHAR(64) PRIMARY KEY NOT ENFORCED
  ,varchar9 VARCHAR(64)
  , string10 STRING
  , timestamp11 TIMESTAMP(3)
) 
PARTITIONED BY (tinyint0)
WITH (
     'connector'='iceberg'                    -- 主键和分区均可多个，分割
   , 'format-version' = '1'                   -- iceberg表版本，可选1，2
   , 'engine.hive.enabled' = 'true'           -- 启用hive同步
   , 'catalog-name'='hive_catalog'            -- 指定catalog
   , 'catalog-database'='iceberg'             -- 指定hive database
   , 'uri'='thrift://cdh2:9083'               -- hive hms地址，分割 
);
```

2. Flink insert

```sql
INSERT INTO ic17 VALUES(
      cast(1218 as INT)
    , cast(295 as SMALLINT)
    , cast(-210121792 as INT)
    , cast(-3697946268377828253 as BIGINT)
    , cast(1.123456789111111 as FLOAT)
    , cast(1111111.123411 as DOUBLE)
    , cast(1111.1234111 as DECIMAL(12, 3))
    , cast(123123123123 as BOOLEAN)
 , cast('`[s1tX213ysdasdasdgfq3wqwdqwqd速度速度pGPYl`AggMaHNRJv\[CkIYzcgMlmVvLSjtYmnlBEcwH^kEgDSxGIwGNLDP' as CHAR(64))
    , cast('daQOIE[n_eJsYLBJLttyFHnBXiCoT`RWeCO\G[JZZTdFFnFZFCODoI`X[SbMVAjq' as VARCHAR(64))
    , cast('e1916697-e626-4446-bd18-0142bfb9417b' as STRING)
    , cast('2021-09-13 03:08:50.810' as TIMESTAMP(3))
);
```

3. presto query

   ![image-20211116101850364](https://gitee.com/Wkkkkkkk/picture/raw/master/img/image-20211116101850364.png)

4. trino query

   ![image-20211116102021473](https://gitee.com/Wkkkkkkk/picture/raw/master/img/image-20211116102021473.png)

5. hive query 

    ![image-20211116102137130](https://gitee.com/Wkkkkkkk/picture/raw/master/img/image-20211116102137130.png)

**Comment by beinan** [comment] 2021-11-16 02:47
Thank you @Wkkkkkkk for creating this issue!  @ChunxuTang and I will take a look very soon

**Comment by beinan** [comment] 2021-11-17 08:00
We're able to reproduce the bugs.  I think the root cause is the mapping between presto's timestamp types and iceberg's timestamp type is missing.  I will try to implement it and post a pr.
The obstacle here is prestodb only support precision of milliseconds ,but looks like iceberg is able to support at least micro second.   I might made an implicit conversion here.

**Comment by Wkkkkkkk** [comment] 2021-11-18 05:33
@beinan That's very kind of you. Thank you

**Comment by Sudeepam97** [comment] 2022-01-13 05:29
Hey @beinan is this being planned worked on currently?

**Comment by ChunxuTang** [comment] 2022-01-14 07:02
Hi @Sudeepam97, I'm looking at the issue and plan to send an initial PR to support the feature soon. Cc @beinan

**Comment by ChunxuTang** [comment] 2022-01-14 20:46
#17190

**Comment by pratyakshsharma** [comment] 2022-12-23 12:06
Closing this since the support for TIMESTAMP type is now available.

**Closed by pratyakshsharma** 2022-12-23 12:06 UTC
