### ISSUE TITLE
unable to SUM or AVG on interval types

### ISSUE THREAD

**Issue by the6campbells** [prestodb/presto#6966] opened 2016-12-24 22:11 UTC
Version: 0.160

Attempting to perform a SUM or AVG aggregate on an interval is not supported. Meanwhile MIN, MAX and COUNT supported.

https://prestodb.io/docs/current/functions/aggregate.html

   SELECT
   SUM(INTERVAL '31 12' DAY TO HOUR) AS "c1",
   SUM(INTERVAL '31 12:45:59.123000000' DAY TO SECOND) AS "c2",
   SUM(INTERVAL '2010-1' YEAR TO MONTH) AS "c3",
   AVG(INTERVAL '31 12' DAY TO HOUR) AS "c4",
   AVG(INTERVAL '31 12:45:59.123000000' DAY TO SECOND) AS "c5",
   AVG(INTERVAL '2010-1' YEAR TO MONTH) AS "c6"
   FROM ( values (1) ) T (C1) 

Error: Query failed (#20161224_220803_04757_ztdeg): line 2:4: Unexpected parameters (interval day to second) for function avg. Expected: avg(double) , avg(bigint) , avg(real) , avg(decimal(p,s)) 
SQLState:  null

Error: Query failed (#20161224_220745_04756_ztdeg): line 2:4: Unexpected parameters (interval day to second) for function sum. Expected: sum(double) , sum(real) , sum(bigint) , sum(decimal(p,s)) 
SQLState:  null

**Comment by fiedukow** [comment] 2017-01-09 15:17
Implementation in review.

**Comment by fiedukow** [comment] 2017-01-10 11:44
Closing as duplicate of:
#4417
See discussion in:
#7026 
and
#4456

**Closed by fiedukow** 2017-01-10 11:44 UTC
Labels: duplicate
