### ISSUE TITLE
Cannot cast char(27) to bigint.

### ISSUE THREAD

**Issue by the6campbells** [prestodb/presto#7730] opened 2017-04-02 18:41 UTC
Presto 0.170 server/jdbc

Mapped to MySQL
select rnum, cast(c1 as bigint) from mysql_cert.dbcert.tsdchar where rnum in (0,1,2)

Cannot cast char(27) to bigint.

create table TSDCHAR (RNUM integer   not null , C1 char (27));

insert into TSDCHAR ( RNUM, C1 ) values ( 0, '-1');
insert into TSDCHAR ( RNUM, C1 ) values ( 1, '0');
insert into TSDCHAR ( RNUM, C1 ) values ( 2, '10');
insert into TSDCHAR ( RNUM, C1 ) values ( 3, '-1.0');
insert into TSDCHAR ( RNUM, C1 ) values ( 4, '0.0');
insert into TSDCHAR ( RNUM, C1 ) values ( 5, '10.0');
insert into TSDCHAR ( RNUM, C1 ) values ( 6, '-1.0E-1');
insert into TSDCHAR ( RNUM, C1 ) values ( 7, '10.0E+0');
insert into TSDCHAR ( RNUM, C1 ) values ( 8, '2000-12-31');
insert into TSDCHAR ( RNUM, C1 ) values ( 9, '23:59:30.123');
insert into TSDCHAR ( RNUM, C1 ) values ( 10, '2000-12-31 12:15:30.123');
insert into TSDCHAR ( RNUM, C1 ) values ( 11, '12:00:00.00+05:00');
insert into TSDCHAR ( RNUM, C1 ) values ( 12, '2000-12-31 12:00:00.0+05:00');
insert into TSDCHAR ( RNUM, C1 ) values ( 13, '-1');
insert into TSDCHAR ( RNUM, C1 ) values ( 14, '10');
insert into TSDCHAR ( RNUM, C1 ) values ( 15, '-1');
insert into TSDCHAR ( RNUM, C1 ) values ( 16, '10');
insert into TSDCHAR ( RNUM, C1 ) values ( 17, '-01-01');
insert into TSDCHAR ( RNUM, C1 ) values ( 18, '10-10');
insert into TSDCHAR ( RNUM, C1 ) values ( 19, '-1');
insert into TSDCHAR ( RNUM, C1 ) values ( 20, '10');
insert into TSDCHAR ( RNUM, C1 ) values ( 21, '-1');
insert into TSDCHAR ( RNUM, C1 ) values ( 22, '10');
insert into TSDCHAR ( RNUM, C1 ) values ( 23, '-1');
insert into TSDCHAR ( RNUM, C1 ) values ( 24, '10');
insert into TSDCHAR ( RNUM, C1 ) values ( 25, '-1.5');
insert into TSDCHAR ( RNUM, C1 ) values ( 26, '10.20');
insert into TSDCHAR ( RNUM, C1 ) values ( 27, '-1 1');
insert into TSDCHAR ( RNUM, C1 ) values ( 28, '10 10');
insert into TSDCHAR ( RNUM, C1 ) values ( 29, '-1 01:01');
insert into TSDCHAR ( RNUM, C1 ) values ( 30, '10 20:30');
insert into TSDCHAR ( RNUM, C1 ) values ( 31, '-1 01:01:01');
insert into TSDCHAR ( RNUM, C1 ) values ( 32, '10 20:30:40');
insert into TSDCHAR ( RNUM, C1 ) values ( 33, '-1:01');
insert into TSDCHAR ( RNUM, C1 ) values ( 34, '10:20');
insert into TSDCHAR ( RNUM, C1 ) values ( 35, '-01:01:01');
insert into TSDCHAR ( RNUM, C1 ) values ( 36, '10:20:30');
insert into TSDCHAR ( RNUM, C1 ) values ( 37, '-01:01');
insert into TSDCHAR ( RNUM, C1 ) values ( 38, '10:20');
insert into TSDCHAR ( RNUM, C1 ) values ( 39, 'TRUE');
insert into TSDCHAR ( RNUM, C1 ) values ( 40, 'FALSE');
insert into TSDCHAR ( RNUM, C1 ) values ( 41, 'UNKNOWN');
insert into TSDCHAR ( RNUM, C1 ) values ( 42, '2001 01 01');
insert into TSDCHAR ( RNUM, C1 ) values ( 43, '1990- 07 : 15');
insert into TSDCHAR ( RNUM, C1 ) values ( 44, '2012, 13 : 07');
insert into TSDCHAR ( RNUM, C1 ) values ( 45, '2014-03-24');
insert into TSDCHAR ( RNUM, C1 ) values ( 46, '15.3; 4');
insert into TSDCHAR ( RNUM, C1 ) values ( 47, '17 06 ;01');
insert into TSDCHAR ( RNUM, C1 ) values ( 48, '10 12 31');
insert into TSDCHAR ( RNUM, C1 ) values ( 49, '1995');
insert into TSDCHAR ( RNUM, C1 ) values ( 50, '10-59/59 pm');
insert into TSDCHAR ( RNUM, C1 ) values ( 51, '11- 23 / 59');
insert into TSDCHAR ( RNUM, C1 ) values ( 52, '25, 23 :15');
insert into TSDCHAR ( RNUM, C1 ) values ( 53, '15.23 10 A.m.');
insert into TSDCHAR ( RNUM, C1 ) values ( 54, '5:17/ 15-50273');
insert into TSDCHAR ( RNUM, C1 ) values ( 55, '18456');
insert into TSDCHAR ( RNUM, C1 ) values ( 56, '23');
insert into TSDCHAR ( RNUM, C1 ) values ( 57, '10 pM');
insert into TSDCHAR ( RNUM, C1 ) values ( 58, '23:59:50.8983');
insert into TSDCHAR ( RNUM, C1 ) values ( 59, '15-25-37,935 +01:00');
insert into TSDCHAR ( RNUM, C1 ) values ( 60, '11- 23 / 59 +08');
insert into TSDCHAR ( RNUM, C1 ) values ( 61, '32473 -15:32');
insert into TSDCHAR ( RNUM, C1 ) values ( 62, '9- 56 / 59 +08:15 Z');
insert into TSDCHAR ( RNUM, C1 ) values ( 63, '23:59:50.8983+08:15');
insert into TSDCHAR ( RNUM, C1 ) values ( 64, '01:01:2001T10-32-49 P.M.');
insert into TSDCHAR ( RNUM, C1 ) values ( 65, '1999- 01 01 : 9- 9 / 9');
insert into TSDCHAR ( RNUM, C1 ) values ( 66, '1783 32473');
insert into TSDCHAR ( RNUM, C1 ) values ( 67, '1990 17 , 15 :17');
insert into TSDCHAR ( RNUM, C1 ) values ( 68, '07-07-2007/59:49:15 -05:34');
insert into TSDCHAR ( RNUM, C1 ) values ( 69, '1999- 01 01 : 11- 15 / 23 +08:07');
insert into TSDCHAR ( RNUM, C1 ) values ( 70, '1999 1 1 : T11- 15 / 23 +08:07Z');
insert into TSDCHAR ( RNUM, C1 ) values ( 71, '1999 32473 +08:07');

**Comment by dain** [comment] 2017-04-03 17:29
Can you post the stack trace printed when you run with `--debug` on the command line?  Also, do you need all of the insert statements to reproduce the problem?

**Comment by the6campbells** [comment] 2017-04-04 02:33
you only need the first 3 rows which the in predicate would filter against.  running via Teradata/Presto JDBC so unsure how --debug would be passed as property to the driver.

trying to push such a cast requires cast(rtrim(cast(c1 as varchar)) as bigint)   which avoids  

Can not cast '-1                         ' to BIGINT.
select rnum, cast(cast(c1 as varchar) as bigint) from mysql_cert.dbcert.tsdchar where rnum in (0,1,2)

**Comment by dain** [comment] 2017-04-04 03:16
Oh I missed that you are explicitly casting to c1 to BIGINT.  

There are two issues here.  First is you are using a fixed CHAR type, which is currently under development.  Currently, I believe that when casting from a CHAR to VARCHAR, Presto pads the char to the full length, which I'm pretty sure this doesn't follow the spec.  There are a few people working on finishing the CHAR type, and I would suggest just avoiding it for now (actually, the CHAR type has super weird behavior in the spec and I would avoid it entirely).  The second problem is it looks like you are trying to cast all sorts of strange stuff to BIGINT.  BIGINT is a 64bit integer number and only a  character string containing a valid number will cast correctly. 

Also, you can test this with the simple query `SELECT CAST(CAST('-1' AS CHAR(27)) AS BIGINT);`.

I'm going to close this issues for now, and suggest you bring up this on the mailing list so you can coordinate with the others working on the CHAR type.

**Closed by dain** 2017-04-04 03:16 UTC

**Comment by the6campbells** [comment] 2017-04-04 03:29
SELECT CAST(CAST('-1' AS CHAR(27)) AS BIGINT)
Cannot cast char(27) to bigint

-vs- SELECT CAST(CAST('-1' AS VARCHAR) AS BIGINT) etc.

The test is applying a predicate on RNUM in (0,1,2) so not attempting to cast what would be non-valid character literals to integer types. 

Very familiar with ISO-201x spec and how solutions including MySQL, Postgres and Hive do not follow it re internal processing plus how solutions like MySQL stick trailing blanks back on the projection via the driver etc. 

Cheers.
