### ISSUE TITLE
[Native] Query with aliased columns in grouping sets produce incorrect results

### ISSUE THREAD

**Issue by mknegi** [prestodb/presto#20917] opened 2023-09-20 05:00 UTC
## Query
SELECT lna, lnb, SUM(quantity) FROM (SELECT linenumber lna, linenumber lnb, CAST(quantity AS BIGINT) quantity FROM lineitem) GROUP BY GROUPING SETS ((lna, lnb), (lna), (lnb), ())

## Expected Behavior
```
        assertQuery("SELECT lna, lnb, SUM(quantity) " +
                        "FROM (SELECT linenumber lna, linenumber lnb, CAST(quantity AS BIGINT) quantity FROM lineitem) " +
                        "GROUP BY GROUPING SETS ((lna, lnb), (lna), (lnb), ())",
                "SELECT linenumber, linenumber, SUM(CAST(quantity AS BIGINT)) FROM lineitem GROUP BY linenumber UNION ALL " +
                        "SELECT linenumber, NULL, SUM(CAST(quantity AS BIGINT)) FROM lineitem GROUP BY linenumber UNION ALL " +
                        "SELECT NULL, linenumber, SUM(CAST(quantity AS BIGINT)) FROM lineitem GROUP BY linenumber UNION ALL " +
                        "SELECT NULL, NULL, SUM(CAST(quantity AS BIGINT)) FROM lineitem");
```

## Current Behavior
```
java.lang.AssertionError: For query: 
 SELECT lna, lnb, SUM(quantity) FROM (SELECT linenumber lna, linenumber lnb, CAST(quantity AS BIGINT) quantity FROM lineitem) GROUP BY GROUPING SETS ((lna, lnb), (lna), (lnb), ())
not equal
Actual rows (up to 100 of 14 extra rows shown, 22 rows in total):
    [null, 3, 274364]
    [null, 3, 274364]
    [null, 4, 219863]
    [null, 4, 219863]
    [null, 1, 385698]
    [null, 1, 385698]
    [null, 6, 109157]
    [null, 6, 109157]
    [null, 5, 161918]
    [null, 5, 161918]
    [null, 7, 54701]
    [null, 7, 54701]
    [null, 2, 330426]
    [null, 2, 330426]
Expected rows (up to 100 of 14 missing rows shown, 22 rows in total):
    [1, 1, 385698]
    [2, 2, 330426]
    [3, 3, 274364]
    [4, 4, 219863]
    [5, 5, 161918]
    [6, 6, 109157]
    [7, 7, 54701]
    [1, null, 385698]
    [2, null, 330426]
    [3, null, 274364]
    [4, null, 219863]
    [5, null, 161918]
    [6, null, 109157]
    [7, null, 54701]
```

**Comment by aditi-pandit** [comment] 2023-09-22 23:59
This has the same root cause as https://github.com/prestodb/presto/issues/20910

**Comment by yzhang1991** [comment] 2023-09-27 03:49
Closing as duplicate of https://github.com/prestodb/presto/issues/20910

**Closed by yzhang1991** 2023-09-27 03:49 UTC
Labels: bug, tests, prestissimo
