### ISSUE TITLE
Incorrect Stage Performance Display on Presto UI

### ISSUE THREAD

**Issue by cymvp** [prestodb/presto#14529] opened 2020-05-14 10:15 UTC
When I want to use “Stage Performance” UI to analyze SQL on 0.234, I found that there are some abnormal displays in this page:
1. Incomplete Pipeline display: Only Pipeline1 and corresponding operators shows in the UI(Pipeline 0 is absent);
2. When clicking on Operators, status of Operator can’t be shown correctly;
![image](https://user-images.githubusercontent.com/1830336/81921742-abd7a880-960d-11ea-971f-7b69efde104f.png)

After checking the code, we believe that root cause is that in returned json, nodeInfo[type] has been changed to class name, but js script still regards it as abbreviation name.
![image](https://user-images.githubusercontent.com/1830336/81922345-8f883b80-960e-11ea-93a7-c8a687d740db.png)

We believe this issue is introduced since 0.220, and the commit is: https://github.com/prestodb/presto/commit/3f6e56d025b729d20fd3f4939698c90c355579ab
![image](https://user-images.githubusercontent.com/1830336/81922507-cbbb9c00-960e-11ea-8992-541ff901bebd.png)

We depend on this UI to analyze queries and performance, so is there any idea to fix it?

**Comment by ChunxuTang** [comment] 2020-05-22 22:47
Reproduced that bug on my machine. As @cymvp  mentioned, the root cause is that the web-side is still using the short names of types but the server-side has removed the name conversion.

I'll send a PR to fix that.

**Comment by rschlussel** [comment] 2020-06-11 21:28
thanks @ChunxuTang  for fixing this! I'm closing the issue since the fix has been merged.  it should be available in the upcoming 0.237 release.

**Closed by rschlussel** 2020-06-11 21:28 UTC
