### ISSUE TITLE
Tests failing in TestDistributedQueriesNoHashGeneration

### ISSUE THREAD

**Issue by ArturGajowy** [prestodb/presto#7642] opened 2017-03-22 10:36 UTC
13 tests are failing  in `TestDistributedQueriesNoHashGeneration`:

```
TestDistributedQueriesNoHashGeneration.testChainedUnionsWithOrder
TestDistributedQueriesNoHashGeneration.testExcept
TestDistributedQueriesNoHashGeneration.testExceptWithAggregation
TestDistributedQueriesNoHashGeneration.testIntersect
TestDistributedQueriesNoHashGeneration.testIntersectWithAggregation
TestDistributedQueriesNoHashGeneration.testMergeEmptyNonEmptyApproxSet
TestDistributedQueriesNoHashGeneration.testSemiJoinAggregationUnionNullHandling
TestDistributedQueriesNoHashGeneration.testSubqueryUnion
TestDistributedQueriesNoHashGeneration.testUnion
TestDistributedQueriesNoHashGeneration.testUnionDistinct
TestDistributedQueriesNoHashGeneration.testUnionRequiringCoercion
TestDistributedQueriesNoHashGeneration.testUnionWithAggregation
TestDistributedQueriesNoHashGeneration.testUnionWithAggregationAndJoin
```

This is on commit d4e08bf, but probably was introduced eariler.

This is probably due to #5864 not having a resolution so far.

```
2017-03-22 15:25:19 INFO Life cycle stopped.
Tests run: 630, Failures: 13, Errors: 0, Skipped: 0, Time elapsed: 178.197 sec <<< FAILURE! - in com.facebook.presto.tests.TestDistributedQueriesNoHashGeneration
testChainedUnionsWithOrder(com.facebook.presto.tests.TestDistributedQueriesNoHashGeneration)  Time elapsed: 0.031 sec  <<< FAILURE!
java.lang.AssertionError: Execution of 'actual' query failed: SELECT orderkey FROM orders UNION (SELECT custkey FROM orders UNION SELECT linenumber FROM lineitem) UNION ALL SELECT orderkey FROM lineitem ORDER BY orderkey
Caused by: com.facebook.presto.client.FailureInfo$FailureException: Duplicate node id found 160 between com.facebook.presto.sql.planner.plan.AggregationNode@30b40193 and com.facebook.presto.sql.planner.plan.AggregationNode@6b1e764

testExcept(com.facebook.presto.tests.TestDistributedQueriesNoHashGeneration)  Time elapsed: 0.024 sec  <<< FAILURE!
java.lang.AssertionError: Execution of 'actual' query failed: SELECT regionkey FROM nation WHERE nationkey < 7 EXCEPT select regionkey FROM nation WHERE nationkey > 21
Caused by: com.facebook.presto.client.FailureInfo$FailureException: Duplicate node id found 134 between com.facebook.presto.sql.planner.plan.AggregationNode@1b7cefe4 and com.facebook.presto.sql.planner.plan.AggregationNode@7c883488

testExceptWithAggregation(com.facebook.presto.tests.TestDistributedQueriesNoHashGeneration)  Time elapsed: 0.018 sec  <<< FAILURE!
java.lang.AssertionError: Execution of 'actual' query failed: SELECT COUNT(*) FROM nation EXCEPT SELECT COUNT(regionkey) FROM nation where regionkey < 3 HAVING SUM(regionkey) IS NOT NULL
Caused by: com.facebook.presto.client.FailureInfo$FailureException: Duplicate node id found 167 between com.facebook.presto.sql.planner.plan.AggregationNode@1416f539 and com.facebook.presto.sql.planner.plan.AggregationNode@13e4134b

testIntersect(com.facebook.presto.tests.TestDistributedQueriesNoHashGeneration)  Time elapsed: 0.018 sec  <<< FAILURE!
java.lang.AssertionError: Execution of 'actual' query failed: SELECT regionkey FROM nation WHERE nationkey < 7 INTERSECT select regionkey FROM nation WHERE nationkey > 21
Caused by: com.facebook.presto.client.FailureInfo$FailureException: Duplicate node id found 134 between com.facebook.presto.sql.planner.plan.AggregationNode@6fbc7945 and com.facebook.presto.sql.planner.plan.AggregationNode@53f3a315

testIntersectWithAggregation(com.facebook.presto.tests.TestDistributedQueriesNoHashGeneration)  Time elapsed: 0.006 sec  <<< FAILURE!
java.lang.AssertionError: Execution of 'actual' query failed: SELECT COUNT(*) FROM nation INTERSECT SELECT COUNT(regionkey) FROM nation HAVING SUM(regionkey) IS NOT NULL
Caused by: com.facebook.presto.client.FailureInfo$FailureException: Duplicate node id found 151 between com.facebook.presto.sql.planner.plan.AggregationNode@572027c5 and com.facebook.presto.sql.planner.plan.AggregationNode@758f1c43

testMergeEmptyNonEmptyApproxSet(com.facebook.presto.tests.TestDistributedQueriesNoHashGeneration)  Time elapsed: 0.021 sec  <<< FAILURE!
com.facebook.presto.client.FailureInfo$FailureException: Duplicate node id found 115 between com.facebook.presto.sql.planner.plan.AggregationNode@5feffccc and com.facebook.presto.sql.planner.plan.AggregationNode@6937757e

testSemiJoinAggregationUnionNullHandling(com.facebook.presto.tests.TestDistributedQueriesNoHashGeneration)  Time elapsed: 0.101 sec  <<< FAILURE!
java.lang.AssertionError: 
Execution of 'actual' query failed: SELECT orderkey
  IN (
    SELECT orderkey
    FROM (
      SELECT CASE WHEN orderkey % 500 = 0 THEN NULL ELSE orderkey END AS orderkey
      FROM orders
      WHERE orderkey % 200 = 0
      UNION ALL
      SELECT CASE WHEN orderkey % 600 = 0 THEN NULL ELSE orderkey END AS orderkey
      FROM orders
      WHERE orderkey % 300 = 0
    )
    GROUP BY orderkey
  )
FROM (
  SELECT orderkey
  FROM lineitem
  WHERE orderkey % 100 = 0)
Caused by: com.facebook.presto.client.FailureInfo$FailureException: Duplicate node id found 231 between com.facebook.presto.sql.planner.plan.AggregationNode@20fa2676 and com.facebook.presto.sql.planner.plan.AggregationNode@75629ceb

testSubqueryUnion(com.facebook.presto.tests.TestDistributedQueriesNoHashGeneration)  Time elapsed: 0.007 sec  <<< FAILURE!
java.lang.AssertionError: Execution of 'actual' query failed: SELECT * FROM (SELECT orderkey FROM orders UNION SELECT custkey FROM orders UNION SELECT orderkey FROM orders) ORDER BY orderkey LIMIT 1000
Caused by: com.facebook.presto.client.FailureInfo$FailureException: Duplicate node id found 131 between com.facebook.presto.sql.planner.plan.AggregationNode@1cfb4892 and com.facebook.presto.sql.planner.plan.AggregationNode@627cc0a7

testUnion(com.facebook.presto.tests.TestDistributedQueriesNoHashGeneration)  Time elapsed: 0.006 sec  <<< FAILURE!
java.lang.AssertionError: Execution of 'actual' query failed: SELECT orderkey FROM orders UNION SELECT custkey FROM orders
Caused by: com.facebook.presto.client.FailureInfo$FailureException: Duplicate node id found 74 between com.facebook.presto.sql.planner.plan.AggregationNode@12142e11 and com.facebook.presto.sql.planner.plan.AggregationNode@10193656

testUnionDistinct(com.facebook.presto.tests.TestDistributedQueriesNoHashGeneration)  Time elapsed: 0.007 sec  <<< FAILURE!
java.lang.AssertionError: Execution of 'actual' query failed: SELECT orderkey FROM orders UNION DISTINCT SELECT custkey FROM orders
Caused by: com.facebook.presto.client.FailureInfo$FailureException: Duplicate node id found 74 between com.facebook.presto.sql.planner.plan.AggregationNode@3575cf3e and com.facebook.presto.sql.planner.plan.AggregationNode@6d833923

testUnionRequiringCoercion(com.facebook.presto.tests.TestDistributedQueriesNoHashGeneration)  Time elapsed: 0.084 sec  <<< FAILURE!
java.lang.AssertionError: Execution of 'actual' query failed: SELECT * FROM (VALUES 1) UNION SELECT * FROM (VALUES 1.0, 2)
Caused by: com.facebook.presto.client.FailureInfo$FailureException: Duplicate node id found 93 between com.facebook.presto.sql.planner.plan.AggregationNode@578eae09 and com.facebook.presto.sql.planner.plan.AggregationNode@14b3aef

testUnionWithAggregation(com.facebook.presto.tests.TestDistributedQueriesNoHashGeneration)  Time elapsed: 0.008 sec  <<< FAILURE!
java.lang.AssertionError: Execution of 'actual' query failed: SELECT ds, count(*) FROM (   SELECT orderdate ds, orderkey FROM orders    UNION ALL    SELECT shipdate ds, orderkey FROM lineitem) a GROUP BY ds
Caused by: com.facebook.presto.client.FailureInfo$FailureException: Duplicate node id found 108 between com.facebook.presto.sql.planner.plan.AggregationNode@5d32811c and com.facebook.presto.sql.planner.plan.AggregationNode@4766655

testUnionWithAggregationAndJoin(com.facebook.presto.tests.TestDistributedQueriesNoHashGeneration)  Time elapsed: 0.014 sec  <<< FAILURE!
java.lang.AssertionError: Execution of 'actual' query failed: SELECT * FROM ( SELECT orderkey, count(*) FROM (   SELECT orderdate ds, orderkey FROM orders    UNION ALL    SELECT shipdate ds, orderkey FROM lineitem) a GROUP BY orderkey) t JOIN orders o ON (o.orderkey = t.orderkey)
Caused by: com.facebook.presto.client.FailureInfo$FailureException: Duplicate node id found 153 between com.facebook.presto.sql.planner.plan.AggregationNode@df38916 and com.facebook.presto.sql.planner.plan.AggregationNode@21f2ac40


Results :

Failed tests: 
  TestDistributedQueriesNoHashGeneration>AbstractTestQueries.testChainedUnionsWithOrder:5576->AbstractTestQueryFramework.assertQueryOrdered:117 Execution of 'actual' query failed: SELECT orderkey FROM orders UNION (SELECT custkey FROM orders UNION SELECT linenumber FROM lineitem) UNION ALL SELECT orderkey FROM lineitem ORDER BY orderkey
  TestDistributedQueriesNoHashGeneration>AbstractTestQueries.testExcept:1785->AbstractTestQueryFramework.assertQuery:107->AbstractTestQueryFramework.assertQuery:112 Execution of 'actual' query failed: SELECT regionkey FROM nation WHERE nationkey < 7 EXCEPT select regionkey FROM nation WHERE nationkey > 21
  TestDistributedQueriesNoHashGeneration>AbstractTestQueries.testExceptWithAggregation:1831->AbstractTestQueryFramework.assertQuery:107->AbstractTestQueryFramework.assertQuery:112 Execution of 'actual' query failed: SELECT COUNT(*) FROM nation EXCEPT SELECT COUNT(regionkey) FROM nation where regionkey < 3 HAVING SUM(regionkey) IS NOT NULL
  TestDistributedQueriesNoHashGeneration>AbstractTestQueries.testIntersect:1722->AbstractTestQueryFramework.assertQuery:107->AbstractTestQueryFramework.assertQuery:112 Execution of 'actual' query failed: SELECT regionkey FROM nation WHERE nationkey < 7 INTERSECT select regionkey FROM nation WHERE nationkey > 21
  TestDistributedQueriesNoHashGeneration>AbstractTestQueries.testIntersectWithAggregation:1768->AbstractTestQueryFramework.assertQuery:107->AbstractTestQueryFramework.assertQuery:112 Execution of 'actual' query failed: SELECT COUNT(*) FROM nation INTERSECT SELECT COUNT(regionkey) FROM nation HAVING SUM(regionkey) IS NOT NULL
  TestDistributedQueriesNoHashGeneration.testMergeEmptyNonEmptyApproxSet » Failure
  TestDistributedQueriesNoHashGeneration>AbstractTestQueries.testSemiJoinAggregationUnionNullHandling:6170->AbstractTestQueryFramework.assertQuery:107->AbstractTestQueryFramework.assertQuery:112 Execution of 'actual' query failed: SELECT orderkey
  IN (
    SELECT orderkey
    FROM (
      SELECT CASE WHEN orderkey % 500 = 0 THEN NULL ELSE orderkey END AS orderkey
      FROM orders
      WHERE orderkey % 200 = 0
      UNION ALL
      SELECT CASE WHEN orderkey % 600 = 0 THEN NULL ELSE orderkey END AS orderkey
      FROM orders
      WHERE orderkey % 300 = 0
    )
    GROUP BY orderkey
  )
FROM (
  SELECT orderkey
  FROM lineitem
  WHERE orderkey % 100 = 0)
  TestDistributedQueriesNoHashGeneration>AbstractTestQueries.testSubqueryUnion:5687->AbstractTestQueryFramework.assertQueryOrdered:117 Execution of 'actual' query failed: SELECT * FROM (SELECT orderkey FROM orders UNION SELECT custkey FROM orders UNION SELECT orderkey FROM orders) ORDER BY orderkey LIMIT 1000
  TestDistributedQueriesNoHashGeneration>AbstractTestQueries.testUnion:5545->AbstractTestQueryFramework.assertQuery:107->AbstractTestQueryFramework.assertQuery:112 Execution of 'actual' query failed: SELECT orderkey FROM orders UNION SELECT custkey FROM orders
  TestDistributedQueriesNoHashGeneration>AbstractTestQueries.testUnionDistinct:5558->AbstractTestQueryFramework.assertQuery:107->AbstractTestQueryFramework.assertQuery:112 Execution of 'actual' query failed: SELECT orderkey FROM orders UNION DISTINCT SELECT custkey FROM orders
  TestDistributedQueriesNoHashGeneration>AbstractTestQueries.testUnionRequiringCoercion:5719->AbstractTestQueryFramework.assertQuery:122 Execution of 'actual' query failed: SELECT * FROM (VALUES 1) UNION SELECT * FROM (VALUES 1.0, 2)
  TestDistributedQueriesNoHashGeneration>AbstractTestQueries.testUnionWithAggregation:5594->AbstractTestQueryFramework.assertQuery:107->AbstractTestQueryFramework.assertQuery:112 Execution of 'actual' query failed: SELECT ds, count(*) FROM (   SELECT orderdate ds, orderkey FROM orders    UNION ALL    SELECT shipdate ds, orderkey FROM lineitem) a GROUP BY ds
  TestDistributedQueriesNoHashGeneration>AbstractTestQueries.testUnionWithAggregationAndJoin:5660->AbstractTestQueryFramework.assertQuery:107->AbstractTestQueryFramework.assertQuery:112 Execution of 'actual' query failed: SELECT * FROM ( SELECT orderkey, count(*) FROM (   SELECT orderdate ds, orderkey FROM orders    UNION ALL    SELECT shipdate ds, orderkey FROM lineitem) a GROUP BY orderkey) t JOIN orders o ON (o.orderkey = t.orderkey)

Tests run: 630, Failures: 13, Errors: 0, Skipped: 0
```

**Comment by electrum** [comment] 2017-03-22 18:44
Thanks. We saw this on our internal Jenkins. I think this shows that we should run them in Travis, even if costs more build slots, because it's far easier to fix such regressions before they are merged.

**Comment by electrum** [comment] 2017-03-22 18:47
I tried enabling in #7267 but it takes too long. Will need to split them out.

**Comment by electrum** [comment] 2017-03-22 18:52
The last successful build was f3119b956aa6e400a4ee95631c4864aa7785a3c6

**Comment by martint** [comment] 2017-03-22 19:22
It's caused by 767f3434799f253f16e452b0b7423170ed9ba61b. @pnowojski, can you take a look?

**Comment by martint** [comment] 2017-03-22 19:31
The problem seems to be that PartialAggregationPushdown is creating a copy of the aggregation and placing it below each branch of the union, but it's not assigning new node ids to each instance.

**Closed** 2017-03-23 00:30 UTC
Labels: RELEASE-BLOCKER, tests
