### ISSUE TITLE
Uncategorized error: Unsupported correlated subquery type 

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#7248] opened 2017-01-30 21:10 UTC
```
java.lang.IllegalArgumentException: Unsupported correlated subquery type
com.facebook.presto.sql.planner.sanity.NoApplyNodeLeftChecker$1.visitApply(NoApplyNodeLeftChecker.java:42)
com.facebook.presto.sql.planner.plan.ApplyNode.accept(ApplyNode.java:140)
com.facebook.presto.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:26)
com.facebook.presto.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:19)
com.facebook.presto.sql.planner.plan.PlanVisitor.visitProject(PlanVisitor.java:40)
com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:92)
com.facebook.presto.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:26)
com.facebook.presto.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:19)
com.facebook.presto.sql.planner.plan.PlanVisitor.visitExchange(PlanVisitor.java:175)
com.facebook.presto.sql.planner.plan.ExchangeNode.accept(ExchangeNode.java:195)
com.facebook.presto.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:26)
com.facebook.presto.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:19)
com.facebook.presto.sql.planner.plan.PlanVisitor.visitOutput(PlanVisitor.java:50)
com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:82)
com.facebook.presto.sql.planner.sanity.NoApplyNodeLeftChecker.validate(NoApplyNodeLeftChecker.java:33)
com.facebook.presto.sql.planner.sanity.PlanSanityChecker.lambda$validate$0(PlanSanityChecker.java:44)
java.lang.Iterable.forEach(Iterable.java:75)
com.facebook.presto.sql.planner.sanity.PlanSanityChecker.validate(PlanSanityChecker.java:44)
com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:127)
com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:111)
com.facebook.presto.sql.analyzer.QueryExplainer.getLogicalPlan(QueryExplainer.java:136)
com.facebook.presto.sql.analyzer.QueryExplainer.getPlan(QueryExplainer.java:94)
com.facebook.presto.sql.rewrite.ExplainRewrite$Visitor.getQueryPlan(ExplainRewrite.java:126)
com.facebook.presto.sql.rewrite.ExplainRewrite$Visitor.visitExplain(ExplainRewrite.java:104)
com.facebook.presto.sql.rewrite.ExplainRewrite$Visitor.visitExplain(ExplainRewrite.java:60)
com.facebook.presto.sql.tree.Explain.accept(Explain.java:73)
com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
com.facebook.presto.sql.rewrite.ExplainRewrite.rewrite(ExplainRewrite.java:57)
com.facebook.presto.sql.rewrite.StatementRewrite.rewrite(StatementRewrite.java:51)
com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:65)
com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:60)
com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:290)
com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:276)
com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:234)
com.facebook.presto.execution.resourceGroups.InternalResourceGroup.lambda$startInBackground$1(InternalResourceGroup.java:478)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:745)

**Comment by martint** [comment] 2017-01-30 21:34
Duplicate of https://github.com/prestodb/presto/issues/6491

**Closed by martint** 2017-01-30 21:34 UTC
Labels: bug, duplicate
