### ISSUE TITLE
Flaky test: testFinalStageInfo(com.facebook.presto.execution.TestSqlStageExecution)

### ISSUE THREAD

**Issue by sopel39** [prestodb/presto#12095] opened 2018-12-18 11:00 UTC
```
[ERROR] Tests run: 5512, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1,181.988 s <<< FAILURE! - in TestSuite
[ERROR] testFinalStageInfo(com.facebook.presto.execution.TestSqlStageExecution)  Time elapsed: 0.008 s  <<< FAILURE!
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.facebook.presto.execution.TestSqlStageExecution.testFinalStageInfoInternal(TestSqlStageExecution.java:152)
	at com.facebook.presto.execution.TestSqlStageExecution.testFinalStageInfo(TestSqlStageExecution.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by sopel39** [comment] 2018-12-18 11:24
FYI: @dain @arhimondr

**Comment by arhimondr** [comment] 2018-12-18 16:54
I was trying to debug it, but i didn't manage to reproduce it.

I suspect that the race happens when scheduling a new task when the `SqlStageExecution` is already aborted.

Consider next scenario

1. Some number of tasks already scheduled: https://github.com/prestodb/presto/blob/master/presto-main/src/test/java/com/facebook/presto/execution/TestSqlStageExecution.java#L134
2. `SqlStageExecution#abort` is called: https://github.com/prestodb/presto/blob/master/presto-main/src/test/java/com/facebook/presto/execution/TestSqlStageExecution.java#L147
3. `SqlStageExecution` cancels all the tasks, and waits for the final task info: https://github.com/prestodb/presto/blob/master/presto-main/src/main/java/com/facebook/presto/execution/SqlStageExecution.java#L255
4. `SqlStageExecution` receives final stage info from all the tasks, `finalStatus` callback is triggered: 
5. New task is scheduled, and since the `SqlStageExecution` is aborted, the task is being aborted instead of started. But since `Task#abort` is asynchronous, the task may be in non final state fore a while.
6. `addFinalStatusListener` (https://github.com/prestodb/presto/blob/master/presto-main/src/test/java/com/facebook/presto/execution/TestSqlStageExecution.java#L118) calls `stage.getStageInfo` in the moment when newly added task is already in the `allTasks` list, but hasn't been switched to the final stage.

**Comment by arhimondr** [comment] 2018-12-18 16:55
Why is it needed to keep adding tasks to the `allTasks` when stage is already cancelled? If stage is cancelled, why `scheduleTask`, `scheduleSplits` and `addExchangeLocations` cannot be simply ignored?

**Comment by sopel39** [comment] 2018-12-28 15:32
failed again in: https://github.com/prestodb/presto/pull/12115

**Comment by findepi** [comment] 2018-12-31 07:10
failed again in: https://github.com/prestodb/presto/pull/12150

**Comment by raghavsethi** [comment] 2018-12-31 08:08
@dain is on vacation at the moment, but I suspect he will roll it into/fix it with a PR he's about to put up.

**Comment by electrum** [comment] 2018-12-31 08:33
It seems to fail about half the time for me in Travis.

**Comment by cbanek** [comment] 2019-01-02 20:00
This has come up both on my local dev machine and in Travis (with my PR).

**Comment by dain** [comment] 2019-01-04 17:49
I'm working on reproducing this by adding a kill switch MockRemoteTaskFactory which will prevent `abort` from working on tasks.  That way new tasks can't finish.  Assuming that is the core issue, I'll try to figure out how it can be fixed.

**Comment by dain** [comment] 2019-01-04 23:12
I was able to reproduce this by modifying `MockRemoteTaskFactory`.  The problem is what @arhimondr pointed out, adding new tasks after final info is set.  I see two things that I think need to be fixed:

1) we should "capture" the final stage info once it is created, so it can not be changed.
2) we should not allow tasks to be added after the stage is in a done state.

I think the first one is pretty straight forward, but I think the second one should be fixed first since it would be strange to have tasks in a stage that are not in the stage info.  The second one is more tricky to fix, because we can't do the easy thing and simply throw an exception because a stage could finish early due to a limit.  Instead, we need to adapt the callers to expect an `Optional<RemoteTask>`.  I'm working on these now.

**Closed** 2019-01-09 01:04 UTC
Labels: RELEASE-BLOCKER
