### ISSUE TITLE
TestRaptorDistributedQueries.testScalarSubquery is flaky

### ISSUE THREAD

**Issue by ArturGajowy** [prestodb/presto#8601] opened 2017-07-26 09:36 UTC
Tests run: 1668, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1,356.01 sec <<< FAILURE! - in TestSuite
testScalarSubquery(com.facebook.presto.raptor.TestRaptorDistributedQueries)  Time elapsed: 51.56 sec  <<< FAILURE!
java.lang.AssertionError: Expected query to fail: SELECT orderkey, totalprice FROM orders ORDER BY (VALUES 1, 2)

Results :

Failed tests: 
  TestRaptorDistributedQueries>AbstractTestQueries.testScalarSubquery:6873->AbstractTestQueryFramework.assertQueryFails:188 Expected query to fail: SELECT orderkey, totalprice FROM orders ORDER BY (VALUES 1, 2)

Tests run: 1668, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 22:53 min
[INFO] Finished at: 2017-07-26T07:58:55Z
[INFO] Final Memory: 69M/260M
[INFO] ------------------------------------------------------------------------

**Comment by dain** [comment] 2017-07-26 17:40
This is really strange.  The query should fail when processing the scalar sub query for `ORDER BY` in `com.facebook.presto.operator.EnforceSingleRowOperator`.   Unless the `orders` table is empty, I think there is likely a bug in one of the operators or a race condition in the engine.

**Comment by kokosing** [comment] 2017-07-26 20:02
> Unless the orders table is empty

@dain IMO it does not matter, there will be a join and scalar sub query (`EnforceSingleRow`) is on the build side, as I understand it will be executed disregarding if probe has rows. So it should fail even if probe is empty.

It looks like both probe and build side had no data, or build had at most single row which would even more strange.

@ArturGajowy How did you encounter this? Is this correct that this test took `Time elapsed: 51.56 sec`?

**Comment by dain** [comment] 2017-07-26 20:14
`CROSS JOIN` is handled by the `NestedLoopJoinOperator` which has an optimization that if the probe is empty, it finished immediately.  This is the same behavior we would get with an optimizer that new the probe produced zero rows (e.g., SELECT * FROM x WHERE false), and could therefore could replace the JOIN with and empty VALUES node.  

@martint thoughts?

**Comment by martint** [comment] 2017-07-26 20:19
> @martint thoughts?

Yes, that makes sense. If we wanted to fail statically, we'd need to do it at analysis time.

I tried running the query 10000 times on my IDE and couldn't reproduce the problem. My initial thought is that this is some race condition in the setup of tables for raptor tests. Does it happen for any other connector ?

**Comment by findepi** [comment] 2017-11-23 22:59
I don't recall seeing this for some time. Do you? May we super-optimistically close this?

**Closed** 2017-11-24 03:01 UTC
Labels: raptor, tests
