### ISSUE TITLE
com.facebook.presto.iceberg.nessie.TestIcebergSmokeNessie.testRegisterTable flaked

### ISSUE THREAD

**Issue by elharo** [prestodb/presto#22897] opened 2024-06-03 14:33 UTC
see https://github.com/prestodb/presto/actions/runs/9304937290/job/25610720743?pr=22872

Error:  Tests run: 2916, Failures: 1, Errors: 0, Skipped: 34, Time elapsed: 3,130.707 s <<< FAILURE! - in TestSuite
Error:  com.facebook.presto.iceberg.nessie.TestIcebergSmokeNessie.testRegisterTable  Time elapsed: 0.091 s  <<< FAILURE!
java.lang.AssertionError: 
For query: 
 SELECT * FROM register_new
 actual column types:
 [integer, integer]
expected column types:
[integer, integer]

not equal
Expected rows (1 of 1 missing rows shown, 1 rows in total):
    [1, 1]

	at org.testng.Assert.fail(Assert.java:110)
	at com.facebook.presto.tests.QueryAssertions.assertEqualsIgnoreOrder(QueryAssertions.java:280)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:233)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:106)
	at com.facebook.presto.tests.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:164)
	at com.facebook.presto.iceberg.IcebergDistributedSmokeTestBase.testRegisterTable(IcebergDistributedSmokeTestBase.java:1378)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

[INFO] 
[INFO] Results:
[INFO] 
Error:  Failures: 
Error:    TestIcebergSmokeNessie>IcebergDistributedSmokeTestBase.testRegisterTable:1378->AbstractTestQueryFramework.assertQuery:164 For query: 
 SELECT * FROM register_new
 actual column types:
 [integer, integer]
expected column types:
[integer, integer]

not equal
Expected rows (1 of 1 missing rows shown, 1 rows in total):
    [1, 1]

**Comment by tdcmeehan** [comment] 2024-06-03 14:39
Duplicate of #22848

**Closed by tdcmeehan** 2024-06-03 14:39 UTC
Labels: flaky-test
