### ISSUE TITLE
Can presto  support  to skip  corrupted files  rather than  failing the  query

### ISSUE THREAD

**Issue by 820678105** [prestodb/presto#20778] opened 2023-09-06 02:59 UTC
## Your Environment

* Presto version used: Presto-0.275
* Storage (HDFS/S3/GCS..): S3 parquet files
* Data source and connector used: hive
* Deployment (Cloud or On-prem): cloud
* [Pastebin](https://pastebin.com/) link to the complete debug logs:

## Expected Behavior

When using presto to query parquet files on s3,  the query  would fail if  some files  were  corrputed.  But this is not what we wanted. We expect that  the query can skip the corrputed files to be  successful, even the result may not be correct.
## Steps to Reproduce

1.
2.
3.
4.

**Comment by tdcmeehan** [comment] 2023-09-06 12:31
Presto is designed to return precise results.  I am closing this as it's not a bug, but you would like this feature to exist, please raise a feature request for it--thanks!

**Closed by tdcmeehan** 2023-09-06 12:31 UTC
Labels: bug

**Comment by 820678105** [comment] 2023-09-07 01:11
> Presto is designed to return precise results. I am closing this as it's not a bug, but you would like this feature to exist, please raise a feature request for it--thanks!

ok, thank you.
