### ISSUE TITLE
Presto Iceberg connector support for materialized view 

### ISSUE THREAD

**Issue by rohanpednekar** [prestodb/presto#16511] opened 2021-07-26 18:17 UTC
cc @ChunxuTang

**Comment by yingsu00** [comment] 2023-08-10 06:05
@rohanpednekar @pratyakshsharma Is this a duplicate of https://github.com/prestodb/presto/issues/20439?

**Comment by tdcmeehan** [comment] 2024-03-25 14:44
Closing in favor of #16511

**Closed by tdcmeehan** 2024-03-25 14:44 UTC
Labels: Roadmap, iceberg
