### ISSUE TITLE
DECIMAL not handled in HiveCoercionPolicy

### ISSUE THREAD

**Issue by dain** [prestodb/presto#10482] opened 2018-04-24 19:01 UTC
HiveCoercionPolicy does not handle DECIMAL at all.  This is needed for schema changes to and from decimal types.

**Comment by findepi** [comment] 2018-04-25 07:34
@losipiuk is this what your https://github.com/prestodb/presto/pull/9422 is doing?

**Comment by findepi** [comment] 2018-04-25 07:36
@dain this issue looks like a duplicate of https://github.com/prestodb/presto/issues/7658 . Let me close this.

**Closed by findepi** 2018-04-25 07:36 UTC
