### ISSUE TITLE
Highly selective LIMIT queries don't complete as soon as required data is output

### ISSUE THREAD

**Issue by martint** [prestodb/presto#9317] opened 2017-11-09 01:32 UTC
A query like the following one on a large table (19.8B rows, 347GB) where only one row matches the where clause keeps running after that row is returned to the client.

```sql
SELECT 1 
FROM t 
WHERE x = ...
LIMIT 1
```

It affects 0.188. Not sure about earlier versions.

**Comment by martint** [comment] 2017-11-09 02:01
The query doesn't tear down until all splits have been enumerated.

**Comment by martint** [comment] 2017-11-09 02:18
A query that matches 2 rows returns quickly with a LIMIT 1 (but not with LIMIT 2), so it may be a matter of a `<` vs `<=` sign somewhere.

**Comment by findepi** [comment] 2017-11-09 08:21
It may be `<` vs `<=` or some buffering before `TopN`. If it was `master` and not 0.188 I'd suspect merge tiny pages feature.

**Comment by haozhun** [comment] 2017-11-09 19:06
I didn't realize that https://github.com/prestodb/presto/pull/8691 was merged. Thank you for pointing this out. The issue is different though. In this case, the output was sent to the client (CLI). Yet the query continues running.

Features that introduce buffering (e.g. tiny page merging) does introduce this interesting problem of working against LIMIT operator though. But that topic likely deserves its own discussion.

**Comment by findepi** [comment] 2017-11-15 08:51
#9344 (release notes) contains "Fix a bug that causes clients to hang when executing ``LIMIT`` queries when..."

@martint is this about this issue? What's the fix? #9142?

**Comment by martint** [comment] 2017-11-15 15:32
No, this is still not fixed. That's some other issue caused by the recent changes to allow distributed outputs.

@haozhun did some investigation on this problem. He's going to add some details.

**Comment by haozhun** [comment] 2017-11-16 18:51
See #9357

**Closed by haozhun** 2017-11-16 18:51 UTC
Labels: bug
