### ISSUE TITLE
Bad lambda error message

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#8028] opened 2017-05-15 17:39 UTC
The error message includes the default `toString`.

```
line 4:3: Unexpected parameters (array(bigint), integer, com.facebook.presto.sql.analyzer.TypeSignatureProvider@3d796d14, com.facebook.presto.sql.analyzer.TypeSignatureProvider@39652241) for function reduce. Expected: reduce(array(T), S, function(S,T,S), function(S,R)) T, S, R

**Comment by szymonm** [comment] 2017-07-04 11:02
Let me try that.

**Comment by szymonm** [comment] 2017-07-04 14:29
@electrum I found 2 other wrong lambda related error messages:
`java.lang.NullPointerException: type cannot be null`
on `reduce(ARRAY [1, 2, 3], 0, (s, x) -> s+x, s -> z)`

and
`com.facebook.presto.sql.analyzer.SemanticException: Expected a lambda that takes 0 argument(s) but got 2`
on `reduce(ARRAY [1, 2, 3], 0, (s, x) -> s+x, s -> s, x -> x, y -> y)`.

However, I couldn't reproduce yours. Can you give some hints on how to reproduce this?

**Comment by findepi** [comment] 2018-06-20 09:16
Let me close this, as some things has changed around type resolution in the meantime. Please file new issue if problem persists.

**Closed by findepi** 2018-06-20 09:16 UTC
Labels: beginner-task
