### ISSUE TITLE
 iceberg  hidden partitioning issues

### ISSUE THREAD

**Issue by zehui-liu** [prestodb/presto#17753] opened 2022-05-12 07:30 UTC
I find  issues about iceberg connector 。I want to use iceberg hidden partitioning and create table use this sql word :
CREATE TABLE iceberg.iceberg_hdfs.test5(
    order_id BIGINT,
    order_date DATE,
    account_number BIGINT,
    customer VARCHAR,
    country VARCHAR)
WITH (partitioning = ARRAY['month(order_date)', 'bucket(account_number, 10)', 'country']);
 it work and succeed。
but when I use insert sql like this :
insert into iceberg.iceberg_hdfs.test5
values (1, date('2020-09-16'), 1, 'one-test', 'us');
it failed . like is 
<img width="814" alt="image" src="https://user-images.githubusercontent.com/30335632/168014899-d7ecdb01-38d2-4906-8989-b8bb4ab9a9d1.png">
I traced the code call stack，found that it does not handle function transitions :
<img width="962" alt="image" src="https://user-images.githubusercontent.com/30335632/168015889-658f19b2-a098-437c-8443-dc07c734e4c4.png">
is this  a iceberg connector bug？someone can handle ，tks！

**Comment by beinan** [comment] 2022-05-12 07:58
Hey @Zhl-zero-bytes , thank you for reporting this to us!  which iceberg.catalog.type are you using?  hive or hadoop?

**Comment by Zhl-zero-bytes** [comment] 2022-05-12 08:03
> Hey @Zhl-zero-bytes , thank you for reporting this to us! which iceberg.catalog.type are you using? hive or hadoop?

thank you for reply ，we use hive catalog。

**Comment by Zhl-zero-bytes** [comment] 2022-05-12 15:40
I read the source code of trrino, and found that presto should not support this feature of iceberg, and whether there is an idea to support it in a future version?

**Comment by beinan** [comment] 2022-05-13 06:22
> I read the source code of trrino, and found that presto should not support this feature of iceberg, and whether there is an idea to support it in a future version?

Yes, looks like some of the column transform logic is missing.  I think I can fix it when I get a chance.  Or you could help us to cherry-pick trino's implementation,  what do you think?

**Comment by gupteaj** [comment] 2023-10-31 19:04
This is issue will be fixed in https://github.com/prestodb/presto/issues/20570

**Comment by tdcmeehan** [comment] 2023-10-31 19:45
Duplicate of #20570

**Closed** 2023-11-03 18:20 UTC
Labels: bug, backport, connector-specific, iceberg
