### ISSUE TITLE
tinyint(1) treated as bool but the actual value is int

### ISSUE THREAD

**Issue by fudanwjj** [prestodb/presto#5102] opened 2016-04-25 07:04 UTC
run sql return "Operator EQUAL(boolean, bigint) not registered"

**Comment by martint** [comment] 2016-04-25 16:43
Can you provide the query and table schema that reproduces the issue?

**Comment by fudanwjj** [comment] 2016-04-26 10:56
mysql table schema:
CREATE TABLE `test` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `type` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

sql:
select * from test.test.test where type=2;

result:
Operator EQUAL(boolean, bigint) not registered

**Comment by maciejgrzybek** [comment] 2016-06-23 21:19
@martint: I checked this and looks like MySQL JDBC driver is returning `Type.BIT` for `TINYINT(1)` despite the fact you can store more than 1 bit of information in such a column.

```sql
mysql> desc test;
+-------+------------------+------+-----+---------+----------------+
| Field | Type             | Null | Key | Default | Extra          |
+-------+------------------+------+-----+---------+----------------+
| id    | int(11) unsigned | NO   | PRI | NULL    | auto_increment |
| type  | tinyint(1)       | NO   |     | NULL    |                |
+-------+------------------+------+-----+---------+----------------+
2 rows in set (0.01 sec)

mysql> select type from test;
+-------+
|  type |
+-------+
|   127 |
+-------+
```

We could add BOOL -> TINYINT/SMALLINT/INTEGER/BIGINT coercion but it looks smelly given the fact all logical expressions are evaluated to boolean.

**Comment by electrum** [comment] 2016-06-23 21:49
Are you saying the MySQL connector is returning a MySQL tinyint as a boolean to Presto? If so, that should be fixed.

**Comment by raghavsethi** [comment] 2016-06-23 21:49
Wow that's pretty bad. Adding implicit coercions from bool to integral types would also be a bad idea.

**Comment by maciejgrzybek** [comment] 2016-06-27 15:16
@electrum yes but it comes from the fact that MySQL connector relies on JDBC type returned by MySQL JDBC lib which returns JDBC BOOL type for `tinyint(1)`.
@raghavsethi I agree, coercion from bool to int seems smelly.

**Comment by raghavsethi** [comment] 2016-07-07 16:15
@electrum: what's the right move given this new information?

**Comment by fudanwjj** [comment] 2016-07-19 08:47
I think I find a solution by configuring the mysql connector as "connection-url=jdbc:mysql://example.net:3306?tinyInt1isBit=false", according to mysql driver document.
Mysql driver returns tinyint type rather then boolean type.

**Comment by maciejgrzybek** [comment] 2016-07-19 12:21
@fudanwjj great! Thanks for finding a solution!
Now solution seems pretty easy: add appropriate connection property in `MySqlClient`

**Comment by maciejgrzybek** [comment] 2016-07-19 19:58
Made a PR (#5702) based on @fudanwjj's suggestion.

**Comment by maciejgrzybek** [comment] 2016-08-16 14:00
Closing as #5702 is merged.

**Closed by maciejgrzybek** 2016-08-16 14:00 UTC
