### ISSUE TITLE
[Native] Query containing reduce_agg() returns 0.0 where it should have returned NULL against velox

### ISSUE THREAD

**Issue by mknegi** [prestodb/presto#21178] opened 2023-10-17 13:55 UTC
## Expected Behavior

```
Following query returns incorrect results if run against c++ worker:

 select reduce_agg(x, 0, (x,y)->try(1/x+1/y), (x,y)->try(1/x+1/y)) from ((select 0) union all select 10.) T(x)

Actual rows (up to 100 of 1 extra rows shown, 1 rows in total):
  [0.0]
Expected rows (up to 100 of 1 missing rows shown, 1 rows in total):
  [null]


```

**Comment by pramodsatya** [comment] 2023-10-18 04:11
The function `getNativeWorkerSystemProperties` called from `PrestoNativeQueryRunnerUtils.createNativeQueryRunner()` sets the property `parse-decimal-literals-as-double` to `false`. When this property is set to the default value of `true`, the following error is seen: 
```
VeloxRuntimeError: b != 0 (0 vs. 0) Division by zero presto.default.divide(1:DECIMAL(10, 0), expr)
```

**Comment by aditi-pandit** [comment] 2023-10-18 06:41
@pramodsatya : Why is the setting of parse-decimal-literals-as-double relevant to this problem ? (I understand that it is independent one though)

**Comment by pramodsatya** [comment] 2023-10-19 20:50
I noticed some differences in the `reduce_agg` function behavior in prestissimo and presto:
With Presto:
```
presto:tpch> select reduce_agg(x, 0, (x,y)->try(x+y), (x,y)->try(x*y)) from (values (0),(1)) T(x);
 _col0
-------
     1

presto:tpch> select reduce_agg(x, 0, (x,y)->try(x+y), (x,y)->try(x*y)) from (values (0),(1),(2)) T(x);
 _col0
-------
     3
```
With Prestissimo:
```
presto:tpch> select reduce_agg(x, 0, (x,y)->try(x+y), (x,y)->try(x*y)) from (values (0),(1)) T(x);
 _col0
-------
     0

presto:tpch> select reduce_agg(x, 0, (x,y)->try(x+y), (x,y)->try(x*y)) from (values (0),(1),(2)) T(x);
 _col0
-------
     0
```

In prestissimo, the `inputFunction` is applied to each input value to obtain the respective states, these states are then combined with the `combineFunction`. In presto on the other hand, the `inputFunction` is recursively called with the new state and input value as operators, in order to obtain the final state. The presto implementation does not appear to be inline with the `reduce_agg` aggregate documentation, please correct me if I am missing something here.

When the session property `parse-decimal-literals-as-double` is set to `true` in the java query runner as well, presto returns `0.1` instead of `NULL` due to the aforementioned behavior difference. When `parse-decimal-literals-as-double` is set to `false`, the input values are of Decimal type and the decimal arithmetic operations in `presto-main/src/main/java/com/facebook/presto/type/DecimalOperators.java` are used. 
For this specific query, the decimal divide operation throws an exception for divide by zero with the input value `0` (`try` in the `inputFunction` returns `NULL` as a result) and the state remains `NULL`. The same operation repeats for the input value `10.`, and `NULL` is returned.

**Comment by yzhang1991** [comment] 2023-10-24 17:25
Closing this as a duplicate of https://github.com/prestodb/presto/issues/21177

**Closed by yzhang1991** 2023-10-24 17:25 UTC
Labels: bug, tests, prestissimo
