### ISSUE TITLE
Flaky PrestoExchangeSourceTest/PrestoExchangeSourceTest.failedProducer/0

### ISSUE THREAD

**Issue by elharo** [prestodb/presto#22368] opened 2024-03-29 19:59 UTC
[flakelogvelox.txt](https://github.com/prestodb/presto/files/14808116/flakelogvelox.txt)

**Comment by tdcmeehan** [comment] 2024-04-01 13:52
Duplicate of #22381

**Closed by tdcmeehan** 2024-04-01 13:52 UTC
Labels: flaky-test
