### ISSUE TITLE
Flaky Test: TestBrutalShutdown.testQueryRetryOnShutdown

### ISSUE THREAD

**Issue by hantangwangd** [prestodb/presto#22344] opened 2024-03-27 10:47 UTC
Test failed in an unrelated PR, see [link](https://github.com/prestodb/presto/actions/runs/8449611780/job/23144064518?pr=22080): `TestBrutalShutdown.testQueryRetryOnShutdown`

<details><summary>Test Stacktrace</summary>
<p>

```
2024-03-27T10:18:39.5213370Z [ERROR] Tests run: 3123, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2,324.024 s <<< FAILURE! - in TestSuite
2024-03-27T10:18:39.5219052Z [ERROR] com.facebook.presto.tests.TestBrutalShutdown.testQueryRetryOnShutdown  Time elapsed: 12.728 s  <<< FAILURE!
2024-03-27T10:18:39.5221358Z java.lang.AssertionError: expected [5] but found [4]
2024-03-27T10:18:39.5224167Z 	at org.testng.Assert.fail(Assert.java:110)
2024-03-27T10:18:39.5225223Z 	at org.testng.Assert.failNotEquals(Assert.java:1413)
2024-03-27T10:18:39.5226500Z 	at org.testng.Assert.assertEqualsImpl(Assert.java:149)
2024-03-27T10:18:39.5227735Z 	at org.testng.Assert.assertEquals(Assert.java:131)
2024-03-27T10:18:39.5229267Z 	at org.testng.Assert.assertEquals(Assert.java:1240)
2024-03-27T10:18:39.5230358Z 	at org.testng.Assert.assertEquals(Assert.java:1274)
2024-03-27T10:18:39.5231965Z 	at com.facebook.presto.tests.TestBrutalShutdown.testQueryRetryOnShutdown(TestBrutalShutdown.java:83)
2024-03-27T10:18:39.5236688Z 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2024-03-27T10:18:39.5238013Z 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2024-03-27T10:18:39.5239755Z 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2024-03-27T10:18:39.5241375Z 	at java.lang.reflect.Method.invoke(Method.java:498)
2024-03-27T10:18:39.5242734Z 	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
2024-03-27T10:18:39.5244412Z 	at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:44)
2024-03-27T10:18:39.5246058Z 	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:72)
2024-03-27T10:18:39.5247709Z 	at org.testng.internal.invokers.InvokeMethodRunnable.run(InvokeMethodRunnable.java:32)
2024-03-27T10:18:39.5250038Z 	at org.testng.internal.invokers.MethodInvocationHelper.invokeWithTimeoutWithNoExecutor(MethodInvocationHelper.java:331)
2024-03-27T10:18:39.5260231Z 	at org.testng.internal.invokers.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:294)
2024-03-27T10:18:39.5261895Z 	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:679)
2024-03-27T10:18:39.5263300Z 	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
2024-03-27T10:18:39.5264718Z 	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
2024-03-27T10:18:39.5266177Z 	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
2024-03-27T10:18:39.5267658Z 	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
2024-03-27T10:18:39.5269202Z 	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
2024-03-27T10:18:39.5270717Z 	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
2024-03-27T10:18:39.5272100Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2024-03-27T10:18:39.5273542Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2024-03-27T10:18:39.5274530Z 	at java.lang.Thread.run(Thread.java:750)
```

**Comment by rschlussel** [comment] 2024-03-29 18:03
duplicate of https://github.com/prestodb/presto/issues/22125. Closing this one, but @tdcmeehan, maybe check in with @imjalpreet since he's claimed the other task, but I see you've also started working on it.

**Closed by rschlussel** 2024-03-29 18:03 UTC
Labels: flaky-test
