### ISSUE TITLE
`select histogram(T)` causes json exception in presto-client

### ISSUE THREAD

**Issue by highker** [prestodb/presto#8826] opened 2017-08-23 21:58 UTC
To reproduce:
```
presto:locations> select histogram(array[1]);
Query is gone (server restarted?)
```

stacktrace with `--debug`:
```
java.lang.RuntimeException: Error fetching next at http://localhost:8080/v1/statement/20170823_213958_00044_xee46/4 returned an invalid response: JsonResponse{statusCode=200, statusMessage=OK, headers={content-type=[application/json], date=[Wed, 23 Aug 2017 21:39:58 GMT], vary=[Accept-Encoding, User-Agent], x-content-type-options=[nosniff]}, hasValue=false} [Error: {"id":"20170823_213958_00044_xee46","infoUri":"http://localhost:8080/query.html?20170823_213958_00044_xee46","partialCancelUri":"http://127.0.0.1:8080/v1/stage/20170823_213958_00044_xee46.0","nextUri":"http://localhost:8080/v1/statement/20170823_213958_00044_xee46/5","columns":[{"name":"_col0","type":"map(array(integer),bigint)","typeSignature":{"rawType":"map","typeArguments":[{"rawType":"array","typeArguments":[{"rawType":"integer","typeArguments":[],"literalArguments":[],"arguments":[]}],"literalArguments":[],"arguments":[{"kind":"TYPE_SIGNATURE","value":{"rawType":"integer","typeArguments":[],"literalArguments":[],"arguments":[]}}]},{"rawType":"bigint","typeArguments":[],"literalArguments":[],"arguments":[]}],"literalArguments":[],"arguments":[{"kind":"TYPE_SIGNATURE","value":{"rawType":"array","typeArguments":[{"rawType":"integer","typeArguments":[],"literalArguments":[],"arguments":[]}],"literalArguments":[],"arguments":[{"kind":"TYPE_SIGNATURE","value":{"rawType":"integer","typeArguments":[],"literalArguments":[],"arguments":[]}}]}},{"kind":"TYPE_SIGNATURE","value":{"rawType":"bigint","typeArguments":[],"literalArguments":[],"arguments":[]}}]}}],"data":[[{"[1]":1}]],"stats":{"state":"RUNNING","queued":false,"scheduled":true,"nodes":1,"totalSplits":18,"queuedSplits":14,"runningSplits":1,"completedSplits":3,"userTimeMillis":1,"cpuTimeMillis":1,"wallTimeMillis":2,"processedRows":0,"processedBytes":0,"rootStage":{"stageId":"0","state":"RUNNING","done":false,"nodes":1,"totalSplits":18,"queuedSplits":14,"runningSplits":1,"completedSplits":3,"userTimeMillis":1,"cpuTimeMillis":1,"wallTimeMillis":2,"processedRows":1,"processedBytes":0,"subStages":[]},"progressPercentage":16.666666666666668}}
]
	at com.facebook.presto.client.StatementClient.requestFailedException(StatementClient.java:363)
	at com.facebook.presto.client.StatementClient.advance(StatementClient.java:306)
	at com.facebook.presto.cli.StatusPrinter.printInitialStatusUpdates(StatusPrinter.java:122)
	at com.facebook.presto.cli.Query.renderQueryOutput(Query.java:125)
	at com.facebook.presto.cli.Query.renderOutput(Query.java:107)
	at com.facebook.presto.cli.Console.process(Console.java:337)
	at com.facebook.presto.cli.Console.runConsole(Console.java:262)
	at com.facebook.presto.cli.Console.run(Console.java:148)
	at com.facebook.presto.cli.Presto.main(Presto.java:32)
Caused by: java.lang.IllegalArgumentException: Unable to create class com.facebook.presto.client.QueryResults from JSON response:
[{"id":"20170823_213958_00044_xee46","infoUri":"http://localhost:8080/query.html?20170823_213958_00044_xee46","partialCancelUri":"http://127.0.0.1:8080/v1/stage/20170823_213958_00044_xee46.0","nextUri":"http://localhost:8080/v1/statement/20170823_213958_00044_xee46/5","columns":[{"name":"_col0","type":"map(array(integer),bigint)","typeSignature":{"rawType":"map","typeArguments":[{"rawType":"array","typeArguments":[{"rawType":"integer","typeArguments":[],"literalArguments":[],"arguments":[]}],"literalArguments":[],"arguments":[{"kind":"TYPE_SIGNATURE","value":{"rawType":"integer","typeArguments":[],"literalArguments":[],"arguments":[]}}]},{"rawType":"bigint","typeArguments":[],"literalArguments":[],"arguments":[]}],"literalArguments":[],"arguments":[{"kind":"TYPE_SIGNATURE","value":{"rawType":"array","typeArguments":[{"rawType":"integer","typeArguments":[],"literalArguments":[],"arguments":[]}],"literalArguments":[],"arguments":[{"kind":"TYPE_SIGNATURE","value":{"rawType":"integer","typeArguments":[],"literalArguments":[],"arguments":[]}}]}},{"kind":"TYPE_SIGNATURE","value":{"rawType":"bigint","typeArguments":[],"literalArguments":[],"arguments":[]}}]}}],"data":[[{"[1]":1}]],"stats":{"state":"RUNNING","queued":false,"scheduled":true,"nodes":1,"totalSplits":18,"queuedSplits":14,"runningSplits":1,"completedSplits":3,"userTimeMillis":1,"cpuTimeMillis":1,"wallTimeMillis":2,"processedRows":0,"processedBytes":0,"rootStage":{"stageId":"0","state":"RUNNING","done":false,"nodes":1,"totalSplits":18,"queuedSplits":14,"runningSplits":1,"completedSplits":3,"userTimeMillis":1,"cpuTimeMillis":1,"wallTimeMillis":2,"processedRows":1,"processedBytes":0,"subStages":[]},"progressPercentage":16.666666666666668}}
]
	at com.facebook.presto.client.JsonResponse.<init>(JsonResponse.java:69)
	at com.facebook.presto.client.JsonResponse.execute(JsonResponse.java:143)
	at com.facebook.presto.client.StatementClient.advance(StatementClient.java:293)
	... 7 more
Caused by: java.lang.IllegalArgumentException: Invalid JSON string for [simple type, class com.facebook.presto.client.QueryResults]
	at io.airlift.json.JsonCodec.fromJson(JsonCodec.java:137)
	at com.facebook.presto.client.JsonResponse.<init>(JsonResponse.java:66)
	... 9 more
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of com.facebook.presto.client.QueryResults, problem: Cannot cast java.lang.String to java.util.List
 at [Source: {"id":"20170823_213958_00044_xee46","infoUri":"http://localhost:8080/query.html?20170823_213958_00044_xee46","partialCancelUri":"http://127.0.0.1:8080/v1/stage/20170823_213958_00044_xee46.0","nextUri":"http://localhost:8080/v1/statement/20170823_213958_00044_xee46/5","columns":[{"name":"_col0","type":"map(array(integer),bigint)","typeSignature":{"rawType":"map","typeArguments":[{"rawType":"array","typeArguments":[{"rawType":"integer","typeArguments":[],"literalArguments":[],"arguments":[]}],"literalArguments":[],"arguments":[{"kind":"TYPE_SIGNATURE","value":{"rawType":"integer","typeArguments":[],"literalArguments":[],"arguments":[]}}]},{"rawType":"bigint","typeArguments":[],"literalArguments":[],"arguments":[]}],"literalArguments":[],"arguments":[{"kind":"TYPE_SIGNATURE","value":{"rawType":"array","typeArguments":[{"rawType":"integer","typeArguments":[],"literalArguments":[],"arguments":[]}],"literalArguments":[],"arguments":[{"kind":"TYPE_SIGNATURE","value":{"rawType":"integer","typeArguments":[],"literalArguments":[],"arguments":[]}}]}},{"kind":"TYPE_SIGNATURE","value":{"rawType":"bigint","typeArguments":[],"literalArguments":[],"arguments":[]}}]}}],"data":[[{"[1]":1}]],"stats":{"state":"RUNNING","queued":false,"scheduled":true,"nodes":1,"totalSplits":18,"queuedSplits":14,"runningSplits":1,"completedSplits":3,"userTimeMillis":1,"cpuTimeMillis":1,"wallTimeMillis":2,"processedRows":0,"processedBytes":0,"rootStage":{"stageId":"0","state":"RUNNING","done":false,"nodes":1,"totalSplits":18,"queuedSplits":14,"runningSplits":1,"completedSplits":3,"userTimeMillis":1,"cpuTimeMillis":1,"wallTimeMillis":2,"processedRows":1,"processedBytes":0,"subStages":[]},"progressPercentage":16.666666666666668}}
; line: 1, column: 1718]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:268)
	at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:1405)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.wrapAsJsonMappingException(StdValueInstantiator.java:468)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.rewrapCtorProblem(StdValueInstantiator.java:487)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:276)
	at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromObjectWith(ValueInstantiator.java:224)
	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:135)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:471)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1194)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:148)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3789)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2871)
	at io.airlift.json.JsonCodec.fromJson(JsonCodec.java:134)
	... 10 more
Caused by: java.lang.ClassCastException: Cannot cast java.lang.String to java.util.List
	at java.lang.Class.cast(Class.java:3369)
	at com.facebook.presto.client.QueryResults.fixValue(QueryResults.java:242)
	at com.facebook.presto.client.QueryResults.fixValue(QueryResults.java:252)
	at com.facebook.presto.client.QueryResults.fixData(QueryResults.java:224)
	at com.facebook.presto.client.QueryResults.<init>(QueryResults.java:95)
	at sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:124)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:274)
	... 19 more
```

**Comment by martint** [comment] 2017-08-23 22:52
That's because maps with complex keys cannot represented on the wire. This is a duplicate of https://github.com/prestodb/presto/issues/3549, which has been folded into https://github.com/prestodb/presto/issues/3693

**Closed by martint** 2017-08-23 22:52 UTC
Labels: bug
