### ISSUE TITLE
Automatic encoding detection in Jackson leads to unexpected behavior

### ISSUE THREAD

**Issue by haozhun** [prestodb/presto#8975] opened 2017-09-14 21:25 UTC
The following test should pass.

```
assertFunction("json_extract_scalar(utf8(X'00 00 00 00 7b 22 72 22'), '$.x')", VARCHAR, null);
```

```
ExternalDependencyTransientError: Presto transient error, will auto retry, info: java.lang.RuntimeException: java.io.CharConversionException: Invalid UTF-32 character 0x7b227222(above 10ffff)
at char #8, byte #35)
	at com.google.common.base.Throwables.propagate(Throwables.java:240)
	at com.facebook.presto.operator.scalar.JsonExtract.extract(JsonExtract.java:143)
	at com.facebook.presto.operator.scalar.JsonFunctions.varcharJsonExtractScalar(JsonFunctions.java:398)
	at com.facebook.presto.$gen.PageFilter_20170914_185020_17501_8bak5_2_278_537816.filter(Unknown Source)
	at com.facebook.presto.$gen.PageFilter_20170914_185020_17501_8bak5_2_278_537816.filter(Unknown Source)
	at com.facebook.presto.operator.project.PageProcessor.process(PageProcessor.java:85)
	at com.facebook.presto.operator.ScanFilterAndProjectOperator.processPageSource(ScanFilterAndProjectOperator.java:281)
	at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:229)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:337)
	at com.facebook.presto.operator.Driver.lambda$processFor$6(Driver.java:241)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:614)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:235)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:622)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at com.facebook.presto.execution.executor.LegacyPrioritizedSplitRunner.process(LegacyPrioritizedSplitRunner.java:23)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:485)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.CharConversionException: Invalid UTF-32 character 0x7b227222(above 10ffff)
at char #8, byte #35)
	at com.fasterxml.jackson.core.io.UTF32Reader.reportInvalid(UTF32Reader.java:189)
	at com.fasterxml.jackson.core.io.UTF32Reader.read(UTF32Reader.java:150)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._loadMore(ReaderBasedJsonParser.java:241)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipWSOrEnd(ReaderBasedJsonParser.java:2346)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:644)
	at com.facebook.presto.operator.scalar.JsonExtract.extract(JsonExtract.java:131)
	... 17 more
```

Root cause is that `ByteSourceJsonBootstrapper.constructParser` calls `detectEncoding` under the hood, which is not expected.

The fix is to pass a Reader to Jackson instead of input stream to circumvent automatic character encoding detection. This will not incur additional performance penalty because that's what Jackson does under the hood anyways given we disabled CANONICALIZE_FIELD_NAMES in Jackson.

**Comment by martint** [comment] 2017-11-16 19:58
Duplicate of #8958

**Closed by martint** 2017-11-16 19:58 UTC
