### ISSUE TITLE
mysql connector - table does not exist error but table is in 'show tables'

### ISSUE THREAD

**Issue by tooptoop4** [prestodb/presto#12957] opened 2019-06-17 14:32 UTC
echo "
connector.name=mysql
connection-url=jdbc:mysql://xxx:3306?useSSL=false&requireSSL=false&verifyServerCertificate=false
connection-user=yyyy
connection-password=aaaa
" > /home/ec2-user/presto-server-${presto_release_version}/etc/catalog/hms.properties

presto> show schemas from hms;
       Schema
--------------------
 information_schema
 innodb
 metastore
 performance_schema
 ranger
 sys
 tmp
(7 rows)

Query 20190617_142342_00083_wehgw, FINISHED, 1 node
Splits: 19 total, 19 done (100.00%)
0:00 [7 rows, 98B] [41 rows/s, 584B/s]

presto> use hms.metastore;
USE
presto:metastore> show tables;
           Table
---------------------------
 aux_table
 bucketing_cols
 cds
 columns_v2
 compaction_queue
 completed_compactions
 completed_txn_components
 database_params
 db_privs
 dbs
 delegation_tokens
 func_ru
 funcs
 global_privs
 hive_locks
 idxs
 index_params
 key_constraints
 master_keys
 next_compaction_queue_id
 next_lock_id
 next_txn_id
 notification_log
 notification_sequence
 nucleus_tables
 part_col_privs
 part_col_stats
 part_privs
 partition_events
 partition_key_vals
 partition_keys
 partition_params
 partitions
 role_map
 roles
 sd_params
 sds
 sequence_table
 serde_params
 serdes
 skewed_col_names
 skewed_col_value_loc_map
 skewed_string_list
 skewed_string_list_values
 skewed_values
 sort_cols
 tab_col_stats
 table_params
 tbl_col_privs
 tbl_privs
 tbls
 txn_components
 txns
 type_fields
 types
 version
 write_set
(57 rows)

Query 20190617_142353_00085_wehgw, FINISHED, 1 node
Splits: 19 total, 19 done (100.00%)
0:01 [57 rows, 1.73KB] [84 rows/s, 2.56KB/s]

presto:metastore> select * from tbls;
Query 20190617_142358_00086_wehgw failed: line 1:15: Table hms.metastore.tbls does not exist
select * from tbls

presto:metastore> select * from columns_v2 limit 3;
 cd_id | comment |     column_name      | type_name | integer_idx
-------+---------+----------------------+-----------+-------------
     1 | NULL    | aggressorcompanyname | string    |          30
     1 | NULL    | aggressortradername  | string    |          29
     1 | NULL    | allornone            | string    |          24
(3 rows)

Query 20190617_142431_00088_wehgw, FINISHED, 1 node
Splits: 18 total, 18 done (100.00%)
0:00 [1.57K rows, 0B] [12K rows/s, 0B/s]

presto:metastore>

com.facebook.presto.sql.analyzer.SemanticException: line 1:15: Table hms.metastore.tbls does not exist
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:924)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:257)
	at com.facebook.presto.sql.tree.Table.accept(Table.java:53)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:271)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:1852)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:1031)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:257)
	at com.facebook.presto.sql.tree.QuerySpecification.accept(QuerySpecification.java:127)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:271)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:281)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:746)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:257)
	at com.facebook.presto.sql.tree.Query.accept(Query.java:94)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:271)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:249)
	at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:79)
	at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:71)
	at com.facebook.presto.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:209)
	at com.facebook.presto.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:97)
	at com.facebook.presto.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:744)
	at com.facebook.presto.execution.SqlQueryManager.createQueryInternal(SqlQueryManager.java:366)
	at com.facebook.presto.execution.SqlQueryManager.lambda$createQuery$4(SqlQueryManager.java:305)
	at com.facebook.presto.$gen.Presto_0_220____20190617_135337_1.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Mysql cli shows below structure. Env is hive 2.3.4 (metastore schema is from hive install), mysql 5.7.25

mysql> desc COLUMNS_V2;
+-------------+--------------+------+-----+---------+-------+
| Field       | Type         | Null | Key | Default | Extra |
+-------------+--------------+------+-----+---------+-------+
| CD_ID       | bigint(20)   | NO   | PRI | NULL    |       |
| COMMENT     | varchar(256) | YES  |     | NULL    |       |
| COLUMN_NAME | varchar(767) | NO   | PRI | NULL    |       |
| TYPE_NAME   | mediumtext   | YES  |     | NULL    |       |
| INTEGER_IDX | int(11)      | NO   |     | NULL    |       |
+-------------+--------------+------+-----+---------+-------+
5 rows in set (0.00 sec)

mysql> desc TBLS;
+--------------------+--------------+------+-----+---------+-------+
| Field              | Type         | Null | Key | Default | Extra |
+--------------------+--------------+------+-----+---------+-------+
| TBL_ID             | bigint(20)   | NO   | PRI | NULL    |       |
| CREATE_TIME        | int(11)      | NO   |     | NULL    |       |
| DB_ID              | bigint(20)   | YES  | MUL | NULL    |       |
| LAST_ACCESS_TIME   | int(11)      | NO   |     | NULL    |       |
| OWNER              | varchar(767) | YES  |     | NULL    |       |
| RETENTION          | int(11)      | NO   |     | NULL    |       |
| SD_ID              | bigint(20)   | YES  | MUL | NULL    |       |
| TBL_NAME           | varchar(256) | YES  | MUL | NULL    |       |
| TBL_TYPE           | varchar(128) | YES  |     | NULL    |       |
| VIEW_EXPANDED_TEXT | mediumtext   | YES  |     | NULL    |       |
| VIEW_ORIGINAL_TEXT | mediumtext   | YES  |     | NULL    |       |
| IS_REWRITE_ENABLED | bit(1)       | NO   |     | NULL    |       |
+--------------------+--------------+------+-----+---------+-------+
12 rows in set (0.00 sec)

**Comment by ebyhr** [comment] 2019-06-20 04:50
Perhaps, it's duplicate of https://github.com/prestodb/presto/issues/2863

**Closed** 2020-05-23 23:43 UTC
