### ISSUE TITLE
Add Create Catalog Sql syntax implementations.

### ISSUE THREAD

**Issue by Akanksha-kedia** [prestodb/presto#21207] opened 2023-10-22 10:59 UTC
Expected Behavior or Use Case: Users should be able to create  catalogs using SQL commands, similar to how databases and schemas are managed in traditional SQL databases.

Presto Component, Service, or Connector: This would primarily affect the PrestoDBserver and all connectors, as they would need to be able to dynamically load and unload at runtime.

Possible Implementation:

- Extend the parser to recognize CREATE CATALOG and DROP CATALOG SQL commands.
- Add new methods to the Metadata interface and its implementations to handle the creation and deletion of catalogs.
- Modify the CatalogManager to allow for the dynamic addition and removal of catalogs.
- Each connector might need to be updated to handle being loaded and unloaded at runtime.

Context:This feature could be useful in multi-tenant environments where different users or groups need to work with different data sources. It would allow for more dynamic management of catalogs without needing to restart the server.

**Comment by Akanksha-kedia** [comment] 2023-10-22 11:08
UseCases :
In a multi-tenant environment, different users or groups may have different data sources they need to work with. For example, one group might use a MySQL database, while another uses a PostgreSQL database. Each of these would be represented as a separate catalog in PrestoDB.

Currently, to add a new catalog in PrestoDB, you have to create a new properties file in the etc/catalog directory and then restart the server. This could be disruptive in a multi-tenant environment, as it would interrupt all users' work whenever a new catalog needs to be added.

If PrestoDB supported CREATE CATALOG and DROP CATALOG SQL commands, it would allow for more dynamic management of catalogs. A new catalog could be added or an existing one removed without needing to restart the server. This would be less disruptive and could allow for more flexibility in managing data sources.

For example, if a new team starts and they have their own data source, a new catalog could be created for them without affecting any other users. Similarly, if a team no longer needs their data source, their catalog could be removed without disrupting others.

This could also potentially improve security. In the current system, anyone who can create a properties file in the etc/catalog directory can add a new catalog. If catalogs could be managed via SQL commands, you could potentially restrict who can create and drop catalogs using PrestoDB's built-in access control features.

However, this feature would also have potential downsides. For example, it could lead to a large number of catalogs being created, which could make the system harder to manage. It could also potentially allow users to create catalogs that connect to insecure or unstable data sources, which could affect the stability of the PrestoDB server. Therefore, if this feature were to be added, it would need to be designed and implemented carefully.

**Comment by tdcmeehan** [comment] 2023-10-23 19:36
Duplicate of #12605 and #14964--please feel free to open a new issue concretely describing how to achieve this feature.

**Closed by tdcmeehan** 2023-10-23 19:36 UTC
Labels: feature request
