### ISSUE TITLE
Missing repartitioning step breaks window function results. 

### ISSUE THREAD

**Issue by xerial** [prestodb/presto#5659] opened 2016-07-13 23:54 UTC
We found a weird window function behavior when a query involves multiple window functions and self join. Here is how to reproduce this problem (in Presto 0.146):

```
-- OK query 
presto:> explain WITH X AS( SELECT id, rank() over(partition BY id) AS ranking FROM kw_sequences ), Y AS ( SELECT b.id, a.ranking FROM X a JOIN X b ON a.id = b.id ) SELECT id, rank() over(partition BY id ORDER BY ranking) FROM Y;
                                                                   Query Plan
------------------------------------------------------------------------------------------------------------------------------------------------
 - Output[id, _col1] => [id_11:varchar, rank_40:bigint]
         id := id_11
         _col1 := rank_40
     - Exchange[GATHER] => id_11:varchar, rank_40:bigint
         - Project => [id_11:varchar, rank_40:bigint]
             - Window[partition by (id_11), order by (rank)] => [id_11:varchar, rank:bigint, $hashvalue:bigint, rank_40:bigint]
                     rank_40 := rank()
                 - Exchange[REPARTITION] => id_11:varchar, rank:bigint, $hashvalue:bigint
                     - Project => [rank:bigint, id_11:varchar, $hashvalue_50:bigint]
                         - InnerJoin[("id" = "id_11")] => [id:varchar, $hashvalue_48:bigint, rank:bigint, id_11:varchar, $hashvalue_50:bigint]
                             - Window[partition by (id)] => [id:varchar, $hashvalue_48:bigint, rank:bigint]
                                     rank := rank()
                                 - Exchange[REPARTITION] => id:varchar, $hashvalue_48:bigint
                                     - Project => [id:varchar, $hashvalue_49:bigint]
                                             $hashvalue_49 := "combine_hash"(BIGINT '0', COALESCE("$operator$hash_code"("id"), 0))
                                         - TableScan[td-presto:td:customer_monotaro.kw_sequences, originalConstraint = true] => [id:varchar]
                                                 LAYOUT: com.treasure_data.presto.connector.TDTableLayoutHandle@ebbc2de6
                                                 id := td:id
                             - Window[partition by (id_11)] => [id_11:varchar, $hashvalue_50:bigint]
                                 - Exchange[REPARTITION] => id_11:varchar, $hashvalue_50:bigint
                                     - Project => [id_11:varchar, $hashvalue_51:bigint]
                                             $hashvalue_51 := "combine_hash"(BIGINT '0', COALESCE("$operator$hash_code"("id_11"), 0))
                                         - TableScan[td-presto:td:customer_monotaro.kw_sequences, originalConstraint = true] => [id_11:varchar]
                                                 LAYOUT: com.treasure_data.presto.connector.TDTableLayoutHandle@ebbc2de6
                                                 id_11 := td:id

-- BAD Query (missing repartitioning)
presto> explain WITH X AS( SELECT id, rank() over(partition BY id) AS ranking FROM kw_sequences ), Y AS ( SELECT a.id, a.ranking FROM X a JOIN X b ON a.id = b.id ) SELECT id, rank() over(partition BY id ORDER BY ranking) FROM Y;
                                                                 Query Plan
--------------------------------------------------------------------------------------------------------------------------------------------
 - Output[id, _col1] => [id:varchar, rank_40:bigint]
         _col1 := rank_40
     - Exchange[GATHER] => id:varchar, rank_40:bigint
         - Project => [id:varchar, rank_40:bigint]
             - Window[partition by (<id>), order by (rank)] => [rank:bigint, id:varchar, $hashvalue:bigint, rank_40:bigint]
                     rank_40 := rank()
         ======  <<  missing REPARTITIONING step >> =======
                 - Project => [rank:bigint, id:varchar, $hashvalue:bigint]
                     - InnerJoin[("id" = "id_11")] => [id:varchar, $hashvalue:bigint, rank:bigint, id_11:varchar, $hashvalue_49:bigint]
                         - Window[partition by (id)] => [id:varchar, $hashvalue:bigint, rank:bigint]
                                 rank := rank()
                             - Exchange[REPARTITION] => id:varchar, $hashvalue:bigint
                                 - Project => [id:varchar, $hashvalue_48:bigint]
                                         $hashvalue_48 := "combine_hash"(BIGINT '0', COALESCE("$operator$hash_code"("id"), 0))
                                     - TableScan[td-presto:td:customer_monotaro.kw_sequences, originalConstraint = true] => [id:varchar]
                                             LAYOUT: com.treasure_data.presto.connector.TDTableLayoutHandle@eddc8608
                                             id := td:id
                         - Window[partition by (id_11)] => [id_11:varchar, $hashvalue_49:bigint]
                             - Exchange[REPARTITION] => id_11:varchar, $hashvalue_49:bigint
                                 - Project => [id_11:varchar, $hashvalue_50:bigint]
                                         $hashvalue_50 := "combine_hash"(BIGINT '0', COALESCE("$operator$hash_code"("id_11"), 0))
                                     - TableScan[td-presto:td:customer_monotaro.kw_sequences, originalConstraint = true] => [id_11:varchar]
                                             LAYOUT: com.treasure_data.presto.connector.TDTableLayoutHandle@eddc8608
                                             id_11 := td:id
```

The only difference between two queries is using `a.id` or `b.id` to extract the self join result, but these ids values should be the same because of `a.id = b.id` join condition.

**Comment by martint** [comment] 2016-07-14 00:01
@erichwang, can you take a look at this?

**Comment by martint** [comment] 2016-07-14 00:31
The missing repartition is actually not an issue from a semantic point of view. It happens because the AddExchanges optimizer doesn't understand a.id = b.id due to the join, so it blindly adds a repartition in one case. 

The only other difference between the plans is that one executes the window operator in streaming mode.

Both queries should return the same result. Are you not seeing that?

**Comment by xerial** [comment] 2016-07-14 00:43
@martint The above query is a simplified one. The actual query uses large string values for `id`, and produces wrong rank() results randomly. I guess hash collision handling, which should be resolved by checking the actual id values (happens in repartitioning step?), is not performed in the latter query.

**Comment by erichwang** [comment] 2016-07-14 01:18
@xerial, do you think you could provide us with a query over some of the TPCH data which might be able to produce this problem?

**Comment by xerial** [comment] 2016-07-14 01:26
@erichwang Producing these different query plans using tpch dataset will not be so difficult. Producing weird query results may take some time because it apparently happens only when there is some hash value collision. Anyway I'll work on that.

**Comment by erichwang** [comment] 2016-07-14 01:28
@xerial, just curious, how do you know hash collisions are responsible here?

**Comment by xerial** [comment] 2016-07-14 17:20
@erichwang These two query plans produce the same query result if we use small partition keys. One of our customers used relatively large string values as the partition key and we found this issue.

**Comment by xerial** [comment] 2016-07-14 22:59
I checked the optimization processes using the following query:
```
WITH X AS (SELECT linenumber id FROM lineitem), " +
                "Y AS ( SELECT a.id FROM X a JOIN X b ON a.id = b.id) " +
                "SELECT id, rank() over(partition BY id) FROM Y";
```

And it seems AddExchange failed to add an exchange(remote, repartition) step:
```
Applied PushTableWriteThroughUnion
- Output[id, _col1] => [linenumber:integer, rank:bigint]
        id := linenumber
        _col1 := rank
    - Window[partition by (linenumber)] => [linenumber:integer, rank:bigint]
            rank := rank()
        - Project => [linenumber:integer]
            - InnerJoin[("linenumber" = "linenumber_7")] => [linenumber:integer, linenumber_7:integer]
                - TableScan[local:tpch:lineitem:sf0.01, originalConstraint = null] => [linenumber:integer]
                        linenumber := tpch:linenumber
                - TableScan[local:tpch:lineitem:sf0.01, originalConstraint = null] => [linenumber_7:integer]
                        linenumber_7 := tpch:linenumber

Applied AddExchanges
- Output[id, _col1] => [linenumber:integer, rank:bigint]
        id := linenumber
        _col1 := rank
    - RemoteExchange[GATHER] => linenumber:integer, rank:bigint
        - Window[partition by (linenumber)] => [linenumber:integer, rank:bigint]
                rank := rank()
       <<======  missing reparition: RemoteExchange[REPARTITION] => linenumber:integer  should be here ========>>
            - Project => [linenumber:integer]
                - InnerJoin[("linenumber" = "linenumber_7")] => [linenumber:integer, linenumber_7:integer]
                    - RemoteExchange[REPARTITION] => linenumber:integer
                        - TableScan[local:tpch:lineitem:sf0.01, originalConstraint = true] => [linenumber:integer]
                                linenumber := tpch:linenumber
                    - RemoteExchange[REPARTITION] => linenumber_7:integer
                        - TableScan[local:tpch:lineitem:sf0.01, originalConstraint = true] => [linenumber_7:integer]
                                linenumber_7 := tpch:linenumber
```

If we rewrite the query `a.id` -> `b.id`, `RemoteExchange[REPARTITION]` step will be added.

**Comment by xerial** [comment] 2016-07-15 00:15
When setting `set session task_join_concurrency=1`, the query produces the correct results.

**Comment by haozhun** [comment] 2016-07-15 01:28
We are able to reproduce this with the below query in 0.146. The query should produce no rows. In 0.146, this query produces many rows.
```
SET SESSION task_join_concurrency=4;
USE TPCH.SF1;
WITH
  X AS (
    SELECT custkey, rank() over (partition by custkey order by orderkey asc) as rank1
    FROM orders
  ),
  Y AS (
    SELECT a.custkey, a.rank1
    FROM
      X a
    JOIN
      X b
    ON
      a.custkey=b.custkey and a.rank1=b.rank1
  ),
  Z AS (
    SELECT custkey, rank() over (partition by custkey order by rank1) as rank2
    FROM Y
  )
SELECT custkey, rank2, count(*) as cnt FROM Z
GROUP BY custkey, rank2
HAVING count(*) > 1
```
We believe it has been fixed in trunk. The same query produces no rows in trunk. Note: Since 0.147,  use `SET SESSION task_concurrency=4` instead of `SET SESSION task_join_concurrency=4`.

Local-parallel implementation was rewritten in 0.147. Prior to 0.147, the implementation naively distributes rows into multiple threads. This breaks any stream clustering/ordering guarantee. Since 0.147, inserting local parallel is part of planning process. It understands the streaming requirements and guarantees. Specifically for the above query, it will do spread the work on each worker into multiple threads based on the hash of `custkey`, which preserves the streaming property.

This bug does not manifest if `task_join_concurrency` is set to 1. The default is 1.

**Closed by haozhun** 2016-07-15 01:28 UTC
Labels: bug, RELEASE-BLOCKER
