### ISSUE TITLE
TestNoisySumGaussianShortDecimalAggregation.testNoisySumGaussianShortDecimalClippingSomeNoiseScaleWithinSomeStd flakes

### ISSUE THREAD

**Issue by elharo** [prestodb/presto#22440] opened 2024-04-08 10:54 UTC
Saw this one flake a couple of times this weekend.

```
2024-04-07T14:41:50.9146481Z [ERROR] com.facebook.presto.operator.aggregation.noisyaggregation.TestNoisySumGaussianShortDecimalAggregation.testNoisySumGaussianShortDecimalClippingSomeNoiseScaleWithinSomeStd  Time elapsed: 0.001 s  <<< FAILURE!
2024-04-07T14:41:50.9149656Z java.lang.AssertionError: Test: Inconsistent results with channel offset, Expected: 42.23822967798865, actual: 48.497140986572795
2024-04-07T14:41:50.9150876Z 	at org.testng.Assert.fail(Assert.java:110)
2024-04-07T14:41:50.9152189Z 	at com.facebook.presto.operator.aggregation.AggregationTestUtils.assertFunctionEquals(AggregationTestUtils.java:138)
2024-04-07T14:41:50.9154177Z 	at com.facebook.presto.operator.aggregation.AggregationTestUtils.partialAggregation(AggregationTestUtils.java:308)
2024-04-07T14:41:50.9156238Z 	at com.facebook.presto.operator.aggregation.AggregationTestUtils.assertAggregationInternal(AggregationTestUtils.java:122)
2024-04-07T14:41:50.9158259Z 	at com.facebook.presto.operator.aggregation.AggregationTestUtils.assertAggregation(AggregationTestUtils.java:85)
2024-04-07T14:41:50.9161876Z 	at com.facebook.presto.operator.aggregation.noisyaggregation.TestNoisySumGaussianShortDecimalAggregation.testNoisySumGaussianShortDecimalClippingSomeNoiseScaleWithinSomeStd(TestNoisySumGaussianShortDecimalAggregation.java:300)
2024-04-07T14:41:50.9164746Z 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2024-04-07T14:41:50.9165858Z 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2024-04-07T14:41:50.9167191Z 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2024-04-07T14:41:50.9168267Z 	at java.lang.reflect.Method.invoke(Method.java:498)
2024-04-07T14:41:50.9170251Z 	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
2024-04-07T14:41:50.9171746Z 	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
2024-04-07T14:41:50.9173014Z 	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
2024-04-07T14:41:50.9174317Z 	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
2024-04-07T14:41:50.9175672Z 	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
2024-04-07T14:41:50.9177052Z 	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
2024-04-07T14:41:50.9178459Z 	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
2024-04-07T14:41:50.9179826Z 	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
2024-04-07T14:41:50.9181090Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2024-04-07T14:41:50.9182361Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2024-04-07T14:41:50.9183304Z 	at java.lang.Thread.run(Thread.java:750)
2024-04-07T14:41:50.9183871Z 
2024-04-07T14:41:51.0656676Z [INFO] 
2024-04-07T14:41:51.0657113Z [INFO] Results:
2024-04-07T14:41:51.0657510Z [INFO] 
2024-04-07T14:41:51.0658102Z [ERROR] Failures: 
2024-04-07T14:41:51.0660266Z [ERROR]   TestNoisySumGaussianShortDecimalAggregation.testNoisySumGaussianShortDecimalClippingSomeNoiseScaleWithinSomeStd:300 Test: Inconsistent results with channel offset, Expected: 42.23822967798865, actual: 48.497140986572795
```

**Comment by tdcmeehan** [comment] 2024-04-09 13:47
Duplicate of #22165

**Closed by tdcmeehan** 2024-04-09 13:47 UTC
Labels: flaky-test
