### ISSUE TITLE
example-http connector: file:///... URI should be valid, however it yields an exception when used for "sources" (in the json metadata file)

### ISSUE THREAD

**Issue by dudu-markovitz** [prestodb/presto#9664] opened 2018-01-03 15:29 UTC
Query 20180103_151937_00005_fyb3c failed: hostPortString is null

P.s.
As a work-around we can use "sources":  ["file://localhost/..."]

**Comment by rschlussel2** [comment] 2018-04-18 18:50
duplicate of #9665

**Closed by rschlussel2** 2018-04-18 18:50 UTC
