### ISSUE TITLE
Release notes for 0.188

### ISSUE THREAD

**Issue by haozhun** [prestodb/presto#9244] opened 2017-10-30 16:46 UTC
## Aleksei Statkevich
- [x]  10-25 17:37:23    fe9611d1cd Build immutable map for prepared statements
- [x]  10-26 11:08:44    256045624b Fix product test for stddev functions
## Dain Sundstrom
- [x]  10-21 19:56:20    46402324e4 Fix SHOW FUNCTIONS documentation for stddev
- [x]  10-28 15:50:58    1ed9579ad3 Update to Airbase 74 and Airlift 0.154
## David Phillips
- [x]  10-26 14:21:58    609882f7a4 Add support for using EMRFS with Hive connector
- [x]  10-26 14:21:58    6ed99fa1f2 Move S3ConfigurationUpdater to S3 package
- [x]  10-27 20:46:14    3b12111f93 Remove duplicate method in RecordFileWriter
- [x]  10-27 20:47:37    7d1e59e9b6 Set thread name when removing tasks
- [x]  10-27 21:15:53    42054818d6 Update to OkHttp 3.9.0
- [x]  10-27 22:57:14    678f1b4b86 Implement cancellation of non-query statements
- [x]  10-28 10:19:00    0dda10b9ee Build Javadoc in Travis CI
- [x]  10-31 22:42:39    0c8cfb6783 Fix transaction support in client and CLI
- [x]  10-31 22:42:39    f85ff2fa3b Run CLI table name completion in separate transaction
## Grzegorz Kokosiński
- [x]  10-20 12:05:57    168703a1e2 Fix formatting
- [x]  10-20 12:05:57    26b81670b4 Improve performance of Analysis.getType(Expression)
- [x]  10-20 12:05:57    7c61d92e15 Fix code style in ExpressionAnalyzer
- [x]  10-20 12:05:57    9355c910d8 Remove unused method
- [x]  10-20 12:05:57    b08d438bb4 Remove redundant null check
- [x]  10-20 12:05:57    cf0d418e3d Fail when no symbol for field is found
- [x]  10-20 12:05:57    d6520854f2 Fix map access with wrong key generic type
## Haozhun Jin
- [x]  10-24 15:11:41    1101b47289 Fix inverted sign for time zones Etc/GMT(+/-)H[H]
- [x]  10-26 13:03:29    b257f31a1d Fix race condition in SpillAwareLookupSourceProvider.close
- [x]  10-31 11:24:13    b98b483461 Update to airlift 0.155
- [x]  10-31 16:16:00    aaf7807a3b Increase test timeout in TestPrestoDriver jdbc test
## James Sun
- [x]  10-19 20:40:33    bb65b61e74 Clean up PositionsPageProcessorIterator::processBatch() return value
- [x]  10-19 20:41:15    c6f1833bc3 Add reference counting to SliceBigArray
- [x]  10-19 20:41:15    ef54384da3 Update ReferenceCountMap method names to be more accurate
- [x]  10-25 16:33:34    669c0414d8 Remove copy of drivers when getting pipeline status
- [x]  10-30 10:39:25    130a525939 Add page size stats to HivePageSink
- [x]  11-01 11:39:30    c16af0e993 Fix bound check in ArraySliceFunction
## Nezih Yigitbasi
- [x]  10-23 16:36:39    6d2dab7120 Fix typo in method name
- [x]  10-26 15:12:46    32c2dd9ed0 Add environment support to db-backed resource manager
- [x]  10-26 16:51:59    45f5fe8bb8 Fix typo in exception message
- [x]  10-31 10:11:57    1127ad086d Create runner in test method and run as single threaded
- [x]  10-31 10:11:57    c2a4c81ca9 Close runner properly in TestTpchDistributedStats
## Raghav Sethi
- [x]  10-20 12:12:01    8bcd7cdb5e Add warning message to 0.186 release notes
- [x]  10-26 15:28:18    13a595a7eb Fix merging for JoinOperatorInfo
- [x]  10-26 17:03:54    bcee065613 Fix unused import and update TestJoinOperator
- [x]  10-26 17:06:31    f46c9a13e0 Add flattened plan to QueryCompletedEvent
## Rongrong Zhong
- [x]  10-24 22:20:18    b580545784 Add current memory to QueryProgressStats
- [x]  11-01 11:36:46    dc872ba0a0 Support client tags in resource group selector

## Wenlei Xie
- [x]  10-21 00:57:15    cd858e0568 Minor fixes for Bing tiles documentation
- [x]  10-23 19:55:01    901a16fd13 Expire specialized function cache entries after one hour
- [x]  10-27 12:12:25    83cfefffd3 Fix geospatial function name in docs
- [x]  10-29 12:49:49    ebc44d1853 Add eager compact option into PagesIndex
- [x]  10-30 17:23:02    4920ba482d Expire projection and filter cache entries after one hour
- [x]  11-01 13:54:07    9eb8617aa7 Upgrade to slice 0.32
- [x]  11-01 13:54:08    2c7f8339fc Minor style and variable name fix for AbstractMapBlock
- [x]  11-01 13:54:09    f91d56d69c Avoid memory allocation when copying a whole compact block
- [x]  11-01 13:54:10    97897c0c4e Fix VariableWidthBlockBuilder.copyRegion to return a compact block
- [x]  11-01 13:54:12    b9bceeba6c Improve SliceArrayBlock.copyRegion perf by skipping compacted slice
- [x]  11-01 13:54:13    14c6ef5bf8 Remove incorrect effectiveness check before compacting block

## Łukasz Osipiuk
- [x]  10-29 15:03:22    043ae8bc10 Make PartitionedLookupSource.close idempotent
- [x]  10-29 15:03:22    1097bc8b09 Make PartitionedLookupSource to close underlying LookupSources
- [x]  10-29 15:03:22    043ae8bc10 Make PartitionedLookupSource.close idempotent
- [x]  10-29 15:03:22    1097bc8b09 Make PartitionedLookupSource to close underlying LookupSources

**Comment by nezihyigitbasi** [comment] 2017-10-30 17:20
General
--------
- Add environment support to db-backed resource groups manager. Previously, configurations of different clusters have to be stored in separate databases. With this change different cluster configurations can be stored in the same table and Presto will use the new `environment` column to differentiate them. The `node.environment` config property will be used to determine the current environment, and Presto will load the configuration for that environment on startup.

**Comment by dain** [comment] 2017-10-30 17:50
# General

* Improve performance of server and HTTP request logging.

**Comment by AlekseiS** [comment] 2017-10-30 17:53
No user-visible changes from me

**Comment by raghavsethi** [comment] 2017-10-30 20:05
# General Changes

Add flattened query plan to QueryInfo

# SPI Changes

Add query plan to the query completed event

**Comment by wenleix** [comment] 2017-10-31 00:43
General 

- Add `pages-index.eager-compaction-enabled` config property. Enabling eager compaction will prevent excessive full GC overhead when join queries with large memory usage exhaust cluster memory. However, this could also increase the CPU used by join queries.

- Prevent excessive full GC overhead and query slowness caused by repeated compilation of MethodHandle. We suspect this is a JVM bug that is related to stale/corrupted profiling data associated with dynamically-created MethodHandles.

**Comment by haozhun** [comment] 2017-10-31 20:13
```
* Fix inverted sign for time zones ``Etc/GMT-12``, ``Etc/GMT-11``, ..., ``Etc/GMT-1``, ``Etc/GMT+1``, ... ``Etc/GMT+12``.

**Comment by electrum** [comment] 2017-11-01 20:15
```
JDBC Driver Changes
-------------------

* Support using ``Statement.cancel()`` for all types of statements.

**Comment by electrum** [comment] 2017-11-01 20:17
```
CLI Changes
-----------

* Fix transaction support. Previously, the transaction was marked as cleared
  on the statement immediately following the ``START TRANSACTION`` statement.

**Comment by highker** [comment] 2017-11-02 05:07
General

- Fix the handling of an invalid input for :func:`slice`.

**Closed** 2017-11-02 23:54 UTC
