### ISSUE TITLE
Flaky Test: TestCreateViewVerification.testRunningInQueryBankMode

### ISSUE THREAD

**Issue by ZacBlanco** [prestodb/presto#20863] opened 2023-09-13 23:12 UTC
CI Run: https://github.com/prestodb/presto/actions/runs/6178244989/job/16771602986?pr=20720#step:7:26425

**Comment by tdcmeehan** [comment] 2023-09-19 14:57
CC: @ericyuliu

**Comment by rschlussel** [comment] 2024-03-21 21:04
Those logs aren't available anymore and i can't reproduce the issue, so I don't know where/why the test failed when it was flaky. I'm adding logging to help with debugging if the issue is encountered again, but I think we should close the issue for now as there's not enough info as things stand.

**Closed** 2024-04-04 14:10 UTC
Labels: bug, flaky-test
