### ISSUE TITLE
Flakey test TestStateCompiler.testComplexStateEstimatedSize

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#10250] opened 2018-03-23 21:47 UTC
```
[ERROR] testComplexStateEstimatedSize(com.facebook.presto.operator.aggregation.TestStateCompiler)  Time elapsed: 1.046 s  <<< FAILURE!
java.lang.AssertionError: expected [1899048] but found [1898959]
	at com.facebook.presto.operator.aggregation.TestStateCompiler.testComplexStateEstimatedSize(TestStateCompiler.java:362)

**Comment by nezihyigitbasi** [comment] 2018-03-26 16:04
Duplicate of #10109.

**Closed** 2018-06-07 08:44 UTC
Labels: tests
