### ISSUE TITLE
Presto query sometimes returns 0 rows and sometimes returns some rows

### ISSUE THREAD

**Issue by soulmachine** [prestodb/presto#4360] opened 2016-01-18 20:12 UTC
This is more like a beginner question.

I run the same query a few times, sometimes it returns 0 rows, and sometimes it returns some rows.

I'm using Presto 0.128.

My query is:

```
select timestamp,ip,tracer_geo_latitude,tracer_geo_longitude,year,month,day,hour,tracer_account_id, tracer_network_type from client_logs where tracer_network_type='3G' and year=extract(YEAR from now() at time zone 'gmt' - interval '7' hour) and month=extract(MONTH from now() at time zone 'gmt' - interval '7' hour) and day=extract(DAY from now() at time zone 'gmt' - interval '7' hour) and hour=extract(HOUR from now() at time zone 'gmt' - interval '7' hour);
```

I checked the log and there are two exceptions, one is:

```
2016-01-18T21:55:44.234Z        ERROR   http-worker-132146      com.facebook.presto.execution.QueryStateMachine Query 20160118_215539_00078_tjd7r failed
com.facebook.presto.spi.PrestoException: Query was canceled
        at com.facebook.presto.execution.SqlQueryManager.cancelQuery(SqlQueryManager.java:326)
        at com.facebook.presto.server.StatementResource$Query.cancel(StatementResource.java:275)
        at com.facebook.presto.server.StatementResource.cancelQuery(StatementResource.java:223)
        at sun.reflect.GeneratedMethodAccessor572.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:171)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:152)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:387)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:331)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:103)
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:297)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:254)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1030)
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:373)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:381)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:344)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
        at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
        at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:300)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at io.airlift.http.server.TraceTokenFilter.doFilter(TraceTokenFilter.java:63)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at io.airlift.http.server.TimingFilter.doFilter(TimingFilter.java:52)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:159)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:499)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:745)
```

Another exception is:

```
2016-01-18T21:05:37.745Z        WARN    http-client-shared-131953       com.facebook.presto.memory.RemoteNodeMemory     Error fetching memory info from http://172.18.81.122:8080/v1/memory: java.util.concurrent.TimeoutException
```

Is this phenomenon normal or not ?

**Comment by martint** [comment] 2016-01-18 20:14
That should never happen for deterministic queries. Can you paste your query?

**Comment by zchen-aa** [comment] 2016-05-19 06:35
Same here, have you solved your problem?

**Comment by rschlussel** [comment] 2017-03-24 14:55
Closing, since there isn't enough information here. If you can provide a query to reproduce the issue on the latest presto version, feel free to reopen.

**Closed by rschlussel** 2017-03-24 14:55 UTC

**Comment by youngyyy** [comment] 2019-11-12 09:24
@soulmachine do you solve the problem? I encountered the same problem recently
