### ISSUE TITLE
Mysql connector cannot retrieve tables which includes underscore in table name

### ISSUE THREAD

**Issue by darkrwe** [prestodb/presto#4983] opened 2016-04-11 08:01 UTC
presto-server-0.139 still have mysql connector problem .

Create database in mysql:

CREATE DATABASE TUTORIAL_1;
USE TUTORIAL_1;
 CREATE TABLE USERS (userid VARCHAR(15), gender CHAR(1), Age SMALLINT,country VARCHAR(50), SIGN_UP VARCHAR(50));

presto> SHOW TABLES FROM mysql.TUTORIAL_1;
 Table 
-------
(0 rows)

Query 20160301_082814_00005_fjdbm, FINISHED, 2 nodes
Splits: 2 total, 2 done (100.00%)
0:00 [0 rows, 0B] [0 rows/s, 0B/s]

**Comment by petroav** [comment] 2016-04-11 20:27
@darkrwe this should have been fixed in https://github.com/prestodb/presto/commit/dbd9288433cee809c823a0bfd1f2744da713400f so I don't know why you're running into this.

@kokosing when you get a chance, can you take a look since you have the most context?

**Comment by kokosing** [comment] 2016-04-12 05:31
I reproduced that. Which is strange as `https://github.com/prestodb/presto/commit/dbd9288433cee809c823a0bfd1f2744da713400f` have tests for that case and it is passing. I need to investigate this.

@martint Can you please assign me to this issue, I will fix it.

**Comment by kokosing** [comment] 2016-04-12 06:06
Somehow it is related with capital letters:
mysql:
```
mysql> create database UPPER;
Query OK, 1 row affected (0,00 sec)

mysql> use UPPER;
Database changed
mysql> create table lower (a int);
Query OK, 0 rows affected (0,03 sec)

mysql> create table UPPER (a int);
Query OK, 0 rows affected (0,03 sec)
```
presto:
```
presto> show tables from mysql.upper;
 Table
-------
(0 rows)
```

**Comment by kokosing** [comment] 2016-04-12 10:51
For sure it is related with capital letters in mysql database name. Here is a test to reproduce the problem: https://github.com/kokosing/presto/commit/c94675fd45705f45a4c3a59872c8210bd94689ee

@martint Currently presto converts all the schema (database) names to lower case. Therefore when source database have different name casing (? I am not sure this word) presto is losing mapping between its schema and source schema. This also leads to ambiguities errors when source database have two schemas which differ only in letter casing. In order to fix that issue we would need to make presto to be case sensitive. It could be done in the same way as other databases do: quoted name - case sensitive, not quoted case insensitive. If you agree I will create an issue for that.

@darkrwe As a workaround you can use 'tutorial_1' instead of 'TUTORIAL_1' and your queries should work.

**Comment by cberner** [comment] 2016-04-12 16:00
Yep, it's a known issue that Presto only supports lowercase identifiers: https://github.com/prestodb/presto/issues/2863

**Comment by kokosing** [comment] 2016-04-13 04:28
@cberner We could close this as a duplicate.

**Closed** 2016-04-13 04:28 UTC
