### ISSUE TITLE
singlestore-dockerized-tests job is failing often

### ISSUE THREAD

**Issue by majetideepak** [prestodb/presto#23049] opened 2024-06-21 08:10 UTC
The job is failing or is stuck

https://github.com/prestodb/presto/pull/23048

https://github.com/prestodb/presto/actions/runs/9602625504/job/26483886110?pr=23030
```
Cannot instantiate class com.facebook.presto.plugin.singlestore.TestSingleStoreTypeMapping
Error:  org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
Error:  
Error:  Cannot instantiate class com.facebook.presto.plugin.singlestore.TestSingleStoreTypeMapping
```

**Comment by elharo** [comment] 2024-06-21 13:58
dupe of https://github.com/prestodb/presto/issues/23006

**Closed by elharo** 2024-06-21 13:58 UTC
Labels: bug
