### ISSUE TITLE
Selective aggregates filtering applied too late

### ISSUE THREAD

**Issue by Vayu** [prestodb/presto#9528] opened 2017-12-11 14:29 UTC
Query
```
WITH test AS (
    SELECT * FROM (
        VALUES
            ('1', 'a', 'good'),
            ('2', 'b', 'good'),
            ('x', 'c', 'bad')
    ) AS t (v, k, name)
)
SELECT
    MAP_AGG(CAST(v AS BIGINT), LOWER(k)) FILTER (WHERE name = 'good') AS col1,
    ARRAY_AGG(CAST(v AS BIGINT)) FILTER (WHERE name = 'good') AS col2
FROM test
```
Fails with `Cannot cast 'x' to BIGINT`
Seems that casts are evaluated even for rows which will be filtered out by `FILTER` condition

If I add `WHERE name = 'good'` it doesn't fail, but semantically it is the same query

**Comment by martint** [comment] 2018-01-03 19:28
Closing as duplicate of #9656. That other issue has more details on the expected semantics.

**Closed by martint** 2018-01-03 19:28 UTC
Labels: bug
