### ISSUE TITLE
Remove unnecessary sorting

### ISSUE THREAD

**Issue by dain** [prestodb/presto#11008] opened 2018-07-10 17:53 UTC
Now that we have distributed sorts, sorting can use a huge amount of resources.  There are only a few places where ordering is necessary and we should remove all others during optimization.  For example, `select count(*) from (select * from orders order by 1)`.

**Comment by martint** [comment] 2018-07-10 17:55
Duplicate of https://github.com/prestodb/presto/issues/7613

**Closed by martint** 2018-07-10 17:55 UTC
Labels: enhancement
