### ISSUE TITLE
Compilation failed for presto-docs module when running on BusyBox

### ISSUE THREAD

**Issue by yogeek** [prestodb/presto#11841] opened 2018-11-02 17:07 UTC
I got the following error when trying to compile prestodb modules with maven :
```
[INFO] --- exec-maven-plugin:1.6.0:exec (validate-thrift-idl) @ presto-docs ---
diff: unrecognized option: c
BusyBox v1.28.4 (2018-07-17 15:21:40 UTC) multi-call binary.

Usage: diff [-abBdiNqrTstw] [-L LABEL] [-S FILE] [-U LINES] FILE1 FILE2

Compare files line by line and output the differences between them.
This implementation supports unified diffs only.

	-a	Treat all files as text
	-b	Ignore changes in the amount of whitespace
	-B	Ignore changes whose lines are all blank
	-d	Try hard to find a smaller set of changes
[...]
[ERROR] Command execution failed.
```

Steps to reproduce :
```
git clone  https://github.com/prestodb/presto.git
docker run --rm -it -v $(pwd):/app -w /app/presto --net=host maven:3.5-jdk-8-alpine bash

### in docker container ###
$ java -version
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (IcedTea 3.9.0) (Alpine 8.181.13-r0)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

# Get mvn wrapper
$ mvn -N io.takari:maven:wrapper

# Build presto
$ ./mvnw clean install -DskipTests
[...]
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:exec (validate-thrift-idl) on project presto-docs: Command execution failed.: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
```

It works correctly if I exclude presto-docs from the build :
```
./mvnw clean install -DskipTests -pl \!presto-docs
[...]
[INFO] BUILD SUCCESS
```

**Comment by yogeek** [comment] 2018-11-05 13:59
Indeed `diff` tool in busybox docker image is a link to `busybox`  multi-call binary that combines many common Unix	utilities into a single executable. 
The problem it is that this `diff` version in docker image does not include the `-c` option needed apparently by maven build.

After installed a compatible version of `diff` however, I get this error :
```
docker run --rm -it -v $(pwd):/app -w /app/presto --net=host maven:3.5-jdk-8-alpine bash

### in docker container ###
$ apk -U add diffutils
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
(1/1) Installing diffutils (3.6-r1)
[...]
OK: 112 MiB in 67 packages

$ ./mvnw clean install -DskipTests -pl presto-docs -am
[...]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] presto-root ........................................ SUCCESS [ 16.560 s]
[INFO] presto-spi ......................................... SUCCESS [02:10 min]
[INFO] presto-plugin-toolkit .............................. SUCCESS [ 19.634 s]
[INFO] presto-client ...................................... SUCCESS [ 14.816 s]
[INFO] presto-parser ...................................... SUCCESS [01:08 min]
[INFO] presto-geospatial-toolkit .......................... SUCCESS [ 19.039 s]
[INFO] presto-array ....................................... SUCCESS [  8.852 s]
[INFO] presto-matching .................................... SUCCESS [  5.876 s]
[INFO] presto-memory-context .............................. SUCCESS [  5.715 s]
[INFO] presto-tpch ........................................ SUCCESS [ 10.825 s]
[INFO] presto-benchto-queries ............................. SUCCESS [  4.603 s]
[INFO] presto-main ........................................ SUCCESS [05:02 min]
[INFO] presto-thrift-connector-api ........................ SUCCESS [ 23.277 s]
[INFO] presto-docs ........................................ FAILURE [ 55.462 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11:31 min
[INFO] Finished at: 2018-11-05T13:14:55Z
[INFO] Final Memory: 226M/2393M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.airlift.maven.plugins:sphinx-maven-plugin:2.0:generate (default) on project presto-docs: Failed to run the report: Sphinx report generation failed -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.airlift.maven.plugins:sphinx-maven-plugin:2.0:generate (default) on project presto-docs: Failed to run the report
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:200)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:196)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to run the report
	at io.airlift.maven.sphinx.SphinxMojo.execute(SphinxMojo.java:234)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 11 more
Caused by: org.apache.maven.reporting.MavenReportException: Sphinx report generation failed
	at io.airlift.maven.sphinx.SphinxMojo.runForkedSphinx(SphinxMojo.java:405)
	at io.airlift.maven.sphinx.SphinxMojo.executeReport(SphinxMojo.java:246)
	at io.airlift.maven.sphinx.SphinxMojo.execute(SphinxMojo.java:231)
	... 13 more

```

Do you think it is also linked the docker environment ? Do you have a docker image recommended to build this project please ?

**Comment by dain** [comment] 2018-11-05 21:00
I don't think anyone that works on this project builds in Docker, so we would be looking to you for a recommendation 😊

**Comment by yogeek** [comment] 2018-11-05 21:39
ok I will try to do some test and get back to you !
I you can just confirm me that the error above is not present in your build environment and tell me the Maven and java version of your build, it could help me. Thanks for the help :-)

**Comment by dain** [comment] 2018-11-05 21:44
@yogeek my setup is:
```
$ mvn --version
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T11:33:14-07:00)
Maven home: /usr/local/Cellar/maven/3.5.4/libexec
Java version: 1.8.0_181, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.1", arch: "x86_64", family: "mac"
```

**Comment by yogeek** [comment] 2018-11-06 10:52
@dain Thanks for the details. 
I can confirm you that I built successfully the project with the following docker image : `maven:3.5.4-jdk-8`

Here are the steps :
```
git clone https://github.com/prestodb/presto.git
cd presto
docker run --rm -it -v $(pwd):/presto -w /presto --net=host maven:3.5.4-jdk-8 bash

###### Inside the container :

# Get mvnw
mvn -N io.takari:maven:wrapper

# Build presto
./mvnw clean install -DskipTests
[...]
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13:32 min
[INFO] Finished at: 2018-11-06T10:32:47Z
[INFO] ------------------------------------------------------------------------
```

**Comment by findepi** [comment] 2018-12-12 20:00
@yogeek @dain 
i have nothing against having Alpine and BusyBox supported tools for development environment -- provided that someone commits to testing & maintenance.
I am closing this, assuming we won't fix this, unless someone interested sends a PR (and helps to maintain this afterwards).

**Closed by findepi** 2018-12-12 20:00 UTC

**Comment by Nymeriawolf** [comment] 2019-07-10 08:30
who can help me?
[INFO] presto-docs ........................................ FAILURE [ 29.824 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 36.554 s
[INFO] Finished at: 2019-07-10T07:20:56Z
[INFO] Final Memory: 50M/560M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.airlift.maven.plugins:sphinx-maven-plugin:2.0:generate (default) on project presto-docs: Failed to run the report: Sphinx report generation failed -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.airlift.maven.plugins:sphinx-maven-plugin:2.0:generate (default) on project presto-docs: Failed to run the report
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:200)
        at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:196)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to run the report
        at io.airlift.maven.sphinx.SphinxMojo.execute(SphinxMojo.java:234)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 11 more
Caused by: org.apache.maven.reporting.MavenReportException: Sphinx report generation failed
        at io.airlift.maven.sphinx.SphinxMojo.runForkedSphinx(SphinxMojo.java:405)
        at io.airlift.maven.sphinx.SphinxMojo.executeReport(SphinxMojo.java:246)
        at io.airlift.maven.sphinx.SphinxMojo.execute(SphinxMojo.java:231)
        ... 13 more

-bash-4.2# mvn --version      
Apache Maven 3.0.5 (Red Hat 3.0.5-17)
Maven home: /usr/share/maven
Java version: 1.8.0_212, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.212.b04-0.el7_6.aarch64/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "4.14.0-49.el7a.aarch64", arch: "aarch64", family: "unix"
