### ISSUE TITLE
Release notes for 0.182

### ISSUE THREAD

**Issue by nezihyigitbasi** [prestodb/presto#8622] opened 2017-07-27 22:34 UTC
## Dain Sundstrom
- [x]  07-26 21:42:45    0a9859d5b8 Fixup: Update to new MapBlock APIs
- [x]  07-26 21:42:45    176c32f8c9 Fixup: Update ChunkedSliceOutput to align with RCWriter
- [x]  07-26 21:42:45    1e597a75f2 Fixup: ORC getRetainedBytes calculations
- [x]  07-26 21:42:45    3ba0a6fdbb Update to latest ORC proto
- [x]  07-26 21:42:45    5dade58aef Fix typo in test ORC temp file name
- [x]  07-26 21:42:45    6b8b3fc7c6 Update ORC reader to UTF-8 string stats
- [x]  07-26 21:42:45    7394e9eedb Fixup: DictionaryCompressionOptimizer
- [x]  07-26 21:42:45    759e143f0a Update ORC writer to produce UTF-8 string stats
- [x]  07-26 21:42:45    aef3e4d970 Fixup: LongOutputStreamV1
- [x]  07-26 21:42:45    c0b3efb2a4 Add new ORC writer implementation
- [x]  07-26 21:42:45    cbe2bfae0f Fixup: Write full bytes in BooleanOutputStream.writeBooleans
- [x]  07-26 21:42:45    d5fda7aee8 Fixup: Consolidate and test ORC writeVLong code
- [x]  07-26 21:42:45    dd6d0daef1 Add array, map, row blocks column decomposition
- [x]  07-26 21:42:45    df0d5f0772 Review feedback for "Add new ORC writer implementation"
- [x]  07-26 21:42:45    e4aed76b21 Add more ORC statistics tests
- [x]  07-26 21:42:45    e6a7bc0374 Review feedback for "Add array, map, row blocks column decomposition"
- [x]  07-26 21:42:46    433a201e5e Sort ORC dictionary before writing
- [x]  07-26 21:42:46    cbb418e634 Fixup: Integrate new ORC writer into Hive connector
- [x]  07-26 21:42:46    d50d9b52e8 Add ORC write validation
- [x]  07-26 21:42:46    db03c71cbe Integrate new ORC writer into Hive connector
## David Phillips
- [x]  07-23 10:16:25    0864d13ca3 Implement subtraction of two timestamps
- [x]  07-24 11:17:12    5f8410aed3 Add Checkstyle rule for extends/implements
- [x]  07-24 11:17:12    a6364668d6 Fix code formatting for extends/implements
- [x]  07-24 11:25:24    816364a92e Remove trailing comma for annotation arrays
- [x]  07-24 11:25:24    ae38348a68 Add Checkstyle rule for indentation and spaces
- [x]  07-24 11:25:24    ca750957c6 Fix code formatting
- [x]  07-24 18:18:09    8309d81400 Clear interrupt flag after exiting from pager
- [x]  07-24 18:35:41    7e765e7483 Add multinode-tls to the presto-product-tests README
- [x]  07-24 18:41:16    e9c67a7b80 Document the push_aggregation_through_join property
## Grzegorz Kokosiński
- [x]  07-19 21:48:17    dfc73bee6b Remove redundant Lookup#resolve call
- [x]  07-19 22:14:13    19b59942a5 Add PruneTopNColumns Rule
- [x]  07-20 13:19:22    62d9637c94 Add PruneProjectColumns rule
- [x]  07-20 21:39:08    263b48717f Add the metadata portion of the TPC-DS connector
- [x]  07-20 21:39:08    54917490b8 Add a test for the TPC-DS connector
- [x]  07-20 21:39:08    6c06263881 Add the data generation portion of the TPC-DS connector
- [x]  07-24 12:50:01    56c2157398 Order entries in AggregationNode
- [x]  07-25 04:32:52    1568a56034 Fix a missing negation in MergeLimitWithDistinct#isDistinct
- [x]  07-25 05:48:23    4456400782 Extract CanonicalizeExpressionRewriter
- [x]  07-25 05:48:23    6a64f7dd6a Encapsulate CanonicalizeExpressionRewriter visitor
- [x]  07-25 05:48:23    90c4a6818a Add generic expression rewriter
- [x]  07-25 05:48:23    a633e16ad4 Migrate CanonicalizeExpressions to iterative optimizer
- [x]  07-25 21:36:55    3f91426a3a Factor out Rule#isEnabled(Session)
- [x]  07-25 22:28:23    f8752527af Rewrite join filters in SimplifyExpressions
- [x]  07-25 23:13:04    64e5373b66 Add PruneFilterColumns rule
- [x]  07-25 23:20:12    5f3c52d386 Add PruneAggregationColumns Rule
- [x]  07-25 23:20:12    7aba04cb3b Add PruneAggregationSourceColumns Rule
- [x]  07-26 05:15:59    3d1ec9933e Use dummy spiller when creating testing LocalExecutionPlanner
- [x]  07-26 05:15:59    41aa1ab09b Shutdown executor used in FileSingleStreamSpillerFactory
- [x]  07-26 05:15:59    e052e1c976 Do not check primitive for nullity
- [x]  07-26 05:36:09    47ae3ae501 Utilize static imports for canonicalizeExpression
- [x]  07-26 05:36:09    ac21639353 Rename CanonicalizeExpressionRewriter::rewrite to canonicalizeExpression
- [x]  07-26 14:26:48    9114e90f76 Minor re-writes to TPC-DS q36, q70 and q86
- [x]  07-26 14:26:48    c382bf95e5 Unquarantine TPC-DS q27, q36, q70 and q86
- [x]  07-28 00:16:44    a6451e1 Use Set to check if output symbols are correct 
## Haozhun Jin
- [x]  07-20 11:28:04    3030ab66d4 Refactor in Annotation based functions
- [x]  07-26 10:46:01    b252549df4 Fix BindExpression doc
## James Sun
- [x]  07-19 22:59:38    6f04eaac12 Fix TransformKey/Value benchmarks
## Karol Sobczak
- [x]  07-25 04:54:48    078dae18bf Skip PushPartialAggregationThroughJoin when hash symbol is present
- [x]  07-25 04:54:48    0c172823d9 Add support for filter functions in partial aggregation pushdown
- [x]  07-25 04:54:48    1ebf26f408 Remove remapping of pushed partial aggregation
- [x]  07-25 04:54:48    551cd2c1d7 Restrict output of join after partial aggregation pushdown
- [x]  07-25 04:54:48    815e792800 Add rule test for PushPartialAggregationThroughJoin
- [x]  07-25 04:54:48    84ecf3d01f Migrate PushPartialAggregationThroughExchange as a rule
- [x]  07-25 04:54:48    aadf477298 Remove legacy PartialAggregationPushDown optimizer
- [x]  07-25 04:54:48    e063d1560f Preserve symbols required by join during partial aggregation pushdown
- [x]  07-25 04:54:48    e9c8526519 Migrate PushPartialAggregationThroughJoin as a rule
## Martin Traverso
- [x]  07-20 13:42:33    eff7dcc2e2 Remove redundant path mapping
- [ ]  07-21 12:17:21    02f6e5061e Support column aliases in CREATE TABLE AS
- [x]  07-25 14:35:16    a2908801f7 Make artifacts upload less chatty
- [ ]  07-25 16:01:02    0058aa772a Change expected type to be Object instead of Block in Accumulator
- [x]  07-25 16:01:02    1e7c6bc651 Fix formatting in AccumulatorCompiler
- [x]  07-26 12:48:35    8bd5e129bb Do not print configuration in tests to avoid Travis log limit
- [ ]   07-31 19:02:47    fb1d38083b Fix CORR for negative correlations
## Nezih Yigitbasi
- [x]  07-20 09:42:23    5c1b685171 Fix PagesIndex.getEstimatedSize for empty index
- [x]  07-20 09:46:30    4e70e865fa Fix flaky test TestPrestoDriver::testQueryTimeout()
- [x]  07-20 09:48:31    8e12d6c12b Throw PrestoException for large columns in SliceDirectStreamReader
- [x]  07-20 09:49:30    4d2a0bfbfa Make sure to close keySectionOutput
- [x]  07-20 09:51:06    3ecc31506a Fix reading INT32/INT64 encoded Parquet decimals
- [x]  07-20 11:06:08    4df9290256 Add stage id/plan node id to generated page projection class name
- [x]  07-20 13:11:41    ffb3ccbe7e Make sure to call destroy() on close
- [x]  07-20 19:42:32    e07b91da07 Simplify resource group configuration with lambdas
- [x]  07-25 15:34:41    472a84043c Update use of deprecated JsonParseException constructor
- [x]  07-25 16:23:03    e3bdf5714d Throw PrestoException with HIVE_BAD_DATA code for corrupt RC files
- [x]  07-26 16:37:14    c713a8f0d5 Reject query if active worker nodes is insufficient
## Raghav Sethi
- [x]  07-20 12:06:20    564da8a476 Export split cpu time counters
- [x]  07-20 12:32:06    a0ba6184b7 Print catalog session properties on a new line
- [x]  07-25 17:26:20    f6b1f2eacf Improve exception handling connecting to resource group db
- [x]  07-25 19:53:30    5c14ce4d3a Fix dependency for presto-resource-group-managers
## Rongrong Zhong
- [x]  07-27 10:55:36    bda925eed5 Fix sub resource group stats
- [x]  07-27 21:28:25    11c0f307e1 Implement IPADDRESS type
- [x]  07-27 21:28:25    97cb0f9752 Add test for QueryResults
## Wenlei Xie
- [x]  07-25 14:52:36    064354c75f Optimize CAST from JSON to map
- [x]  07-25 14:52:36    0b3244324f Extract conversion from JsonToken to DECIMAL into JsonUtil
- [x]  07-25 14:52:36    1fb31cc7ff Optimize CAST from JSON to array
- [x]  07-25 14:52:36    2103ae179b Add cast from JSON to TINYINT/SMALLINT
- [x]  07-25 14:52:36    2a62cf54c8 Remove TypeJsonUtils
- [x]  07-25 14:52:36    50424aa3b9 Extract conversion from JsonToken to Presto type into JsonUtil
- [x]  07-25 14:52:36    5efd991c89 Add benchmark for JSON to array/map cast
- [x]  07-25 14:52:36    98ed287f51 Clean up JSON cast related methods in TypeJsonUtils
## Łukasz Osipiuk
- [x]  07-21 15:57:25    1108808887 Unify ExpressionInterpreter.invoke and FunctionInvoker code
- [x]  07-21 15:57:25    45337fe9f1 Remove ExpressionInterpreter.invoke, use FunctionInvoker instead
- [x]  07-21 15:57:25    49b3ac7967 Pass FunctionRegistry instead of whole Metadata
- [x]  07-21 15:57:25    8b34d90ab7 Fix handling ConnectorSession in FunctionInvoker
- [x]  07-21 15:57:25    e779e626df Fix IntelliJ warnings in ExpressionInterpreter
- [x]  07-25 06:24:17    e40babca2e Fix date constant in test
- [x]  07-26 02:35:44    dfdfd33d6a Test Join using stateful filter function
- [x]  07-26 06:39:55    074f1b05f5 Add Estimate.zeroValue()
- [x]  07-26 06:39:55    445492cf2e Add requireNonNull in ColumnStatistics
- [x]  07-26 06:39:55    68a44203df Make methods private in ShowStatsRewrite where possible
- [x]  07-26 08:09:24    252ee52b92 Remove maps from TableStatistics and ColumnStatistics
- [x]  07-26 08:09:24    3b52d7a1a8 Rename variables in ShowStatsRewrite.rewriteShowStats
- [x]  07-31 19:06:05    27d5488d8b Rename joinConditionBuilder variable in PredicatePushDown
- [x]  07-31 19:06:09    a6b2e75d37 Do not plan INNER join with just filter function

**Comment by caithagoras** [comment] 2017-07-28 19:44
General
 - Add a config option to reject queries during cluster initialization. Queries are rejected if active worker count is less than the ``query-manager.initialization-required-workers`` when coordinator up time is less than ``query.manager.initialization-timeout``.

**Comment by wenleix** [comment] 2017-07-28 22:39
General

- Improve performance of CAST from JSON to ARRAY/MAP type.

**Comment by nezihyigitbasi** [comment] 2017-08-01 02:11
@rongrong's release notes:

```
* Add a new type :ref: `ipaddress_type` to represent IP address. 
```

**Comment by nezihyigitbasi** [comment] 2017-08-01 02:32
```
Hive Changes
------------

* Fix reading decimal values in the optimized Parquet reader when they are backed
  by the ``int32`` or ``int64`` types.
```

**Comment by kokosing** [comment] 2017-08-01 05:09
General
 * Introduce the `TPC-DS` connector. This connector provides a set of schemas to support the TPC Benchmark™ DS (TPC-H).
 * improve planning performance for queries which consists of multiple joins with tables that have many ( counted in hundreds) columns

**Comment by losipiuk** [comment] 2017-08-01 07:09
General:
 * Improve performance of joins with just non-equality conditions by using a nested-loops join instead of a hash join.

**Comment by maciejgrzybek** [comment] 2017-08-01 15:35
@martint:
`Change expected type to be Object instead of Block in Accumulator` (0058aa7) could go as:

```
**Fix execution of several window functions on array and map types**

Some window functions taking array or map types (e.g. approx_percentile) were not executing before that patch.
```

**Comment by losipiuk** [comment] 2017-08-01 15:37
@martint: this is from @maciejgrzybek  concerning `Change expected type to be Object instead of Block in Accumulator`

General:
* Fix execution of several window functions (e.g. approx_percentile) on array and map types

**Comment by raghavsethi** [comment] 2017-08-01 19:41
* Add :func:`to_milliseconds` function to convert intervals (day to second) to milliseconds.

**Comment by nezihyigitbasi** [comment] 2017-08-02 05:31
@maciejgrzybek 
>> Fix execution of several window functions on array and map types

Which window functions are fixed? That commit only has tests for `approx_percentile`, any other functions affected?

**Comment by nezihyigitbasi** [comment] 2017-08-02 05:59
@raghavsethi please add documentation for `to_milliseconds` in datetime functions doc.

**Comment by nezihyigitbasi** [comment] 2017-08-02 06:23
@raghavsethi Just saw your PR, thanks.

**Comment by arthurhsk** [comment] 2017-08-02 07:35
https://github.com/prestodb/presto/issues/6386

Will this ticket be fixed in coming release?

**Comment by nezihyigitbasi** [comment] 2017-08-02 07:48
@arthurhsk Nope. I don't think anyone looked at that issue.

**Comment by maciejgrzybek** [comment] 2017-08-02 15:28
@nezihyigitbasi:
>Which window functions are fixed? That commit only has tests for `approx_percentile`, any other functions affected?

All functions accepting Block (map, array) as a scalar parameter.
We have three types of window functions:
1. accepting scalars (e.g. `sum(bigint)`, `avg(double)` etc.)
2. accepting blocks as a set of values (e.g. `map_agg(bigint, array[bigint])`)
3. accepting block as a scalar value (to represent maps and arrays), e.g. the aforementioned `approx_percentile(T, ARRAY[T])`.

The third type was affected.

Example of functions affected:
`approx_percentile(T, array[T])`, e.g. `select approx_percentile(1, array [1]) over();`
`min(array [T])`, e.g. `select min(array [1]) over();`
`max(array [T])`, e.g. `select max(array [1]) over();`

However, although `map_agg` is accepting `Block` as input, it was not affected by the bug because it was not retrieving the `Block` as a scalar argument to the function. Instead, `map_agg` retrieves a set of scalar values to be processed as a `Block`.
The bug was caused by a mistake I made in retrieving the `Block` scalar values (maps, arrays) from the `WindowIndex`.

We don't have to test other functions because the fix is not specific to any of the affected functions. We just need single representation to prevent regressions.

Does it make sense to you, @nezihyigitbasi?

**Comment by dain** [comment] 2017-08-02 15:47
```
Hive
----
* Add new, experimental ORC writer implementation optimized for Presto.  We have some up coming improvements, so we recommend waiting a few releases before using this in production. The new writer can be enabled with the ``hive.orc.optimized-writer.enabled`` configuration property or with the ``orc_optimized_writer_enabled`` session property.

**Comment by martint** [comment] 2017-08-03 16:12
```
* Fix correctness issue that causes :func:`corr` to return positive numbers for inverse correlations.
* Fix query failure when certain aggregations (e.g., :func:`approx_percentile`) are used as window functions.
* Add support for column aliases in ``CREATE TABLE ... AS`` statements.
```

**Comment by electrum** [comment] 2017-08-03 17:25
```
General Changes
---------------

* Implement subtraction for all ``TIME`` and ``TIMESTAMP`` types.

CLI Changes
-----------

* Fix an issue that would sometimes prevent queries from being cancelled when exiting from the pager.

**Closed** 2017-08-03 20:04 UTC
