### ISSUE TITLE
presto does not support redash when source is hive and  external table exists

### ISSUE THREAD

**Issue by derekennui** [prestodb/presto#11907] opened 2018-11-13 03:29 UTC
When I run the query 

SELECT table_schema, table_name, column_name
        FROM hive.information_schema.columns
        WHERE table_schema NOT IN ('pg_catalog', 'information_schema')

it reports error
failed: outputFormat should not be accessed from a null StorageFormat

I found the error in source code in com.facebook.presto.hive.metastore.StorageFormat,change the code

public String getOutputFormat()
{
    if (outputFormat == null) {
        return "null";
        //throw new IllegalStateException("outputFormat should not be accessed from a null StorageFormat");
    }
    return outputFormat;
}

It works.

I'm not gonna query hive external table, but if I don't change the code above, I can't config the redash hive source.

**Comment by kokosing** [comment] 2018-11-13 05:09
It looks like duplicate of #6972

**Closed by kokosing** 2018-11-13 05:09 UTC
