### ISSUE TITLE
presto0.278-hive catalog-UnknownHostException

### ISSUE THREAD

**Issue by xiaowuzi010599** [prestodb/presto#18803] opened 2022-12-14 05:25 UTC
since i retsart Presto.I want to query data from hudi sync table,and the first time 
![impicture_20221214_121014](https://user-images.githubusercontent.com/79125320/207503699-a56892fa-1b11-480e-ae4a-3b1deba6af86.png)
![impicture_20221214_121026](https://user-images.githubusercontent.com/79125320/207503721-aa24940a-c7e1-44db-9ae3-92711fb6f393.png)
then i change a normal hive table,it can work,and i query the hudi sync table again,it can work,why?
![impicture_20221214_132408](https://user-images.githubusercontent.com/79125320/207513018-01a49835-5718-463e-9c66-cb5dc14e41d6.png)
![impicture_20221214_132454](https://user-images.githubusercontent.com/79125320/207513109-7c73d85c-6209-4d07-9356-3725a145307b.png)

**Comment by pratyakshsharma** [comment] 2022-12-29 18:23
@imjalpreet @agrawalreetika Do you guys have some pointers around why this could be happening?

**Comment by imjalpreet** [comment] 2022-12-29 18:51
@xiaowuzi010599 This looks like the configuration did not get initialized when the HUDI table is first queried after a cluster start and might be a bug but will need to investigate. Can you confirm if you also include hadoop config files(core-site, hdfs-site etc) via hive catalog file property (`hive.config.resources`)?

We will try to look into it and figure out the root cause.

**Comment by xiaowuzi010599** [comment] 2023-01-03 01:57
> @xiaowuzi010599 This looks like the configuration did not get initialized when the HUDI table is first queried after a cluster start and might be a bug but will need to investigate. Can you confirm if you also include hadoop config files(core-site, hdfs-site etc) via hive catalog file property (`hive.config.resources`)?
> 
> We will try to look into it and figure out the root cause.

Yes, I am sure I have configured hive.config.resources, otherwise the ordinary hive query may also fail.

**Comment by xiaowuzi010599** [comment] 2023-01-03 01:58
> @xiaowuzi010599 This looks like the configuration did not get initialized when the HUDI table is first queried after a cluster start and might be a bug but will need to investigate. Can you confirm if you also include hadoop config files(core-site, hdfs-site etc) via hive catalog file property (`hive.config.resources`)?
> 
> We will try to look into it and figure out the root cause.

Yes, I am sure I have configured hive.config.resources, otherwise the ordinary hive query may also fail. @imjalpreet

**Comment by xiaowuzi010599** [comment] 2023-01-03 02:00
> @imjalpreet @agrawalreetika Do you guys have some pointers around why this could be happening?

From the stack information, the program calls the createnonhaproxy method, but our cluster construction is entirely in ha mode. @pratyakshsharma

**Comment by imjalpreet** [comment] 2023-01-03 04:39
> > @xiaowuzi010599 This looks like the configuration did not get initialized when the HUDI table is first queried after a cluster start and might be a bug but will need to investigate. Can you confirm if you also include hadoop config files(core-site, hdfs-site etc) via hive catalog file property (`hive.config.resources`)?
> 
> > 
> 
> > We will try to look into it and figure out the root cause.
> 
> 
> 
> Yes, I am sure I have configured hive.config.resources, otherwise the ordinary hive query may also fail. @imjalpreet 

Yes, I just wanted to confirm whether in your case do you make use of that config property or not since that is not a mandatory config. Thanks for confirming.

This confirms that the configuration is not getting initialized properly in the HUDI code path and we will investigate this and update you.

**Comment by imjalpreet** [comment] 2023-01-03 04:41
> > @imjalpreet @agrawalreetika Do you guys have some pointers around why this could be happening?
> 
> 
> 
> From the stack information, the program calls the createnonhaproxy method, but our cluster construction is entirely in ha mode. 

That's probably due to the same reason, since the config is not getting initialized it might be going ahead with the default values.

**Comment by rohanpednekar** [comment] 2023-02-08 20:55
@xiaowuzi010599 Do you still need any help on this issue?

**Comment by xiaowuzi010599** [comment] 2023-02-09 03:47
> @xiaowuzi010599 Do you still need any help on this issue?

This problem has been solved in version 0.279, and I also want to know about the specific code changes. What should I do?

**Comment by yzhang1991** [comment] 2023-02-15 21:55
@imjalpreet Can you provide a pointer? Thanks!

**Comment by imjalpreet** [comment] 2023-02-22 08:48
@xiaowuzi010599 This was the change which fixed querying HUDI tables in 0.279: #18441 

There are still some issues with HUDI MOR realtime tables which will be fixed soon as well (#18911)

**Comment by pratyakshsharma** [comment] 2023-03-08 21:52
@xiaowuzi010599 Please let us know in case you are looking for any more support.

**Closed** 2023-03-09 01:10 UTC

**Comment by zhongtiancai** [comment] 2024-07-15 13:32
> > @xiaowuzi010599 Do you still need any help on this issue?
> 
> This problem has been solved in version 0.279, and I also want to know about the specific code changes. What should I do?

I get the same exception in 0.286

1、throw the UnknownHostException
2、the program calls the createnonhaproxy method, but our cluster construction is entirely in ha mode.
3、the hive.config.resources is set，But it's the same effect as not set。
4、the ordinary hive query is success。
