### ISSUE TITLE
Improve type of hash_code operator and combine_hash function

### ISSUE THREAD

**Issue by cberner** [prestodb/presto#4040] opened 2015-11-26 06:43 UTC
The type of hash_code and combine_hash is declared to be `BIGINT`. However, there are lots of assumptions in the code base that the value returned from these functions will be within the range of an `int`. We either need to remove these assumptions, or change the type to `INT` (and implement an `INT` type)

**Comment by xerial** [comment] 2016-07-13 20:26
@cberner 
A problem related this is `SELECT rank() OVER(PARTITION_BY id)` creates inaccurate windows if combine_hash(id) has collisions in 32-bit `int` space.

**Comment by martint** [comment] 2016-07-13 20:43
The issue with hash sizes should already be fixed since we moved them to 64 bits.

@xerial, that would be a correctness issue. Computing the partitions shouldn't be sensitive to whether there are collisions, since it should do equality comparisons for the partition column. That should only affect performance, but not the results.

**Comment by xerial** [comment] 2016-07-13 21:26
@martint We found this problem `PARTITION BY (large string column)` in Presto 0.146, and suspect WindowOperator.findGroupEnd might have problem: https://github.com/prestodb/presto/blob/688a8ff0128169d8e0c4b28094ab29457bd1269b/presto-main/src/main/java/com/facebook/presto/operator/WindowOperator.java#L469

**Comment by martint** [comment] 2016-07-13 21:51
That code compares positions with `positionEqualsPosition`, so it should be insensitive to hash collisions. The shortcut just checks whether the first position matches the last one to avoid having to do the linear scan.

So, I suspect that is some other issue (or the implementation of those functions is broken).

**Comment by xerial** [comment] 2016-07-13 22:30
I have been failing to reproduce this issue when using only a window function. The problem occurs when complex sub queries are involved. I'll find our the exact condition to reproduce the issue.

**Comment by xerial** [comment] 2016-07-13 23:22
I found some clue by tweaking queries. Here is a simplified version of the original query:

```
-- OK query
with A as (select concat(c1, c2) id, rank() over(partition by order by time) r from B) 
select b.id, rank() over(partition by id order by r) from a join b on a.id = b.id 
```

```
-- BAD query  (b.id is replaced with a.id. Produces weird rank values)
with A as (select concat(c1, c2) id, rank() over(partition by id order by time) r from B) 
select a.id, rank() over(partition by id order by r) from a join b on a.id = b.id 
```

The above query should produce almost same query plan, but the exchange step is missing in the bad query. 

```
> - Window[partition by (<concat>), order by (rank)] => [rank:bigint, concat:varchar, $hashvalue_116:bigint, rank_89:bigint]
11,13c11,12  <<--------------- (OK plan)
<   - Exchange[REPARTITION] => concat_42:varchar, rank:bigint, $hashvalue:bigint
<      - Project => [rank:bigint, concat_42:varchar, $hashvalue_117:bigint]
<             $hashvalue_117 := "combine_hash"(BIGINT '0', COALESCE("$operator$hash_code"("concat_42"), 0))
---              <<---------------- (NG plan that produces weird rank values)
>      - Project => [rank:bigint, concat:varchar, $hashvalue_116:bigint]
>              $hashvalue_116 := "combine_hash"(BIGINT '0', COALESCE("$operator$hash_code"("concat"), 0))
```

**Comment by martint** [comment] 2016-07-13 23:25
That's not good. Can you file a separate issue for that? 

Also, your first query is missing something in the `partition by ???? order by time` clause.

**Comment by xerial** [comment] 2016-07-13 23:26
OK. I'll create another ticket.

**Comment by martint** [comment] 2016-07-13 23:27
Closing this one, since hashes are now 64-bit wide.

**Closed by martint** 2016-07-13 23:27 UTC
Labels: intermediate-task

**Comment by xerial** [comment] 2016-07-13 23:56
Filed the issue to https://github.com/prestodb/presto/issues/5659
