### ISSUE TITLE
Hive connector: sort bucketed tables not handled correctly

### ISSUE THREAD

**Issue by cberner** [prestodb/presto#3603] opened 2015-09-14 22:56 UTC
User on mailing list reported that reading from a sort bucketed table does not work properly: https://groups.google.com/forum/#!topic/presto-users/PjohcRjcbZw

We need a test for this case in `AbstractTestHiveClient`

**Comment by taklwu** [comment] 2016-08-17 06:27
is this still an open issue?

**Comment by haozhun** [comment] 2017-02-09 19:43
We never got a reproduce of this issue. Unfortunately, the information available in the mailing list was quite limited.

**Comment by electrum** [comment] 2019-01-13 07:12
Closing this since there is no reproduction.

**Closed by electrum** 2019-01-13 07:12 UTC
Labels: bug, intermediate-task
