### ISSUE TITLE
Query with nested window functions fails

### ISSUE THREAD

**Issue by cberner** [prestodb/presto#7257] opened 2017-01-31 18:30 UTC
```
SELECT x, max(z2) over()
FROM
(SELECT x, z, sum(z) over (order by z) as z2
FROM
(SELECT x, sum(y) as z
FROM (values (1, 2)) t(x, y)
GROUP BY 1))
```

fails with
```
java.lang.IllegalArgumentException: Invalid node. Window function dependencies ([sum_13]) not in source plan output ([field])

	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
	at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker.checkDependencies(ValidateDependenciesChecker.java:620)
	at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker.access$100(ValidateDependenciesChecker.java:77)
	at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitWindow(ValidateDependenciesChecker.java:184)
	at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitWindow(ValidateDependenciesChecker.java:91)
	at com.facebook.presto.sql.planner.plan.WindowNode.accept(WindowNode.java:153)
	at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitOutput(ValidateDependenciesChecker.java:300)
	at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitOutput(ValidateDependenciesChecker.java:91)
	at com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:81)
	at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker.validate(ValidateDependenciesChecker.java:88)
	at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker.validate(ValidateDependenciesChecker.java:83)
	at com.facebook.presto.sql.planner.sanity.PlanSanityChecker.lambda$validate$0(PlanSanityChecker.java:44)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.facebook.presto.sql.planner.sanity.PlanSanityChecker.validate(PlanSanityChecker.java:44)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:127)
```

**Comment by martint** [comment] 2017-01-31 18:37
Duplicate of https://github.com/prestodb/presto/issues/7247

**Closed by martint** 2017-01-31 18:37 UTC
Labels: duplicate, RELEASE-BLOCKER
