### ISSUE TITLE
Issue with grouping sets combined with grouping()

### ISSUE THREAD

**Issue by lyxking2009** [prestodb/presto#8498] opened 2017-07-13 21:11 UTC
I got an issue when using grouping() combined with grouping sets. I am doing this on a newly created table.

    SELECT
    ds
    ,column
    ,CASE grouping(ds, column)
     WHEN 0 THEN 'ds,column aggregation'
     WHEN 1 THEN 'ds aggreagtion'
     END AS aggregation_type
    FROM stg_table_
    GROUP BY GROUPING SETS (
    (ds, column),
    (ds)
    )

it gives an error message below:
PrestoQueryFailedException:Column 'ds' cannot be resolved

What concerned me was, some of my older query with almost identical form can still run, only this one failed. The only difference is, the older table was created through Hive, the new table today is created directly in presto, I am not sure if that is the cause

**Comment by findepi** [comment] 2017-07-14 10:49
I could not reproduce the problem with:

```
presto> use hive.default;
presto:default> create table stg_table_ as select 1 ds, 1 column;
CREATE TABLE: 1 row

Query 20170714_104804_00007_wa9jk, FINISHED, 1 node
Splits: 51 total, 51 done (100.00%)
0:01 [0 rows, 0B] [0 rows/s, 0B/s]

presto:default> SELECT
             -> ds
             -> ,column
             -> ,CASE grouping(ds, column)
             ->  WHEN 0 THEN 'ds,column aggregation'
             ->  WHEN 1 THEN 'ds aggreagtion'
             ->  END AS aggregation_type
             -> FROM stg_table_
             -> GROUP BY GROUPING SETS (
             -> (ds, column),
             -> (ds)
             -> );
 ds | column |   aggregation_type
----+--------+-----------------------
  1 |      1 | ds,column aggregation
  1 | NULL   | ds aggreagtion
(2 rows)
```


Could you please provide exact repro steps (how do you create table), which presto you're using and also full exception being raised (run CLI with `--debug`).

**Comment by martint** [comment] 2017-07-14 14:25
This is a duplicate of https://github.com/prestodb/presto/issues/8499

**Closed by martint** 2017-07-14 14:25 UTC
