### ISSUE TITLE
Bad error message for correlated subquery

### ISSUE THREAD

**Issue by martint** [prestodb/presto#7030] opened 2017-01-09 23:36 UTC
This query:

```sql
WITH t(a) AS (VALUES 1)
SELECT
 (SELECT 1 FROM t WHERE a = CAST(u.a as BIGINT))
FROM t u
GROUP BY CAST(a AS BIGINT)
```

Fails with 
```
java.lang.IllegalArgumentException: Input does not contain symbols from correlation
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
	at com.facebook.presto.sql.planner.plan.ApplyNode.<init>(ApplyNode.java:52)
	at com.facebook.presto.sql.planner.SubqueryPlanner.appendSubqueryApplyNode(SubqueryPlanner.java:495)
	at com.facebook.presto.sql.planner.SubqueryPlanner.appendScalarSubqueryApplyNode(SubqueryPlanner.java:222)
	at com.facebook.presto.sql.planner.SubqueryPlanner.appendScalarSubqueryApplyNodes(SubqueryPlanner.java:210)
	at com.facebook.presto.sql.planner.SubqueryPlanner.handleSubqueries(SubqueryPlanner.java:134)
	at com.facebook.presto.sql.planner.SubqueryPlanner.handleSubqueries(SubqueryPlanner.java:128)
	at com.facebook.presto.sql.planner.QueryPlanner.handleSubqueries(QueryPlanner.java:679)
	at com.facebook.presto.sql.planner.QueryPlanner.plan(QueryPlanner.java:141)
	at com.facebook.presto.sql.planner.RelationPlanner.visitQuerySpecification(RelationPlanner.java:409)
	at com.facebook.presto.sql.planner.RelationPlanner.visitQuerySpecification(RelationPlanner.java:92)
	at com.facebook.presto.sql.tree.QuerySpecification.accept(QuerySpecification.java:125)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
	at com.facebook.presto.sql.planner.QueryPlanner.planQueryBody(QueryPlanner.java:215)
	at com.facebook.presto.sql.planner.QueryPlanner.plan(QueryPlanner.java:110)
	at com.facebook.presto.sql.planner.RelationPlanner.visitQuery(RelationPlanner.java:402)
	at com.facebook.presto.sql.planner.RelationPlanner.visitQuery(RelationPlanner.java:92)
	at com.facebook.presto.sql.tree.Query.accept(Query.java:92)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
	at com.facebook.presto.sql.planner.LogicalPlanner.createRelationPlan(LogicalPlanner.java:347)
	at com.facebook.presto.sql.planner.LogicalPlanner.planStatement(LogicalPlanner.java:152)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:114)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:109)
	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:292)
	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:271)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:229)
	at com.facebook.presto.execution.QueuedExecution.lambda$start$1(QueuedExecution.java:62)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by findepi** [comment] 2017-01-10 15:40
As far as I can tell, the problem is in how we handle scopes in 
`StatementAnalyzer#visitQuerySpecification`. Because `GROUP BY` clause can reference select expression (e.g. `GROUP BY 1`), we process those before analyzing grouping expressions. However, when analyzing select expressions we should already know the grouping expressions. If there is grouping, the columns from the source (table) should *not* show up in the scope, only the ones used as grouping expressions.

I see two options here

1. `StatementAnalyzer#visitQuerySpecification` do a "two-pass" analysis. Peek into select expressions to be able to resolve `GROUP BY n`-s, then analyze the group by clause, create appropriate scope and fully analyze select expressions.

2. Do a kind of query rewrite (probably via `StatementRewrite`) so that `GROUP BY n`-s get eliminated before `StatementAnalyzer` is called. Arguably, this would make `StatementAnalyzer` slightly simpler.

@martint, do you have an opinion on this?

**Comment by kokosing** [comment] 2017-01-11 09:09
SQL allows to express the same thing in several forms. In this case user can:
```
SELECT x + b .... GROUP 1
```
and 
```
SELECT x + b ... GROUP x + b
```
If I understand it correctly both of them have the same semantic. If so then I think it would be better for planner in such case to support only one form of it (no need for strange `IF`, and `SemanticAnalyzer will be less complicated).

That means I vote for option 2. But I not an expert of SQL, so specification has to be checked in order to be sure that these two forms are equivalent.

**Comment by martint** [comment] 2017-01-11 16:50
Rewriting queries during analysis is an anti-pattern. It's problematic for a number of reasons:
- not everything can be rewritten to other syntactic forms. E.g., `SELECT * FROM t GROUP BY 1'`
- it's hard to relate errors in the rewritten form to the original query, which means we can't report precise errors to users.
- how far do you take it? Would `SELECT x FROM t GROUP BY t.x` be rewritten to `SELECT t.x FROM t GROUP BY t.x`? It would require some analysis. How about `SELECT DISTINCT x FROM t` vs `SELECT x FROM t GROUP BY x`?

For what it's worth, I went down this path in the early days of presto, and had to change strategy.

**Comment by findepi** [comment] 2017-01-11 16:56
Thanks for the guidance. I will look into the "two-passes" option then.

**Comment by kokosing** [comment] 2017-01-12 06:47
Thank you, sounds reasonable.

**Closed** 2017-04-27 02:48 UTC
Labels: bug
