### ISSUE TITLE
No Implicit Coercion in SemiJoin

### ISSUE THREAD

**Issue by geraint0923** [prestodb/presto#5268] opened 2016-05-12 17:57 UTC
```
presto:tiny> explain select orderkey from orders where orderkey in (values 39301, 39330);
                                                         Query Plan
-----------------------------------------------------------------------------------------------------------------------------
 - Output[orderkey] => [orderkey:bigint]
     - RemoteExchange[GATHER] => orderkey:bigint
         - Project => [orderkey:bigint]
             - Filter["semijoin_result"] => [orderkey:bigint, semijoin_result:boolean]
                 - Project => [orderkey:bigint, semijoin_result:boolean]
                     - SemiJoin[orderkey = field] => [orderkey:bigint, $hashvalue:bigint, semijoin_result:boolean]
                         - Project => [orderkey:bigint, $hashvalue:bigint]  <----- 'orderkey' is bigint
                                 $hashvalue := "combine_hash"(BIGINT '0', COALESCE("$operator$hash_code"("orderkey"), 0))
                             - TableScan[tpch:tpch:orders:sf0.01, originalConstraint = true] => [orderkey:bigint]
                                     orderkey := tpch:orderkey
                         - RemoteExchange[REPARTITION] => field:integer, $hashvalue_6:bigint
                             - Project => [field:integer, $hashvalue_7:bigint]
                                     $hashvalue_7 := "combine_hash"(BIGINT '0', COALESCE("$operator$hash_code"("field"), 0))
                                 - Values => [field:integer]                <----- integer
                                         (39301)
                                         (39330)
```

```
presto:tiny> select orderkey from orders where orderkey in (values 39301, 39330);

Query 20160512_175141_00023_e9yg3, FAILED, 4 nodes
http://localhost:8080/query.html?20160512_175141_00023_e9yg3
Splits: 21 total, 6 done (28.57%)
CPU Time: 0.0s total,     0 rows/s,     0B/s, 0% active
Per Node: 0.0 parallelism,     0 rows/s,     0B/s
Parallelism: 0.0
0:00 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20160512_175141_00023_e9yg3 failed: Expected one BIGINT parameter
java.lang.IllegalArgumentException: Expected one BIGINT parameter
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
	at com.facebook.presto.tpch.TpchNodePartitioningProvider.getBucketFunction(TpchNodePartitioningProvider.java:82)
	at com.facebook.presto.sql.planner.NodePartitioningManager.getPartitionFunction(NodePartitioningManager.java:78)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:312)
	at com.facebook.presto.execution.SqlTaskExecution.<init>(SqlTaskExecution.java:157)
	at com.facebook.presto.execution.SqlTaskExecution.createSqlTaskExecution(SqlTaskExecution.java:119)
	at com.facebook.presto.execution.SqlTaskExecutionFactory.create(SqlTaskExecutionFactory.java:73)
	at com.facebook.presto.execution.SqlTask.updateTask(SqlTask.java:275)
	at com.facebook.presto.execution.SqlTaskManager.updateTask(SqlTaskManager.java:314)
	at com.facebook.presto.server.TaskResource.createOrUpdateTask(TaskResource.java:123)
	at sun.reflect.GeneratedMethodAccessor403.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1689)
	at io.airlift.http.server.TraceTokenFilter.doFilter(TraceTokenFilter.java:63)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
	at io.airlift.http.server.TimingFilter.doFilter(TimingFilter.java:52)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:396)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1176)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1106)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:518)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:314)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:246)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:156)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by martint** [comment] 2016-05-12 19:19
This is a duplicate of https://github.com/prestodb/presto/issues/4715

**Closed by martint** 2016-05-12 19:19 UTC
Labels: bug, duplicate

**Comment by sopel39** [comment] 2016-12-16 09:46
fixed by: https://github.com/prestodb/presto/pull/6808
```
presto:sf0.1> select orderkey from orders where orderkey in (values 39301, 39330);
 orderkey 
----------
    39301 
    39330 
(2 rows)
```
