### ISSUE TITLE
Selecting Aggregate Partitioned by a Nested Aggregate

### ISSUE THREAD

**Issue by dlahn** [prestodb/presto#7293] opened 2017-02-03 13:48 UTC
I am noticing this behaviour since trying to upgrade to 0.165. This issue was not present for the same query in 0.155. I have managed to reproduce this for a simple table and query:

```
 CREATE TABLE `people` (
   `PersonID` int(5),
   `LastName` varchar(255),
   `FirstName` varchar(255)
 )
```
```
SELECT *, MIN(min_PersonID) OVER (PARTITION BY min_PersonID2) AS minbypersonid 
FROM (
    SELECT *,MIN(PersonID) OVER (PARTITION BY PersonID2) AS min_PersonID, MIN(PersonID2) OVER (PARTITION BY PersonID) AS min_PersonID2 
    FROM (
        SELECT *, PersonID as PersonID2 from people
    )
);
```
Running this query yields, the following error:

`Query 20170203_122355_00026_96i97 failed: Output layout ([personid, lastname, firstname]) don't include all partition columns ([min_18])`

This seems to be due to partitioning by the nested aggregate in the top-level aggregate.

**Comment by maciejgrzybek** [comment] 2017-02-03 19:38
This is a duplicate of https://github.com/prestodb/presto/issues/7247.
Fix is on it's way. Performing tests now and should be PRed momentarily.

**Closed** 2017-02-09 17:52 UTC
