### ISSUE TITLE
TestRaptorIntegrationSmokeTestBucketed::testCreateBucketedTable is flaky

### ISSUE THREAD

**Issue by nezihyigitbasi** [prestodb/presto#8487] opened 2017-07-12 20:14 UTC
Here is a failing instance: https://travis-ci.org/prestodb/presto/jobs/252942975

```
Tests run: 1668, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1,351.269 sec <<< FAILURE! - in TestSuite
testCreateBucketedTable(com.facebook.presto.raptor.TestRaptorIntegrationSmokeTestBucketed)  Time elapsed: 1.637 sec  <<< FAILURE!
java.lang.AssertionError: 
For query: 
 SELECT count(DISTINCT "$shard_uuid") FROM orders_bucketed
not equal
Actual 1 rows:
    [75]
Expected 1 rows:
    [100]


2017-07-13 01:43:32 INFO Life cycle stopping...

Results :

Failed tests: 
  TestRaptorIntegrationSmokeTestBucketed>TestRaptorIntegrationSmokeTest.testCreateBucketedTable:350->AbstractTestQueryFramework.assertQuery:123 For query: 
 SELECT count(DISTINCT "$shard_uuid") FROM orders_bucketed
not equal
Actual 1 rows:
    [75]
Expected 1 rows:
    [100]


Tests run: 1668, Failures: 1, Errors: 0, Skipped: 0
```

**Comment by kokosing** [comment] 2018-03-07 06:15
Duplicate of #6434

**Closed by kokosing** 2018-03-07 06:15 UTC
Labels: raptor, tests
