### ISSUE TITLE
[native] AbstractTestNativeGeneralQueries.testUnionAllInsert fails often

### ISSUE THREAD

**Issue by majetideepak** [prestodb/presto#22300] opened 2024-03-22 15:04 UTC
[ERROR]   TestPrestoSparkNativeGeneralQueries>AbstractTestNativeGeneralQueries.testUnionAllInsert:1479->AbstractTestQueryFramework.assertQuery:164 For query: 
 SELECT * FROM tmp_presto_153bcbcdfb994f60b71c175ba9b5fa15
not equal
Expected rows (100 of 15000 missing rows shown, 45000 rows in total):

https://app.circleci.com/pipelines/github/prestodb/presto/13763/workflows/0af203f0-3dd4-4620-a155-d725c25204d2/jobs/53431

**Comment by rschlussel** [comment] 2024-03-22 15:50
I think this is a duplicate of https://github.com/prestodb/presto/issues/22275

**Closed by rschlussel** 2024-03-22 15:50 UTC
Labels: flaky-test
