### ISSUE TITLE
Add Drop Catalog SQL Syntax Implementation

### ISSUE THREAD

**Issue by Akanksha-kedia** [prestodb/presto#21208] opened 2023-10-22 11:09 UTC
Implementing DROP CATALOG SQL command in PrestoDB/Trino would require significant changes to the PrestoDB source code. Here's a high-level overview of what might be needed:

**Expected Behavior or Use Case:** Users should be able to drop catalogs using SQL commands, similar to how databases and schemas are managed in traditional SQL databases.

**Presto Component, Service, or Connector**: This would primarily affect the PrestoDB server and all connectors, as they would need to be able to dynamically unload at runtime.

**Possible Implementation:**

- Extend the parser to recognize DROP CATALOG SQL command.
- Add new methods to the Metadata interface and its implementations to handle the deletion of catalogs.
- Modify the CatalogManager to allow for the dynamic removal of catalogs.
- Each connector might need to be updated to handle being unloaded at runtime.

**Context**: This feature could be useful in environments where catalogs need to be dynamically managed. For instance, in a testing environment, catalogs may need to be created and dropped frequently. Also, in a multi-tenant environment, if a tenant no longer needs access to a particular data source, the corresponding catalog could be dropped without affecting other tenants.

**Comment by tdcmeehan** [comment] 2023-10-23 19:36
Duplicate of #12605 and #14964--please feel free to open a new issue concretely describing how to achieve this feature.

**Closed by tdcmeehan** 2023-10-23 19:36 UTC
Labels: feature request
