### ISSUE TITLE
UnknownHostException With Presto Query Hudi Table

### ISSUE THREAD

**Issue by zhiyuan192shine** [prestodb/presto#16598] opened 2021-08-12 06:59 UTC
When HA is enabled on the NameNode, an UnknownHostException: nameservice1 occurs when Presto query the Hudi table。But querying Hive table is normal。

PrestoDB Version：0.258
Hudi Version：0.9

hive.properties

> connector.name=hive-hadoop2
hive.metastore.uri=thrift://xxxx.glprop.com:9083
hive.config.resources=/etc/hadoop/conf/hdfs-site.xml,/etc/hadoop/conf/core-site.xml
hive.metastore.authentication.type=KERBEROS
hive.metastore.service.principal=hive/_HOST@GLPROP.COM
hive.metastore.client.principal=bigdata@GLPROP.COM
hive.metastore.client.keytab=/etc/security/keytab/bigdata.keytab
hive.hdfs.authentication.type=KERBEROS
hive.hdfs.presto.principal=bigdata@GLPROP.COM
hive.hdfs.presto.keytab=/etc/security/keytab/bigdata.keytab

Exception:
2021-08-12T14:37:43.410+0800    ERROR   hive-hive-1     org.apache.hudi.hadoop.HoodieROTablePathFilter  Error checking path :hdfs://nameservice1/hudi/ods_inout_record_cow/20210809/.hoodie_partition_metadata, under folder: null
java.lang.IllegalArgumentException: java.net.UnknownHostException: nameservice1
        at org.apache.hadoop.security.SecurityUtil.buildTokenService(SecurityUtil.java:378)
        at org.apache.hadoop.hdfs.NameNodeProxies.createNonHAProxy(NameNodeProxies.java:320)
        at org.apache.hadoop.hdfs.NameNodeProxies.createProxy(NameNodeProxies.java:176)
        at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:678)
        at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:619)
        at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:149)
        at org.apache.hadoop.fs.PrestoFileSystemCache.createFileSystem(PrestoFileSystemCache.java:149)
        at org.apache.hadoop.fs.PrestoFileSystemCache.getInternal(PrestoFileSystemCache.java:89)
        at org.apache.hadoop.fs.PrestoFileSystemCache.get(PrestoFileSystemCache.java:62)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
        at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
        at org.apache.hudi.hadoop.HoodieROTablePathFilter.accept(HoodieROTablePathFilter.java:106)
        at com.facebook.presto.hive.util.HiveFileIterator.lambda$getLocatedFileStatusRemoteIterator$0(HiveFileIterator.java:103)
        at com.google.common.collect.Iterators$5.computeNext(Iterators.java:639)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
        at com.facebook.presto.hive.util.HiveFileIterator.computeNext(HiveFileIterator.java:69)
        at com.facebook.presto.hive.util.HiveFileIterator.computeNext(HiveFileIterator.java:40)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
        at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1811)
        at java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:294)
        at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206)
        at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:161)
        at java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300)
        at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
        at com.facebook.presto.hive.BackgroundHiveSplitLoader.loadSplits(BackgroundHiveSplitLoader.java:195)
        at com.facebook.presto.hive.BackgroundHiveSplitLoader.access$300(BackgroundHiveSplitLoader.java:40)
        at com.facebook.presto.hive.BackgroundHiveSplitLoader$HiveSplitLoaderTask.process(BackgroundHiveSplitLoader.java:121)
        at com.facebook.presto.hive.util.ResumableTasks.safeProcessTask(ResumableTasks.java:47)
        at com.facebook.presto.hive.util.ResumableTasks.access$000(ResumableTasks.java:20)
        at com.facebook.presto.hive.util.ResumableTasks$1.run(ResumableTasks.java:35)
        at com.facebook.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:78)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.UnknownHostException: nameservice1
        ... 36 more

**Comment by rohanpednekar** [comment] 2021-08-12 23:53
@imjalpreet Do you think you check this issue?

**Comment by imjalpreet** [comment] 2021-08-13 01:29
@zhiyuan192shine I am currently working on a fix which I faced while reading HUDI tables in S3 but I think the root cause might be the same. I will soon be raising a PR and will tag you in that so that you can try that patch and test again to see if it solves your issue.

**Comment by imjalpreet** [comment] 2021-08-13 01:35
@zhiyuan192shine I also wanted to add that currently Presto has a complete support for HUDI 0.5.3 and there is ongoing work for supporting HUDI 0.7.0 and 0.8.0. So, until Presto supports HUDI 0.9.0 there might be certain changes/features in HUDI which are not supported in Presto yet. Just wanted to let you know so that you don't face any issues later on.

**Comment by imjalpreet** [comment] 2021-08-15 23:04
@zhiyuan192shine I have raised a PR #16611, you can test the change by applying that patch and trying to read HUDI table after that.

**Comment by liuyuanzhi-cn** [comment] 2021-08-24 03:43
@zhiyuan192shine 问题解决了吗，我也遇到类似的问题。https://github.com/prestodb/presto/issues/16637

**Comment by liuyuanzhi-cn** [comment] 2021-08-24 05:47
> @zhiyuan192shine I have raised a PR #16611, you can test the change by applying that patch and trying to read HUDI table after that.

I also encountered a similar problem, but the error report is not the same  https://github.com/prestodb/presto/issues/16637

**Comment by imjalpreet** [comment] 2021-08-24 06:21
@liuyuanzhi-cn On first look, it doesn't look to be because of the same issue. Since this issue only exists in case Kerberos is enabled in the case of hdfs. But I assume in your case Kerberos is not enabled. Please correct me if I am wrong.

**Comment by liuyuanzhi-cn** [comment] 2021-08-24 06:35
> @liuyuanzhi-cn On first look, it doesn't look to be because of the same issue. Since this issue only exists in case Kerberos is enabled in the case of hdfs. But I assume in your case Kerberos is not enabled. Please correct me if I am wrong.

Yes, I did not configure Kerberos in my issue.

**Comment by Ayan07** [comment] 2021-08-24 12:11
@imjalpreet I'm also getting a similar issue while trying to query Hudi table from presto. I have my presto cluster and Hive metastore service running on Kubernetes.


Exception:

org.apache.hudi.hadoop.HoodieROTablePathFilter	Error checking path :s3a://dp-ingestion-stage/hudi/stagenew/kubernetes-mysql.integrationtesting.dummy/.hoodie, under folder: null
java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2197)
	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2654)
	at org.apache.hadoop.fs.PrestoFileSystemCache.createFileSystem(PrestoFileSystemCache.java:144)
	at org.apache.hadoop.fs.PrestoFileSystemCache.getInternal(PrestoFileSystemCache.java:103)
	at org.apache.hadoop.fs.PrestoFileSystemCache.get(PrestoFileSystemCache.java:62)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
	at org.apache.hudi.hadoop.HoodieROTablePathFilter.accept(HoodieROTablePathFilter.java:106)
	at com.facebook.presto.hive.util.HiveFileIterator.lambda$getLocatedFileStatusRemoteIterator$0(HiveFileIterator.java:103)
	at com.google.common.collect.Iterators$5.computeNext(Iterators.java:639)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
	at com.facebook.presto.hive.util.HiveFileIterator.computeNext(HiveFileIterator.java:69)
	at com.facebook.presto.hive.util.HiveFileIterator.computeNext(HiveFileIterator.java:40)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1811)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:295)
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:207)
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:162)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:301)
	at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
	at com.facebook.presto.hive.BackgroundHiveSplitLoader.loadSplits(BackgroundHiveSplitLoader.java:195)
	at com.facebook.presto.hive.BackgroundHiveSplitLoader.access$300(BackgroundHiveSplitLoader.java:40)
	at com.facebook.presto.hive.BackgroundHiveSplitLoader$HiveSplitLoaderTask.process(BackgroundHiveSplitLoader.java:121)
	at com.facebook.presto.hive.util.ResumableTasks.safeProcessTask(ResumableTasks.java:47)
	at com.facebook.presto.hive.util.ResumableTasks.access$000(ResumableTasks.java:20)
	at com.facebook.presto.hive.util.ResumableTasks$1.run(ResumableTasks.java:35)
	at com.facebook.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	

But in my case , it is additionally saying that 'org.apache.hadoop.fs.s3a.S3AFileSystem not found'. 
Do you have any idea on this issue?

**Comment by imjalpreet** [comment] 2021-08-24 12:23
@Ayan07 Can you let me know how have you configured S3 access?

**Comment by Ayan07** [comment] 2021-08-24 13:13
@imjalpreet  yes I have mentioned the keys in the hive.properties file which is mounted as a catalog.
hive.properties :
          connector.name: hive-hadoop2    
          hive.metastore.uri: thrift://metastore:9083
          hive.metastore.authentication.type: NONE
          hive.s3.use-instance-credentials: "false"
          hive.s3.aws-access-key: aws-access-key
          hive.s3.aws-secret-key: aws-secret-key
          hive.s3.path-style-access: "true"
          hive.allow-drop-table: "true"
          hive.max-partitions-per-scan: "1000000"

**Comment by imjalpreet** [comment] 2021-08-24 13:33
@Ayan07 Just to confirm, you are able to access non-hudi tables successfully right?

If yes, PR #16611 should resolve the issue you are facing as well. You can try applying the patch from that PR on your presto distribution or you can wait till that gets merged and then try accessing your table again.

**Comment by Ayan07** [comment] 2021-08-24 15:15
@imjalpreet for non-hudi tables, I'm not getting the exception, but while querying those tables I'm not able to fetch any records.

**Comment by imjalpreet** [comment] 2021-08-25 06:55
@Ayan07 If everything else is properly set-up, the HUDI issue should get resolved by the PR I mentioned earlier. I will need some more details to understand what's happening in the case of non-hudi tables since it's not related to this issue. You can reach out on PrestoDB Slack.

**Comment by Ayan07** [comment] 2021-08-25 07:00
@imjalpreet Okay, thanks.

**Closed** 2021-09-13 14:39 UTC
Labels: hudi

**Comment by rubenssoto** [comment] 2021-09-13 17:36
@imjalpreet thank you so much for fixing this issue, I will compile the master branch and give a try

**Comment by rubenssoto** [comment] 2021-09-13 19:19
@imjalpreet I dont if I did something wrong...

I get the latest Presto release 0.260.1, compile presto from master and only changed the jar presto-hive.jar on release 0.260.1.

After that I tried to use presto and I got the error:

`java.lang.NoSuchMethodError: com.facebook.presto.hive.HiveFileInfo.getFileModifiedTime()J
	at com.facebook.presto.hive.util.InternalHiveSplitFactory.createInternalHiveSplit(InternalHiveSplitFactory.java:108)
	at com.facebook.presto.hive.util.InternalHiveSplitFactory.createInternalHiveSplit(InternalHiveSplitFactory.java:89)
	at com.facebook.presto.hive.StoragePartitionLoader.lambda$createInternalHiveSplitIterator$3(StoragePartitionLoader.java:330)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:295)
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:207)
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:162)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:301)
	at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
	at com.facebook.presto.hive.BackgroundHiveSplitLoader.loadSplits(BackgroundHiveSplitLoader.java:195)
	at com.facebook.presto.hive.BackgroundHiveSplitLoader.access$300(BackgroundHiveSplitLoader.java:40)
	at com.facebook.presto.hive.BackgroundHiveSplitLoader$HiveSplitLoaderTask.process(BackgroundHiveSplitLoader.java:121)
	at com.facebook.presto.hive.util.ResumableTasks.safeProcessTask(ResumableTasks.java:47)
	at com.facebook.presto.hive.util.ResumableTasks.access$000(ResumableTasks.java:20)
	at com.facebook.presto.hive.util.ResumableTasks$1.run(ResumableTasks.java:35)
	at com.facebook.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by imjalpreet** [comment] 2021-09-13 20:51
> @imjalpreet I dont if I did something wrong...
> 
> I get the latest Presto release 0.260.1, compile presto from master and only changed the jar presto-hive.jar on release 0.260.1.

@rubenssoto You are facing this because there have been other changes as well in presto-hive in master which expect compatible classes from other presto plugins which are present in master but might not be present in 0.260.1, for eg. in this case the class HiveFileInfo from presto-hive-common plugin has updated and has a new method getFileModifiedTime which doesn't exist in 0.260.1 

Either you can try using master directly or you can checkout 0.260.1 tag/branch and cherry-pick the commit which contains the fix, build presto-hive and replace with that in your cluster. These two options would be the easiest in your case.
