### ISSUE TITLE
[Native] Not returning all the rows if timezone was part of the timestamp (against velox)

### ISSUE THREAD

**Issue by mknegi** [prestodb/presto#21188] opened 2023-10-19 06:39 UTC
## Current Behavior

**Velox Output**
```
SELECT x FROM (values TIMESTAMP '1970-01-01 00:01:00+00:00', TIMESTAMP '1970-01-01 08:01:00+08:00', TIMESTAMP '1970-01-01 00:01:00+08:00') t(x) WHERE x IN (TIMESTAMP '1970-01-01 00:01:00+00:00');
       x
-----------------------------
 1970-01-01 00:01:00.000 UTC
(1 row)
```

**Java Output**
```
SELECT x FROM (values TIMESTAMP '1970-01-01 00:01:00+00:00', TIMESTAMP '1970-01-01 08:01:00+08:00', TIMESTAMP '1970-01-01 00:01:00+08:00') t(x) WHERE x IN (TIMESTAMP '1970-01-01 00:01:00+00:00');
        x
--------------------------------
 1970-01-01 00:01:00.000 UTC
 1970-01-01 08:01:00.000 +08:00
(2 rows)
```

Seems like the issue is only there if timezone is part of the timestamp.

**Comment by yiweiHeOSS** [comment] 2023-10-27 23:38
Hi @mknegi . The where clause only has one value `WHERE x IN (TIMESTAMP '1970-01-01 00:01:00+00:00')`. Why the Java Output have two values.  Isn't it right that we only return one value `1970-01-01 00:01:00.000 UTC` (or `1970-01-01 00:01:00+00:00`, which I think are the same value)

**Comment by mknegi** [comment] 2023-10-31 04:52
@yiweiHeOSS - timestamp 1970-01-01 08:01:00.000 +08:00 is effectively 1970-01-01 00:01:00.000 because this timestamp was supplied with timezone which is 08 hours ahead of UTC therefore the query with a predicate WHERE x IN (TIMESTAMP '1970-01-01 00:01:00+00:00') should return this timestamp twice because this timestamp was effectively there twice in the values.

**Comment by yiweiHeOSS** [comment] 2023-11-02 23:05
I can find the testcases for TimestampWithTimezone inside the DateTimeFunctionsTest.cpp. The test did some simple conversions of TimestampWithTimezone, e.g. from timestamp to hours, according to the time zone:
```
TEST_F(DateTimeFunctionsTest, hourTimestampWithTimezone) {
  EXPECT_EQ(
      20,
      evaluateWithTimestampWithTimezone<int64_t>(
          "hour(c0)", 998423705000, "+01:00"));
  EXPECT_EQ(
      12,
      evaluateWithTimestampWithTimezone<int64_t>(
          "hour(c0)", 41028000, "+01:00"));
  EXPECT_EQ(
      13,
      evaluateWithTimestampWithTimezone<int64_t>(
          "hour(c0)", 41028000, "+02:00"));
...
```
Not sure if these tests can cover the case.

**Comment by yiweiHeOSS** [comment] 2023-11-06 20:54
I did some experiments about it. I tried the below commands with velox worker. What are the correct commands to create a table with a column type TIMESTAMP WITH TIME ZONE and insert data? @mknegi 
```
presto:tpch> create table t1 (C1 TIMESTAMP);
CREATE TABLE

presto:tpch> insert into t1 values(TIMESTAMP '1970-01-01 00:01:00+00:00');
Query 20231106_203224_00012_fpybc failed: line 1:23: Mismatch at column 1: 'c1' is of type timestamp but expression is of type timestamp with time zone
insert into t1 values(TIMESTAMP '1970-01-01 00:01:00+00:00')

presto:tpch> insert into t1 values(TIMESTAMP WITH TIME ZONE '1970-01-01 00:01:00+00:00');
Query 20231106_203447_00013_fpybc failed: line 1:23: mismatched input 'TIMESTAMP WITH TIME ZONE'. Expecting: <expression>
insert into t1 values(TIMESTAMP WITH TIME ZONE '1970-01-01 00:01:00+00:00')

presto:tpch> create table t2 (C1 TIMESTAMP WITH TIME ZONE);
Query 20231106_204116_00017_fpybc failed: No default Hive type provided for unsupported Hive type: timestamp with time zone
```

**Comment by yiweiHeOSS** [comment] 2023-11-07 00:53
From the plan, it looks like we didn't do the conversion of the second value well `(TIMESTAMP WITH TIME ZONE'245761320')`. It is 8 hours ahead.
```
presto:tpch> explain SELECT x FROM (values TIMESTAMP '1970-01-01 00:01:00+00:00', TIMESTAMP '1970-01-01 08:01:00+08:00', TIMESTAMP '1970-01-01 00:01:00+08:00') t(x) WHERE x IN (TIMESTAMP '1970-01-01 00:01:00+00:00');
                                                     Query Plan                                                      
---------------------------------------------------------------------------------------------------------------------
 - Output[x] => [field:timestamp with time zone]                                                                     
         Estimates: {rows: 1 (9B), cpu: 54.00, memory: 0.00, network: 0.00}                                          
         x := field (1:16)                                                                                           
     - Filter[filterPredicate = (field) = (TIMESTAMP WITH TIME ZONE'245760000')] => [field:timestamp with time zone] 
             Estimates: {rows: 1 (9B), cpu: 54.00, memory: 0.00, network: 0.00}                                      
         - LocalExchange[ROUND_ROBIN] () => [field:timestamp with time zone]                                         
                 Estimates: {rows: 3 (27B), cpu: 27.00, memory: 0.00, network: 0.00}                                 
             - Values => [field:timestamp with time zone]                                                            
                     Estimates: {rows: 3 (27B), cpu: 0.00, memory: 0.00, network: 0.00}                              
                     (TIMESTAMP WITH TIME ZONE'245760000')                                                           
                     (TIMESTAMP WITH TIME ZONE'245761320')                                                           
                     (TIMESTAMP WITH TIME ZONE'-117719038680')    
```

**Comment by mknegi** [comment] 2023-11-07 05:18
@yiweiHeOSS - you tried to create the table using hive connector but it doesn't support timestamp with timezone type. You should either use the original query that built the table on coordinator by using the values clause  or use a connector that supports timestamp with time zone type.

**Comment by yiweiHeOSS** [comment] 2023-11-07 23:33
I think I found where the problem is. The code is doing the conversion of the timezone twice. 
I ran the debugger in the code toGMTMillis() in Comparisons.h below. The value of parameter timestampWithTimezone is already converted to the UTC time, e.g. '1970-01-01 08:01:00+08:00' is already converted to '1970-01-01 00:01:00'. But in the toGMTMillis(), we did that conversion again in the `inputTimeStamp.toGMT(timezone);`. In this case, it will subtract 16 hours from its original timestamp. 
```
  // Convert TimestampWithTimezone from original timezone to GMT in milliseconds
  FOLLY_ALWAYS_INLINE
  int64_t toGMTMillis(
      const arg_type<TimestampWithTimezone>& timestampWithTimezone) {
    const int64_t milliseconds = *timestampWithTimezone.template at<0>();
    const int16_t timezone = *timestampWithTimezone.template at<1>();
    Timestamp inputTimeStamp = Timestamp::fromMillis(milliseconds);
    inputTimeStamp.toGMT(timezone);
    return inputTimeStamp.toMillis();
  }
```

**Comment by yiweiHeOSS** [comment] 2023-11-09 00:35
Hi, @JasmineWeii . I saw the change in Comparisons.h was made by you 5 months ago. Do you have any insight about this issue?

**Comment by aditi-pandit** [comment] 2023-11-14 21:02
@yiweiHeOSS : Did the code work before the changes in Comparisons.h ? Or was this added later based on Comparisons.h ? Based on that we should fix the problem.

**Comment by yiweiHeOSS** [comment] 2023-11-14 23:01
> @yiweiHeOSS : Did the code work before the changes in Comparisons.h ? Or was this added later based on Comparisons.h ? Based on that we should fix the problem.

@aditi-pandit  I can try to find a build before the changes in Comparisons.h and see if the problem disappears.

**Comment by yiweiHeOSS** [comment] 2023-11-15 23:05
If I commented out the `inputTimeStamp.toGMT(timezone);` inside the toGMTMillis(), the query can run successfully. This proved my [assumption](https://github.com/prestodb/presto/issues/21188#issuecomment-1800419177). cc @aditi-pandit
```
  // Convert TimestampWithTimezone from original timezone to GMT in milliseconds
  FOLLY_ALWAYS_INLINE
  int64_t toGMTMillis(
      const arg_type<TimestampWithTimezone>& timestampWithTimezone) {
    const int64_t milliseconds = *timestampWithTimezone.template at<0>();
    const int16_t timezone = *timestampWithTimezone.template at<1>();
    Timestamp inputTimeStamp = Timestamp::fromMillis(milliseconds);
    // inputTimeStamp.toGMT(timezone);
    return inputTimeStamp.toMillis();
  }
```

**Comment by yiweiHeOSS** [comment] 2023-11-29 21:07
I found the description of the VALUES syntax to define a literal inline table https://prestodb.io/docs/current/sql/values.html
I guess the code already did the conversion when it read the data and create a table using the `(values TIMESTAMP '1970-01-01 00:01:00+00:00', TIMESTAMP '1970-01-01 08:01:00+08:00', TIMESTAMP '1970-01-01 00:01:00+08:00') t(x)`
I am unsure if we should do the conversion during that time since the `toGMTMillis()` will do it again later.
Does anyone know the code path of reading data and creating a table using VALUES syntax like the above? Maybe there is something wrong there, I can compare it with the Java worker code.
cc: @aditi-pandit @czentgr @ashokku2022 @svm1

**Comment by czentgr** [comment] 2024-01-29 19:54
The literals are already created on the Java coordinator. They are not converted by the worker. That means it is expected to have the correct type and data as expected.
In this case Timestamp with Timezone is expected to have the timestamp portion in UTC with the associated timezone. This is also mentioned in the header for the type
```
/// Represents timestamp with time zone as a number of milliseconds since epoch
/// and time zone ID.
class TimestampWithTimeZoneType : public RowType {
  TimestampWithTimeZoneType()
      : RowType({"timestamp", "timezone"}, {BIGINT(), SMALLINT()}) {}
```

So when the comparison function is presented with values of this type the timestamp portion should already be in UTC and no more conversion to UTC is necessary. Which is exactly what you are observing.

The values plan node of the presto plan is converted into the Velox equivalent in Prestissimo. The actual value for the type is processed in
```
std::shared_ptr<const core::ValuesNode>
VeloxQueryPlanConverterBase::toVeloxQueryPlan(
    const std::shared_ptr<const protocol::ValuesNode>& node,
    const std::shared_ptr<protocol::TableWriteInfo>& /* tableWriteInfo */,
    const protocol::TaskId& taskId) {
```

where the constant expression value is read from what was sent by the coordinator.

The conversion occurs:
```
TypedExprPtr VeloxExprConverter::toVeloxExpr(
    std::shared_ptr<protocol::RowExpression> pexpr) const {
  if (auto call = std::dynamic_pointer_cast<protocol::CallExpression>(pexpr)) {
    return toVeloxExpr(*call);
  }
  if (auto constant =
          std::dynamic_pointer_cast<protocol::ConstantExpression>(pexpr)) {
    return toVeloxExpr(constant);   <<< data is read as timestamp with timezone
  }
...
```

The result is that the coordinator sends the following:
```
SELECT x FROM (values TIMESTAMP '1970-01-01 00:01:00+00:00', TIMESTAMP '1970-01-01 08:01:00+08:00') t(x);
```
This is a row type and so the first column is the timestamp portion and the second column the timezone id:
```
TS w/TZ: 
```
row 1:  [col0] 60 [col1] 0
row 3: [col0] 60 [col1] 1320
```

Therefore, as mentioned before, the equality check should not perform an adjustment of the timestamp portion to the timezone by calling `toGMTMillis`. I believe there is some confusion originally as to how the Timestamp with timezone type has data represented.
I believe this to be a bug. Without the original authors thoughts on the issue we must conclude the equality check is incorrect based on the data and handling of the type generally.

The query
```
SELECT x FROM (values TIMESTAMP '1970-01-01 00:01:00+00:00', TIMESTAMP '1970-01-01 08:01:00+08:00') t(x);
```
has matching output when using the Java worker and Prestissimo worker.

**Comment by aditi-pandit** [comment] 2024-02-23 00:14
Presto co-ordinator sends below plan to worker. Rightly, the timestamps are converted on the co-ordinator itself.

```
presto> explain SELECT x FROM (values TIMESTAMP '1970-01-01 00:01:00+00:00', TIMESTAMP '1970-01-01 09:01:00+09:00', TIMESTAMP '1970-01-01 00:01:00+08:00') t(x) WHERE x IN (TIMESTAMP '1970-01-01 00:01:00+00:00');
                                                     Query Plan                                                      
---------------------------------------------------------------------------------------------------------------------
 - Output[x] => [field:timestamp with time zone]                                                                     
         Estimates: {rows: 1 (9B), cpu: 54.00, memory: 0.00, network: 0.00}                                          
         x := field (1:16)                                                                                           
     - Filter[filterPredicate = (field) = (TIMESTAMP WITH TIME ZONE'245760000')] => [field:timestamp with time zone] 
             Estimates: {rows: 1 (9B), cpu: 54.00, memory: 0.00, network: 0.00}                                      
         - LocalExchange[ROUND_ROBIN] () => [field:timestamp with time zone]                                         
                 Estimates: {rows: 3 (27B), cpu: 27.00, memory: 0.00, network: 0.00}                                 
             - Values => [field:timestamp with time zone]                                                            
                     Estimates: {rows: 3 (27B), cpu: 0.00, memory: 0.00, network: 0.00}                              
                     **(TIMESTAMP WITH TIME ZONE'245760000')                                                           
                     (TIMESTAMP WITH TIME ZONE'245761380')                                                           
                     (TIMESTAMP WITH TIME ZONE'-117719038680')**   
```

The constant block read from Prestissimo to Velox also correctly populates the ms and timezone parts correctly.

TimestampToTimezone Java code is also simply unpacking the Ms value for each operation https://github.com/prestodb/presto/blob/master/presto-main/src/main/java/com/facebook/presto/type/TimestampWithTimeZoneOperators.java#L69 and there isn't a timezone conversion.

Velox code for non-timezone types does a timezone conversion based on config [adjust_session_timestamp_to_timezone](https://github.com/facebookincubator/velox/blob/main/velox/core/QueryConfig.h#L76). But that is not applicable here.

**Comment by aditi-pandit** [comment] 2024-02-23 00:15
@kagamiori, @Yuhta , @mbasmanova : Wdyt ?

**Comment by czentgr** [comment] 2024-03-04 18:14
Change got merged. Closing.

**Closed by czentgr** 2024-03-04 18:14 UTC
Labels: bug, tests, prestissimo, P0
