### ISSUE TITLE
If the URL contains unescaped characters,  url_extract_path function returns null

### ISSUE THREAD

**Issue by Akanksha-kedia** [prestodb/presto#21564] opened 2023-12-18 12:28 UTC
## Describe the problem you faced
<img width="943" alt="Screenshot 2023-12-18 at 5 38 10 PM" src="https://github.com/prestodb/presto/assets/89628774/476fb755-f423-402c-ab9a-e7b3dd183b98">

* A clear and concise description of the problem.
* Was this working before or is this a first try?
* If this worked before, then what has changed that recently?  
* Provide table DDLs and `` EXPLAIN ANALYZE `` for your Presto queries.

## Environment Description

* Presto version used: 0.286
* Storage (HDFS/S3/GCS..):  general
* Data source and connectors or catalogs used: no connector
* Deployment (Cloud or On-prem): on prem
* [Pastebin](https://pastebin.com/) link to the complete debug logs:

## Steps To Reproduce
 If an URL contains the characters <> [] or | like in the following url:
https://www.example.com/de/test.jsp{
The function returns null.

This seems not to be entirely true, since we are seeing that browser are using such unescaped chars in URLs. And it seems also be allowed by the spec in https://datatracker.ietf.org/doc/html/rfc2396.html#section-2.4.3 which defined explicit some characters which can be left unescaped.

Thanks in advance!

<img width="943" alt="Screenshot 2023-12-18 at 5 38 10 PM" src="https://github.com/prestodb/presto/assets/89628774/085cc46a-fc83-4b41-938e-3f1fec0b7c89">

## Expected behavior

Not null as output

## Additional context

Trino also has similar behaviour

## Stacktrace

NULL

Postgresql :
postgres=# CREATE OR REPLACE FUNCTION url_extract_path(url TEXT)
RETURNS TEXT AS $$
DECLARE
  path TEXT;
BEGIN
  SELECT (regexp_matches(url, 'https?://[^/]+/(.*)$'))[1] INTO path;
  RETURN path;
END;
$$ LANGUAGE plpgsql;
CREATE FUNCTION
postgres=# SELECT url_extract_path('https://www.example.com/de/test.jsp{');
 url_extract_path
------------------
 de/test.jsp{
(1 row)

mYSQL :mysql> CREATE FUNCTION url_extract_path(url TEXT)
    -> RETURNS TEXT
    -> DETERMINISTIC
    -> BEGIN
    ->   DECLARE path TEXT;
    ->   SET path = SUBSTRING_INDEX(SUBSTRING_INDEX(url, '://', -1), '/', 1);
    ->   RETURN path;
    -> END//
Query OK, 0 rows affected (0.01 sec)

mysql>
mysql> DELIMITER ;
mysql> SELECT url_extract_path('https://www.example.com/de/test.jsp{')
    -> ;
+----------------------------------------------------------+
| url_extract_path('https://www.example.com/de/test.jsp{') |
+----------------------------------------------------------+
| www.example.com                                          |
+----------------------------------------------------------+
1 row in set (0.00 sec)

Trino and prestodb :
<img width="1422" alt="Screenshot 2023-12-18 at 5 57 46 PM" src="https://github.com/prestodb/presto/assets/89628774/9fabe414-1e6f-4d9c-a014-6d9a41f300a1">

**Comment by karadyauran** [comment] 2023-12-21 18:22
I can try to solve this problem! Am I right that the method should ignore the characters <> [] or | in URL?

**Comment by tdcmeehan** [comment] 2023-12-21 18:58
Some of this is copied from trinodb/trino#20154.

After reading https://datatracker.ietf.org/doc/html/rfc2396.html#section-2.4.3, I see `}` as being explicitly called out as excluded.  It is mentioned in 2.4.3 *why* that character is excluded.  So I think the behavior is fine.  Regarding the example and how that works in-browser, I think it's because the browser is escaping that character after it's into the address bar.

Currently, this function returns NULL because there is no valid path element (it's not a valid URI).  NULL seems appropriate given that the given string isn't even a URI per the spec.  

I understand this is not convenient given the messy reality of data.  However, we do have an `url_encode` method which can fix this up for the user:

```
presto:tiny> SELECT url_extract_path(url_encode('https://www.example.com/de/test.jsp{'));
                _col0                 
--------------------------------------
 https://www.example.com/de/test.jsp{ 
(1 row)

Query 20231221_185436_00003_wpyhh, FINISHED, 1 node
Splits: 5 total, 5 done (100.00%)
[Latency: client-side: 0:01, server-side: 0:01] [0 rows, 0B] [0 rows/s, 0B/s]
```

If NULLs are not convenient if the URI is invalid, we can fail the query if it encounters a null: 

```
presto:tiny> SELECT coalesce(url_extract_path('https://www.example.com/de/test.jsp{'), fail('invalid uri'));
```

Closing this because I think it's working as designed, but please reopen if you think I'm mistaken, thanks!

**Closed by tdcmeehan** 2023-12-21 18:58 UTC
Labels: bug, good first issue, usage
