### ISSUE TITLE
Max negative BIGINT value cannot be selected

### ISSUE THREAD

**Issue by santijampp** [prestodb/presto#9102] opened 2017-10-05 14:46 UTC
According to Presto's documentation, BIGINTS are:
```
A 64-bit signed two’s complement integer with a minimum value of -2^63 and a maximum value of 2^63 - 1.
```
Yet it breaks with `-2^63`.

Examples:
```
presto> select -9223372036854775808;
Query failed: line 1:1: Invalid numeric literal: 9223372036854775808
```

Also:
```
presto> select -9223372036854775807 - 1;
presto> select from_big_endian_64(from_hex('8000000000000000'));
```

Both fail with a huge strack trace which eventually results in:
```
Caused by: com.facebook.presto.sql.parser.ParsingException: line 1:1: Invalid numeric literal: 9223372036854775808
```

**Comment by electrum** [comment] 2017-10-05 15:20
Thanks for reporting. Duplicate of https://github.com/prestodb/presto/issues/4571

**Closed by electrum** 2017-10-05 15:20 UTC
