### ISSUE TITLE
[Native Execution] Build failure on MacOS when PRESTO_ENABLE_PARQUET=ON

### ISSUE THREAD

**Issue by majetideepak** [prestodb/presto#18261] opened 2022-08-31 15:54 UTC
The presto_server target build fails on MacOS with bunch of missing symbols when built with -DPRESTO_ENABLE_PARQUET=ON
```
bash$ PRESTO_ENABLE_PARQUET=ON make debug

.....
Undefined symbols for architecture x86_64:
  "apache::thrift::CodecConfig::__fbthrift_clear()", referenced from:
      apache::thrift::CodecConfig::~CodecConfig() in libpresto_thrift-cpp2.a(PrestoThriftAsyncClient.cpp.o)
      apache::thrift::CodecConfig::~CodecConfig() in libthriftcpp2.a(Cpp2Channel.cpp.o)
      apache::thrift::CodecConfig::~CodecConfig() in libthriftcpp2.a(RequestChannel.cpp.o)
      apache::thrift::CodecConfig::~CodecConfig() in libthriftcpp2.a(FramingHandler.cpp.o)
      apache::thrift::CodecConfig::~CodecConfig() in libthriftcpp2.a(RpcMetadataUtil.cpp.o)
  "apache::thrift::concurrency::Util::currentTimeTicks(long long)", referenced from:
      apache::thrift::concurrency::Util::currentTime() in libtransport.a(THttpParser.cpp.o)
  "apache::thrift::ContextStack::onReadData(apache::thrift::SerializedMessage const&)", referenced from:
      folly::exception_wrapper apache::thrift::detail::ac::recv_wrapped_helper<apache::thrift::BinaryProtocolReader, apache::thrift::ThriftPresult<true> >(apache::thrift::BinaryProtocolReader*, apache::thrift::ClientReceiveState&, apache::thrift::ThriftPresult<true>&) in libpresto_thrift-cpp2.a(PrestoThriftAsyncClient.cpp.o)
      folly::exception_wrapper apache::thrift::detail::ac::recv_wrapped_helper<apache::thrift::CompactProtocolReader, apache::thrift::ThriftPresult<true> >(apache::thrift::CompactProtocolReader*, apache::thrift::ClientReceiveState&, apache::thrift::ThriftPresult<true>&) in libpresto_thrift-cpp2.a(PrestoThriftAsyncClient.cpp.o)
.........
```

**Comment by mbasmanova** [comment] 2022-08-31 15:59
CC: @mshang816 @amitkdutta @spershin @gggrace14

**Comment by mbasmanova** [comment] 2022-08-31 16:00
@majetideepak Deepak, are there any particular steps to reproduce this failure? I'm able to build successfully.

**Comment by mbasmanova** [comment] 2022-08-31 16:01
@majetideepak Deepak, does this happen only when PRESTO_ENABLE_PARQUET=ON ? I don't have this setting. I'll try to enable it and build.

**Comment by majetideepak** [comment] 2022-08-31 16:04
@mbasmanova Yes, the build fails only when PRESTO_ENABLE_PARQUET=ON. I edited the description. Previously it was only in the title.

**Comment by majetideepak** [comment] 2022-08-31 16:08
Some observations
1) This seems to happen only on MacOS and not on Linux.
2) We have two thrift libraries, regular thrift (for Arrow) and FBThrift. Likely a conflict between both.
3) I tried to see if we can use only FBThrift for Arrow as well. Unfortunately, this does not work since Arrow checks in regular thrift-generated Parquet Thrift files.

**Comment by mshang816** [comment] 2022-08-31 17:08
> PRESTO_ENABLE_PARQUET=ON

I can take a look. So this should be reproduced like this: make -DPRESTO_ENABLE_PARQUET=ON debug  ?

**Comment by majetideepak** [comment] 2022-08-31 18:15
`PRESTO_ENABLE_PARQUET=ON make debug` should do.

**Comment by mshang816** [comment] 2022-09-01 01:30
> CodecConfig

it looks like I can reproduce the issue locally. I will take a look at the issue.

**Comment by uhyonc** [comment] 2022-10-06 21:20
Hi, I have the same problem as well. Can we get an update on this ticket? Thanks!

**Comment by mbasmanova** [comment] 2022-10-07 03:21
CC: @kgpai

**Comment by Mionsz** [comment] 2022-10-16 21:09
@mbasmanova @majetideepak Here is the partial fix: https://github.com/prestodb/presto/pull/18213/files

You need to add also on line `158` in `presto-native-execution/CMakeLists.txt` (after `find_library(RE2 re2)`):

```
find_library(RE2 re2)
find_package(FBTHRIFT)
include_directories(${FBTHRIFT_INCLUDE_DIR})
```

You could adopt in somehow as we are waiting for legal team to finish the CLA process so it still can take some time.

**Comment by majetideepak** [comment] 2022-10-17 20:07
@Mionsz this fix did not work for me on my MacOS. Did you see the same build error in the description?

**Comment by Mionsz** [comment] 2022-10-19 08:21
@majetideepak so now I see that we have some problems in building prestocpp - the latest version - so it is hard to tell if those are the same. 
It is worth mentioning that Velox now uses ThirdpartyToolchain.cmake file for folly installation and linking. This is not reflected in PrestoCpp. There are also some issues with Presto protocol translation to PrestoCpp.

**Comment by mbasmanova** [comment] 2022-10-31 10:48
@mshang816 Michael, is this something you could help look into?

CC: @kgpai

**Comment by Mionsz** [comment] 2022-11-08 11:03
@dingqiaoyi @majetideepak try using this PR https://github.com/prestodb/presto/pull/18572

**Comment by majetideepak** [comment] 2022-11-09 17:19
@Mionsz the build failure happens only on MacOS. I wrote this in one of my comments above. I clarified this in the title and in the description.

**Comment by markjin1990** [comment] 2023-01-27 21:40
> Yes I am aware -- try building Thrift part with `-std=c++11 -stdlib=libc++` instead of `-std=c++17 -stdlib=libstdc++`. It is possible that `-stdlib=libc++` could help.

Would you mind elaborating your proposed solution of "building Thrift part with -std=c++11 -stdlib=libc++"? Thanks!

**Comment by markjin1990** [comment] 2023-02-02 22:59
Hi, @majetideepak Did you finally figured out a solution for this problem? Both my colleagues and I encountered this problem recently.

**Comment by sungho-park-23** [comment] 2023-02-03 00:16
This worked for me:

```
make debug 
EXTRA_CMAKE_FLAGS="-DVELOX_BUILD_TESTING=ON
-DCMAKE_BUILD_TYPE=Debug
-DCMAKE_CXX_FLAGS=-isystem\
/usr/local/include
-DVELOX_CODEGEN_SUPPORT=ON
-DVELOX_ENABLE_PARQUET=ON
-DVELOX_ENABLE_HIVE_CONNECTOR=ON"
```

It fails when I remove "-DCMAKE_CXX_FLAGS=-isystem\
/usr/local/include"

**Comment by sungho-park-23** [comment] 2023-02-04 00:59
@majetideepak I am running into this issue as well, have you figured out a solution for this?

**Comment by Mionsz** [comment] 2023-02-04 01:16
Try instead of building fbthrift running this before the build starts:
```shell
sed -i '/^sudo --preserve-env apt install/a\  *thrift* \\' presto-native-execution/scripts/setup-macos.sh
```
so that it will be installed

**Comment by sungho-park-23** [comment] 2023-02-04 01:44
> Try instead of building fbthrift running this before the build starts:
> 
> ```shell
> sed -i '/^sudo --preserve-env apt install/a\  *thrift* \\' presto-native-execution/scripts/setup-macos.sh
> ```
> 
> so that it will be installed

This didn't work for me, I'm still getting the same error

**Comment by majetideepak** [comment] 2023-02-06 16:13
I am able to manually build `presto_server` by changing the link order of `thrift/libpresto_thrift-cpp2.a /usr/local/lib/libthriftcpp2.a`. I will spend more time this week on a proper fix.

**Comment by majetideepak** [comment] 2023-02-06 17:43
I have a fix here https://github.com/prestodb/presto/pull/19021. I am able to verify locally. Can someone else verify as well? Thanks.

**Comment by markjin1990** [comment] 2023-02-06 19:49
@majetideepak Thanks for providing the fix! This solves the problem on my side. @sungho-park-23 Please double check it.

**Closed** 2023-02-07 20:47 UTC
Labels: build
