### ISSUE TITLE
facing issue while building presto-docs  OSError: [Errno 20000] Unknown error: 20000: '/home/test/presto/presto-docs/target/html'

### ISSUE THREAD

**Issue by nareshk355** [prestodb/presto#3849] opened 2015-10-28 11:21 UTC
```
[ERROR]
[ERROR] Exception occurred:
[ERROR]   File "/root/.m2/repository/org/python/jython-standalone/2.5.2/jython-standalone-2.5.2.jar/Lib/os.py", line 158, in makedirs
[ERROR]     mkdir(name, mode)
[ERROR] OSError: [Errno 20000] Unknown error: 20000: '/home/test/presto/presto-docs/target/html'
[ERROR] The full traceback has been saved in /tmp/sphinx-err-r8XCy-.log, if you want to report the issue to the developers.
[ERROR] Please also report this if it was a user error, so that a better error message can be provided next time.
[ERROR] Either send bugs to the mailing list at <http://groups.google.com/group/sphinx-dev/>,
[ERROR] or report them in the tracker at <http://bitbucket.org/birkenfeld/sphinx/issues/>. Thanks!
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 42.709 s
[INFO] Finished at: 2015-10-28T16:45:41+05:30
[INFO] Final Memory: 36M/321M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.tomdz.maven:sphinx-maven-plugin:1.0.3:generate (default) on project presto-docs: Failed to run the report: Sphinx report generation failed -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

traceback log file

```
# Sphinx version: 1.1.3
# Python version: 2.5.2
# Docutils version: 0.9.1 release
# Jinja2 version: 2.6
Traceback (most recent call last):
  File "/home/test/presto/presto-docs/target/sphinx/sphinx/cmdline.py", line 189, in main
    app.build(force_all, filenames)
  File "/home/test/presto/presto-docs/target/sphinx/sphinx/application.py", line 200, in build
    self.builder.build_all()
  File "/home/test/presto/presto-docs/target/sphinx/sphinx/builders/__init__.py", line 159, in build_all
    self.build(None, summary='all source files', method='all')
  File "/home/test/presto/presto-docs/target/sphinx/sphinx/builders/__init__.py", line 252, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/test/presto/presto-docs/target/sphinx/sphinx/builders/__init__.py", line 292, in write
    self.write_doc(docname, doctree)
  File "/home/test/presto/presto-docs/target/sphinx/sphinx/builders/html.py", line 426, in write_doc
    self.handle_page(docname, ctx, event_arg=doctree)
  File "/home/test/presto/presto-docs/target/sphinx/sphinx/builders/html.py", line 738, in handle_page
    ensuredir(path.dirname(outfilename))
  File "/home/test/presto/presto-docs/target/sphinx/sphinx/util/osutil.py", line 55, in ensuredir
    os.makedirs(path)
  File "/root/.m2/repository/org/python/jython-standalone/2.5.2/jython-standalone-2.5.2.jar/Lib/os.py", line 158, in makedirs
    mkdir(name, mode)
OSError: [Errno 20000] Unknown error: 20000: '/home/test/presto/presto-docs/target/html'
```

please look into issue and help me to resove it

**Comment by electrum** [comment] 2015-10-28 20:26
It seems to be failing when trying to create the directory `/home/test/presto/presto-docs/target/html`. Can you do an `mvn clean` and try again?

**Comment by electrum** [comment] 2015-10-28 20:29
Also, please show the output of running `mvn -V clean`

**Comment by nareshk355** [comment] 2015-10-29 06:17
I have tried running mvn clean and all but still getting same errors.

and here is output of mvn -V

test@pts00449-vm4:~/presto/presto-docs$ mvn -V
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T17:27:37+05:30)
Maven home: /usr/local/apache-maven-3.3.3
Java version: 1.8.0_45-internal, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-ppc64el/jre
Default locale: en_IN, platform encoding: UTF-8
OS name: "linux", version: "3.19.0-15-generic", arch: "ppc64", family: "unix"
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.883 s
[INFO] Finished at: 2015-10-29T11:45:10+05:30
[INFO] Final Memory: 11M/109M
[INFO] ------------------------------------------------------------------------
[ERROR] No goals have been specified for this build. You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoGoalSpecifiedException

**Comment by electrum** [comment] 2015-10-29 06:43
It looks like you're running on ppc64. Presto only supports x86_64 on Linux (required for bundled Hadoop JNI libraries) and has many assumptions about the architecture being little endian.

This docs issue might be due to the JNI libraries from the Jython version used by the Maven Sphinx plugin. For now, I suggest you skip that module by removing it from the root pom.xml file.

**Comment by nareshk355** [comment] 2015-11-03 08:02
Hi electrum,

yes we are working on ppc64le, could you please let us the required libraries to build to build presto on ppc64le.

as suggested I skipped the presto-docs module and I was able to build the other components but test cases are getting failed for some components, I think those errors are related to missing JNI libraries.

**Comment by gerrith3** [comment] 2015-11-24 15:55
Hi IBM now has a program using its Power Development Program to allow any open source developer to use our ppc64le based cloud.  There is a little bit of overhead but there is no cost for open source development.

To start, register for the service here:  https://www-304.ibm.com/partnerworld/wps/ent/pdp/web/MyProgramAccess?registerosd 

 and then press the "Please register me as an Open Source Developer" link. 

Identify yourself as an Open Source developer and your project, then include the link to any defects you want to test to get your account open (e.g. this defect).  That should give you the ongoing ability to access VMs for open source development purposes.

**Comment by rschlussel** [comment] 2017-03-24 15:12
Duplicate of https://github.com/prestodb/presto/issues/3862

**Closed by rschlussel** 2017-03-24 15:12 UTC
