### ISSUE TITLE
Planning failure for count distinct on row type

### ISSUE THREAD

**Issue by martint** [prestodb/presto#7229] opened 2017-01-26 00:27 UTC
This query:

```sql
SELECT count(DISTINCT a), max(b)
FROM (VALUES (row(1, 2), 3)) t(a, b)
```

fails with:

```
java.lang.AssertionError: Number of parameters and fieldNames for ROW type doesn't match
	at com.facebook.presto.spi.type.TypeSignature.verify(TypeSignature.java:379)
	at com.facebook.presto.spi.type.TypeSignature.createNamedTypeParameters(TypeSignature.java:286)
	at com.facebook.presto.spi.type.TypeSignature.parseRowTypeSignature(TypeSignature.java:202)
	at com.facebook.presto.spi.type.TypeSignature.parseTypeSignature(TypeSignature.java:106)
	at com.facebook.presto.spi.type.TypeSignature.parseTypeSignature(TypeSignature.java:93)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitCast(ExpressionAnalyzer.java:955)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitCast(ExpressionAnalyzer.java:255)
	at com.facebook.presto.sql.tree.Cast.accept(Cast.java:98)
	at com.facebook.presto.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:26)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:274)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.coerceToSingleType(ExpressionAnalyzer.java:1181)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitIfExpression(ExpressionAnalyzer.java:466)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitIfExpression(ExpressionAnalyzer.java:255)
	at com.facebook.presto.sql.tree.IfExpression.accept(IfExpression.java:70)
	at com.facebook.presto.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:26)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:274)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyze(ExpressionAnalyzer.java:231)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyzeExpressions(ExpressionAnalyzer.java:1382)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyzeExpressionsWithSymbols(ExpressionAnalyzer.java:1335)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.getExpressionTypes(ExpressionAnalyzer.java:1301)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.getExpressionTypes(ExpressionAnalyzer.java:1289)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.getExpressionTypes(ExpressionAnalyzer.java:1277)
	at com.facebook.presto.sql.planner.optimizations.PropertyDerivations$Visitor.visitProject(PropertyDerivations.java:505)
	at com.facebook.presto.sql.planner.optimizations.PropertyDerivations$Visitor.visitProject(PropertyDerivations.java:124)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:92)
	at com.facebook.presto.sql.planner.optimizations.PropertyDerivations.deriveProperties(PropertyDerivations.java:110)
	at com.facebook.presto.sql.planner.optimizations.PropertyDerivations.deriveProperties(PropertyDerivations.java:105)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.deriveProperties(AddExchanges.java:1214)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.withDerivedProperties(AddExchanges.java:1209)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.rebaseAndDeriveProperties(AddExchanges.java:1196)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitProject(AddExchanges.java:242)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitProject(AddExchanges.java:199)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:92)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.planChild(AddExchanges.java:1191)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitAggregation(AddExchanges.java:287)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitAggregation(AddExchanges.java:199)
	at com.facebook.presto.sql.planner.plan.AggregationNode.accept(AggregationNode.java:206)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.planChild(AddExchanges.java:1191)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitOutput(AddExchanges.java:248)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitOutput(AddExchanges.java:199)
	at com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:82)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges.optimize(AddExchanges.java:149)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:120)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:111)
	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:297)
	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:276)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:234)
	at com.facebook.presto.execution.QueuedExecution.lambda$start$1(QueuedExecution.java:63)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

The query succeeds if the `max(b)` expression is removed from the select list.

**Comment by wenleix** [comment] 2017-02-03 19:35
The error will not occur if `optimizer.optimize-mixed-distinct-aggregations` is disabled. 

Related issue with mixed distinct aggregation (not same): https://github.com/prestodb/presto/issues/7214

**Comment by wenleix** [comment] 2017-02-03 20:41
This optimizer works fine if `a` is an integer. Here is a query and the logical plan:
```
presto> EXPLAIN SELECT count(DISTINCT a), max(b) FROM (VALUES (1, 3)) t(a, b);
                                                                                          Query Plan
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 - Output[_col0, _col1] => [count:bigint, max:integer]
         _col0 := count
         _col1 := max
     - Aggregate(FINAL) => [max:integer, count:bigint]
             max := "arbitrary"("arbitrary")
             count := "count"("count_15")
         - LocalExchange[SINGLE] () => count_15:bigint, arbitrary:bigint
             - Aggregate(PARTIAL) => [count_15:bigint, arbitrary:bigint]
                     count_15 := "count"("expr_13")
                     arbitrary := "arbitrary"("expr_14")
                 - Project[] => [expr_13:integer, expr_14:integer]
                         expr_13 := IF(("group" = CAST(1 AS bigint)), "field", CAST(null AS integer))
                         expr_14 := IF(("group" = CAST(0 AS bigint)), "max_12", CAST(null AS integer))
                     - Aggregate(FINAL)[field, group][$hashvalue] => [field:integer, group:bigint, $hashvalue:bigint, max_12:integer]
                             max_12 := "max"("max_16")
                         - LocalExchange[HASH][$hashvalue] ("field", "group") => field:integer, group:bigint, max_16:bigint, $hashvalue:bigint
                             - Aggregate(PARTIAL)[field, group][$hashvalue_17] => [field:integer, group:bigint, $hashvalue_17:bigint, max_16:bigint]
                                     max_16 := "max"("field_0")
                                 - Project[] => [field_0:integer, field:integer, group:bigint, $hashvalue_17:bigint]
                                         $hashvalue_17 := "combine_hash"("combine_hash"(BIGINT '0', COALESCE("$operator$hash_code"("field"), 0)), COALESCE("$operator$hash_code"("group"), 0))
                                     - GroupId[[field_0], [field]] => [field_0:integer, field:integer, group:bigint]
                                             field_0 := field_0
                                             field := field
                                         - LocalExchange[ROUND_ROBIN] () => field:integer, field_0:integer
                                             - Values => [field:integer, field_0:integer]
                                                     (1, 3)

(1 row)
```

It does the following:
- Compute `SELECT max(b) GROUP BY GROUPING SETS ((), (a))` 
- For each grouping tuple `(a, group_id, max_b)`:
  - Generate `(null, max_b)` if `group_id = 0`; this is a same behavior as normal grouping sets
  - Generate `(a, null)` if `group_id = 1`; basically it discards the `max(b)` computed for `GROUPING SET (a)`. 
- Compute `count(a), arbitrary(max_b)`. 

The high-level idea of this optimization is to use `GROUPING SET ()` to compute `MAX(b)`, while use `GROUPING SET (a)` to compute `COUNT(DISTINCT a)`.

**Comment by wenleix** [comment] 2017-02-03 22:37
The root cause if because `Type.getDisplayName` is used to generate `CAST IF` statement ([here](https://github.com/prestodb/presto/blob/8566cce62b03a793698168df430e4e150967e443/presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/OptimizeMixedDistinctAggregations.java#L444)]. This will put an extra space when it's a row type (e.g. `row(integer, integer)`)

**Comment by wenleix** [comment] 2017-02-10 21:24
Resolved by https://github.com/prestodb/presto/pull/7303

**Closed by wenleix** 2017-02-10 21:24 UTC
Labels: bug
