### ISSUE TITLE
Support for "skip.header.line.count" property for HIVE tables

### ISSUE THREAD

**Issue by damiencarol** [prestodb/presto#1848] opened 2014-10-22 09:04 UTC
We have text tables with skip.header.line.count property.

**Comment by Downchuck** [comment] 2016-01-27 21:13
I hit this as well.. Refreshing that it's an issue.

**Comment by jakovm** [comment] 2016-03-30 16:33
This is still an issue...

**Comment by maciejgrzybek** [comment] 2016-07-29 18:14
`skip.header.line.count` is available from metastore. Record cursor will have to skip lines according to that property. Some changes in `BackgroundHiveSplitLoader` and `ColumnarTextHiveRecordCursor` will be necessary.

**Comment by pletelli** [comment] 2017-03-16 15:33
No update on this issue ?

**Comment by dain** [comment] 2017-03-16 17:56
I would expect this to work for reading and writing to existing tables.  I don't think there is a way to set this property when creating new tables.

**Comment by d18s** [comment] 2017-03-21 15:05
👍

**Comment by dain** [comment] 2017-03-21 17:32
If this is still an issue, please reopen with specifics on how to reproduce the problem.

**Comment by rupesh1183** [comment] 2017-03-30 10:26
This is still an issue. Hive understands the skip.header.line property and skips header while reading. But presto displays the header record on querying the same table.

Example to reproduce the error:

Step 1: create a csv file with 2 columns including header record (having inserted few records),

Step 2: Create table in hive with following property TBLPROPERTIES("skip.header.line.count"="1");

Step3 : query (select *) the table in hive  --> Does not show header, furthermore as an added test, using the value(column header) in where clause produces no rows

Step 4: Query (select *) the table in presto --> Includes Header, furthermore as an added test,using the value(column header) in where clause returns the header record.

**Comment by chamal-sapumohotti** [comment] 2017-05-23 05:02
facing the same issue. running on AWS EMR with 
Hive = Hive 2.1.0
Presto =  Presto 0.157.1

**Comment by raja-sudhan** [comment] 2017-10-10 13:09
Is this issue solved since I am also encountering the same issue.

**Comment by LouisKottmann** [comment] 2017-10-17 10:17
We are experiencing the same issue, @dain is @rupesh1183 's specifics enough to reproduce the problem on your end?

**Comment by Micka33** [comment] 2017-10-17 12:10
Facing the same issue. Any progress since Oct 22, 2014 ?

**Comment by minion96** [comment] 2017-10-26 15:09
any other way around this?

**Comment by gseva** [comment] 2017-11-03 19:50
Still an issue.

**Comment by dylancis** [comment] 2017-11-22 16:21
same issue here

**Comment by robmurtagh** [comment] 2017-12-08 17:57
yeah, same issue here...

**Comment by rupeshmalladi** [comment] 2018-04-03 18:56
All - A related update : AWS has fixed this issue in 'Athena' which is AWS's version/product based on Presto.

**Comment by findepi** [comment] 2018-04-03 20:05
@rupeshmalladi any plans for AWS Athena to contribute this back?

**Comment by rupeshmalladi** [comment] 2018-04-05 15:19
@findepi Not that I am aware of!

**Comment by kokosing** [comment] 2018-04-13 10:13
Fixed with #10323

**Closed by kokosing** 2018-04-13 10:13 UTC
Labels: enhancement, intermediate-task

**Comment by cvandeve** [comment] 2018-05-21 13:39
Presto is still ignoring skip.header.line.count on latest cluster deployment from AWS (5.13) Presto 0.194 with Hadoop 2.8.3 HDFS and Hive 2.3.2

The "closing fix #10323" doesn't apply to this ticket. The linked ticket was closed for a reason that had nothing to do with Presto.

**Comment by findepi** [comment] 2018-05-21 13:52
@cvandeve the fix is available for since Presto 0.199 (https://prestodb.io/docs/current/release/release-0.199.html#hive-changes), while latest release is 0.201.

**Comment by cvandeve** [comment] 2018-05-21 14:53
Thanks @findepi
