### ISSUE TITLE
JDBC Driver: Method java.sql.DatabaseMetaData.getTables is not implemented

### ISSUE THREAD

**Issue by lucboudreau** [prestodb/presto#3075] opened 2015-06-11 13:38 UTC
Calling this method should return a ResultSet of the available tables.

http://docs.oracle.com/javase/7/docs/api/java/sql/DatabaseMetaData.html#getTables(java.lang.String,%20java.lang.String,%20java.lang.String,%20java.lang.String[])

As of now it returns no rows.

**Comment by electrum** [comment] 2015-06-15 19:02
This method is implemented and has a bunch of tests: https://github.com/facebook/presto/blob/master/presto-jdbc/src/test/java/com/facebook/presto/jdbc/TestDriver.java#L317

Can you provide more info on what is failing? Even better, can you reproduce it by adding a failing test?

**Comment by lucboudreau** [comment] 2015-06-15 19:04
Will do.

**Comment by damiencarol** [comment] 2015-06-16 03:39
It's related to #2687

**Comment by damiencarol** [comment] 2015-06-16 03:41
If we call Method java.sql.DatabaseMetaData.getTables() with table type filter at value "TABLE" (as Pentaho tools do) no rows are returned. Because Presto use value "BASE TABLE" which is wrong.

**Comment by rschlussel** [comment] 2017-03-24 17:32
closing as duplicate of #2687

**Closed by rschlussel** 2017-03-24 17:32 UTC
