### ISSUE TITLE
Implement FILTER clause for aggregations

### ISSUE THREAD

**Issue by cberner** [prestodb/presto#6327] opened 2016-10-11 21:16 UTC
For example, this query `select sum(x) filter (where x > 1), sum(x) from (values (1), (1), (2), (2)) t(x);` should return `4` and `6`

The SQL spec defines the FILTER clause as follow:
```
<aggregate function> ::=
COUNT <left paren> <asterisk> <right paren> [ <filter clause> ]
| <general set function> [ <filter clause> ]
| <binary set function> [ <filter clause> ]
| <ordered set function> [ <filter clause> ]
| <array aggregate function> [ <filter clause> ]
<filter clause> ::=
FILTER <left paren> WHERE <search condition> <right paren>
```

and in section 10.9.8: `A <filter clause> shall not contain a <query expression>, a <window function>, or an outer reference.`

and `If <filter clause> is specified, then the <search condition> is effectively evaluated for each row of T.
Let T1 be the collection of rows of T for which the result of the <search condition> is True.`

To implement this you'll first need to add the Antlr grammar to `SqlBase.g4`. Then take a look at `StatementAnalyzer.visitQuerySpecification` and how it handles aggregations. The actual planning will need to be done in `QueryPlanner.aggregate`. Take a look at how the "mask" functionality for distinct aggregations is done. This allows you to mask our rows, so that they're not considered for the aggregation. The plan should use a `ProjectNode` to compute a boolean value for the FILTER expression, and then use that Symbol as the mask for the aggregation.

You can add tests to `AbstractTestQueries` which can be run, most easily, from `TestLocalQueries`

**Comment by cberner** [comment] 2016-10-11 21:16
Li Ding is going to take a look at this

**Comment by martint** [comment] 2016-10-11 21:29
This is a duplicate of https://github.com/prestodb/presto/issues/5085.

**Closed by martint** 2016-10-11 21:29 UTC
Labels: duplicate
