### ISSUE TITLE
Presto insert doesn't work as expected for external hive table

### ISSUE THREAD

**Issue by jiajinyu** [prestodb/presto#10308] opened 2018-04-02 05:52 UTC
We have some external Hive tables. The insertion never worked as expected. 

The behavior is like this. 
1. The syntax `INSERT INTO table_name SELECT a, b, partition_name from T;`  will create many rows in `table_name` , but only `partition_name` is correctly inserted.  For every row, column `a` and `b` have `NULL`.

2. If I use the syntax, `INSERT INTO table_name VALUES (a, b, partition_name)`, then the syntax above^, for the same table, then both insertion work correctly. 

The presto version is 0.192.  As an ex-FB employee, I really like the performance and efficiency brought by Presto. Any suggestion on how to debug the issues will be appreciated. Thanks in advance.

**Comment by dain** [comment] 2018-04-02 20:34
Can you provide a more specific example?  I'm not really sure what the problem is.

**Comment by jiajinyu** [comment] 2018-04-03 10:20
Thanks @dain for the prompt response. Here is a concrete example. 

The table is created as 
``` sql
CREATE EXTERNAL TABLE IF NOT EXISTS `example_table`(
  `col1` string,
  `col2` string
)
PARTITIONED BY (
`partition_col` string)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
STORED AS TEXTFILE
LOCATION
'/path/
```

Then if we use the following insertion (let's call this **INSERTION 1**)
```
INSERT INTO example_table
SELECT
another_table.col1,
another_table.col2,
'partition_foo'
FROM another_table
```


The the table `example_table` will have this row:
```
co1   | col2    | partition_col
NULL | NULL | 'partition_foo'
```

If we first do the following,
```
INSERT INTO example_table VALUES ('a', 'b', 'partition_bar)
```
then **INSERTION 1**, 
the table will have the following rows:
```
co1  | col2 | partition_col
a| b | 'partition_bar',
another_table.col1 | another_table.col2|'partition_foo'
```
Hope this explains better. Thanks again

**Comment by findepi** [comment] 2018-04-03 10:35
@jiajinyu i think this has been fixed in https://github.com/prestodb/presto/pull/9784 . Please upgrade.

**Comment by findepi** [comment] 2018-04-03 10:36
btw, thanks for providing more context, this is what reminded me about that change.

**Closed by findepi** 2018-04-03 10:35 UTC
