### ISSUE TITLE
values column calculated by rand() in subquery are regenerated every time the column is referenced

### ISSUE THREAD

**Issue by brianseo517** [prestodb/presto#4992] opened 2016-04-11 20:27 UTC
presto:default> with test1 as (select rand() as test_value) 
                        select 1 + test_value, 0+test_value, test_value from test1;

       _col0        |        _col1        |     test_value     
--------------------+---------------------+--------------------
 1.064817        | 0.422031069  | 0.438340512

I'm not sure if this is the intended behavior, but i'm noticing that if i use the rand() in a nested subquery, every time I reference the column in a subsequent function/column the value will regenerate. Ideally once the rand() value is generated, it should persist and not be regenerated unless rand() is being called directly.

I think the cluster i'm on is currently running on presto 0.122. I don't recall seeing anything in the release notes post .122 that indicate a change to this function.

**Comment by martint** [comment] 2016-04-11 20:35
This is a duplicate of https://github.com/prestodb/presto/issues/3779

**Closed by martint** 2016-04-11 20:35 UTC
