### ISSUE TITLE
Right-truncating cast from number to varchar(x) produces value that behaves strangely

### ISSUE THREAD

**Issue by xufanghui** [prestodb/presto#9282] opened 2017-11-04 11:53 UTC
I query at :
<pre>
select cast(1234 as varchar(3))='123';
 _col0
-------
 false
(1 row)

Query 20171104_114903_00039_xazve, FINISHED, 1 node
Splits: 17 total, 17 done (100.00%)
</pre>
result is true,but is false,may be is bug

**Comment by akshatnair** [comment] 2017-11-04 21:44
Possible error due to padding and/or length calculation:

presto:sf1> select length(cast(1234 as varchar(3)));
 _col0 
-------
     4 
(1 row)

presto:sf1> select typeof(cast(1234 as varchar(3)));
   _col0    
------------
 varchar(3) 
(1 row)

**Comment by sopel39** [comment] 2017-11-05 20:57
@xufanghui The result should be neither true of false. According to SQL specification, such cast (which truncates fixed numeric value) should throw an exception. Therefore you shouldn't rely that `cast(1234 as varchar(3))='123';`

What you can do though is to convert your number to varchar of unbounded length and then truncate:
```
presto> select cast(cast(1234 as varchar) as varchar(3))='123';
 _col0
-------
 true
(1 row)
```

http://webdocs.cs.ualberta.ca/~yuan/courses/db_readings/ansi-iso-9075-2-1999.pdf `section 6.22 8)`:
```
8)   If TD is fixed-length character string, then let LTD be the length in characters of TD.
Case:
a)   If SD is exact numeric, then let YP be the shortest character string that conforms to the
definition of <exact numeric literal> in Subclause 5.3, ‘‘<literal>’’, whose scale is the same as
the scale of SD and whose interpreted value is the absolute value of SV . If SV is less than 0 (zero),
then let Y be the result of ’-’||YP Otherwise, let Y be YP.
Case:
i)   If Y contains any <SQL language character> that is not in the repertoire of TD , then an
exception condition is raised: data exception — invalid character value for cast.
ii)   If the length in characters LY of Y is equal to LTD , then TV is Y.
iii)   If the length in characters LY of Y is less than LTD, then TV is Y extended
on the right by LTD-LY <space>s.
iv)   Otherwise, an exception condition is raised: data exception — string data, right truncation.
```

We should probably address numeric conversion issues holistically and think how to handle double to character string conversions since doubles are not converted using scientific notation (e.g `1E2`).

**Comment by findepi** [comment] 2017-11-05 21:08
@sopel39 good catch! I think you quoted section regarding cast to `char(x)`, but indeed, cast to `varchar(x)` is almost the same (sans padding with spaces).

This, however, poses backwards incompatible change. Currently `cast(cast(1234 as varchar(3))` prints `'123'` (but the `Slice` representation of the value is bogus, which leads to the problems described in this issue, which #9288 addressed). Now, following standard, `cast(cast(1234 as varchar(3))` should fail (for source type `integer`, `bigint`). 
@martint , could you please ACK this?

Also, there is a question, what should happen when there would be right truncation when casting to varchar from boolean (4-5 characters), float/double (inexact numeric), decimal data types. All these are currently wrong (none throws, each can produce `Slice` longer than target type length limit).

**Comment by sopel39** [comment] 2017-11-05 21:20
> Also, there is a question, what should happen when there would be right truncation when casting to varchar from boolean (4-5 characters), float/double (inexact numeric), decimal data types. All these are currently wrong (none throws, each can produce Slice longer than target type length limit).

Those cases are described in SQL standard in the link I have included. Basically all numeric -> varchar/char casts should fail when digits are truncated. The same goes to boolean (`true/false`).

The only issue is with double/float since we use non-scientific textual representation of these. I think we should also fail when some digit is truncated. Uses can always cast first to decimal and then to varchar of given length.

**Comment by sopel39** [comment] 2017-11-05 21:24
I also assume that people don't rely much on numeric->character type casts yet since nobody noticed the issue yet. So probably now is a good time to decide on semantics. Postgres for instance does this the stupid way (e.g: as I recall `cast('123' as varchar(1))='1'`).

**Comment by sopel39** [comment] 2017-11-05 22:51
Possibly duplicate of: https://github.com/prestodb/presto/issues/7815

**Comment by findepi** [comment] 2017-11-06 08:29
Duplicates #7815

**Closed by findepi** 2017-11-06 08:29 UTC
