### ISSUE TITLE
CREATE TABLE AS & CAST( --- as date) Does not work correctly in conjunction

### ISSUE THREAD

**Issue by brianseo517** [prestodb/presto#3780] opened 2015-10-16 20:37 UTC
presto:default> select '2015-10-01', cast('2015-10-01' as date);
   _col0    |   _col1  
------------+------------
 2015-10-01 | 2015-10-01 

presto:default> create table zzz_presto_bug as select '2015-10-01' as d1, cast('2015-10-01' as date) as d2;
presto:default> select \* from zzz_presto_bug;
     d1     |     d2  
------------+------------
 2015-10-01 | 2015-09-30 

When creating a table and casting one of the columns from string to date, the date rolls back by 1 day for whatever reason.

This presto instance is v 0.115, Hadoop distro is CDH 5.4. Catalogue is a hive, running v.1.1

**Comment by cawallin** [comment] 2015-10-19 21:49
This looks like a timezone issue.  What time zones are the Presto CLI, the Presto server and the Hive server running in?

**Comment by brianseo517** [comment] 2015-10-19 23:01
Presto CLI - PDT, Presto Server - PDT America/Los Angeles, Hive Server - PDT

**Comment by nezihyigitbasi** [comment] 2015-10-21 19:56
[This](https://github.com/facebook/presto/blob/master/presto-hive/src/main/java/com/facebook/presto/hive/HiveWriteUtils.java#L181-L183) code snippet is the root cause I believe. The following fixes the problem:

```Java
return new Date(UTC.getMillisKeepLocal(DateTimeZone.getDefault(), TimeUnit.DAYS.toMillis(days)));
```

@dain Can you please confirm whether this is the right fix? If yes, I can create a PR for it.

**Comment by dain** [comment] 2015-10-22 06:50
That looks correct, but it would be nice to have a test that can reproduce this.  Maybe we can reproduce by modifying TestHiveIntegrationSmokeTest#createTableAs to have a DATE column.

-dain

**Comment by rschlussel** [comment] 2017-03-24 15:30
Fixed by https://github.com/prestodb/presto/pull/3809

**Closed by rschlussel** 2017-03-24 15:30 UTC
