### ISSUE TITLE
QueryManager is reporting RunningQueries wrong

### ISSUE THREAD

**Issue by yingsu00** [prestodb/presto#10134] opened 2018-03-09 20:15 UTC
https://fburl.com/ods/0qjke3vt
RunningQueries from QueryManager was 450-500 sometimes while the RunningQueries counters from the resource groups are just 40-50.

**Comment by nezihyigitbasi** [comment] 2018-03-15 05:20
This looks like a duplicate of https://github.com/prestodb/presto/issues/10046

**Comment by rschlussel** [comment] 2019-03-27 22:12
@yingsu00 I'm closing this as a duplicate.  If it's a different issue, feel free to reopen and explain

**Closed by rschlussel** 2019-03-27 22:12 UTC
Labels: bug
