### ISSUE TITLE
Flaky tests in presto-iceberg

### ISSUE THREAD

**Issue by pranjalssh** [prestodb/presto#18100] opened 2022-07-25 21:24 UTC
2 flaky tests in presto-iceberg have been disabled.

PR: https://github.com/prestodb/presto/pull/18081

Run: https://github.com/prestodb/presto/runs/7507677777?check_suite_focus=true

[Logs](https://pipelines.actions.githubusercontent.com/serviceHosts/b142b595-b3a5-43bf-a874-b00b946d701e/_apis/pipelines/1/runs/103497/signedlogcontent/2?urlExpires=2022-07-25T21%3A23%3A52.0328148Z&urlSigningMethod=HMACV1&urlSignature=ZioEpHplg27DqRVOlvzL3UCq46hYGMxkUdicndUtqNY%3D)

**Comment by pranjalssh** [comment] 2022-07-25 21:25
Cc @nastra  @beinan

**Comment by beinan** [comment] 2022-07-25 23:44
@pranjalssh thank you for raising this issue!  #18101 merged

**Closed** 2022-07-25 23:45 UTC

**Comment by ajantha-bhat** [comment] 2022-07-28 08:37
@nastra, @pranjalssh: I want to investigate these Nessie flaky tests.

Do we have a link to the callstack (in logs) when the failure happened? I tried running disabled tests from this PR locally. But I couldn't reproduce locally.

**Comment by nastra** [comment] 2022-07-28 08:42
@ajantha-bhat here's the stack from from https://github.com/prestodb/presto/runs/7493562511?check_suite_focus=true:
```
2022-07-25T05:24:38.0785692Z [ERROR] com.facebook.presto.iceberg.nessie.TestNessieMultiBranching.testNamespaceVisibility  Time elapsed: 0.737 s  <<< FAILURE!
2022-07-25T05:24:38.0786328Z java.lang.AssertionError: 
2022-07-25T05:24:38.0786579Z 
2022-07-25T05:24:38.0786820Z Expecting empty but was:<[[namespace_one]]>
2022-07-25T05:24:38.0787519Z 	at com.facebook.presto.iceberg.nessie.TestNessieMultiBranching.testNamespaceVisibility(TestNessieMultiBranching.java:98)
2022-07-25T05:24:38.0788254Z 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-07-25T05:24:38.0789395Z 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-07-25T05:24:38.0791008Z 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-07-25T05:24:38.0791578Z 	at java.lang.reflect.Method.invoke(Method.java:498)
2022-07-25T05:24:38.0793038Z 	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
2022-07-25T05:24:38.0794092Z 	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
2022-07-25T05:24:38.0795355Z 	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
2022-07-25T05:24:38.0796591Z 	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
2022-07-25T05:24:38.0798060Z 	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
2022-07-25T05:24:38.0799288Z 	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
2022-07-25T05:24:38.0800698Z 	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
2022-07-25T05:24:38.0801767Z 	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
2022-07-25T05:24:38.0802996Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2022-07-25T05:24:38.0804209Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2022-07-25T05:24:38.0804843Z 	at java.lang.Thread.run(Thread.java:750)
```

**Comment by ajantha-bhat** [comment] 2022-07-29 12:22
Randomly reproduced with logs, need to dig more

```
Session sessionOne = sessionOnRef(one.getName());
Session sessionTwo = sessionOnRef(two.getName());
```

session1: [SHOW SCHEMAS FROM iceberg]
[[information_schema], [tpch]]
session2: [SHOW SCHEMAS FROM iceberg]
[[information_schema], [**namespace_one**], [tpch]]

`assertQuerySucceeds(sessionOne, "CREATE SCHEMA namespace_one");`

session1: [SHOW SCHEMAS FROM iceberg]
[[information_schema], [namespace_one], [tpch]]
session2: [SHOW SCHEMAS FROM iceberg]
[[information_schema], [namespace_one], [tpch]]

`assertQuerySucceeds(sessionTwo, "CREATE SCHEMA namespace_two");`

session1: [SHOW SCHEMAS FROM iceberg]
[[information_schema], [namespace_one], [tpch]]
session2: [SHOW SCHEMAS FROM iceberg]
[[information_schema], [namespace_one], [namespace_two], [tpch]] 

**Observation:**
Session2 already has namespace1 before creating the namespace in session2 :(

**Comment by dimas-b** [comment] 2022-07-29 18:35
#18124 fixes the namespace clash.
