### ISSUE TITLE
Regex fails with ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#3735] opened 2015-10-08 21:42 UTC
```
presto> select REGEXP_LIKE('a' ,'a.*\b');
Query ... failed: 1
java.lang.ArrayIndexOutOfBoundsException: 1
    at io.airlift.jcodings.MultiByteEncoding.safeLengthForUptoFour(MultiByteEncoding.java:64)
    at io.airlift.jcodings.specific.NonStrictUTF8Encoding.length(NonStrictUTF8Encoding.java:30)
    at io.airlift.jcodings.specific.BaseUTF8Encoding.mbcToCode(BaseUTF8Encoding.java:91)
    at io.airlift.jcodings.specific.NonStrictUTF8Encoding.mbcToCode(NonStrictUTF8Encoding.java:22)
    at io.airlift.jcodings.Encoding.isMbcWord(Encoding.java:469)
    at io.airlift.joni.ByteCodeMachine.opWordBound(ByteCodeMachine.java:1063)
    at io.airlift.joni.ByteCodeMachine.matchAt(ByteCodeMachine.java:239)
    at io.airlift.joni.Matcher.matchCheck(Matcher.java:304)
    at io.airlift.joni.Matcher.searchInterruptible(Matcher.java:457)
    at io.airlift.joni.Matcher.search(Matcher.java:318)
    at com.facebook.presto.operator.scalar.RegexpFunctions.regexpLike(RegexpFunctions.java:73)
    at com_facebook_presto_$gen_PageProcessor_4069.project_0(Unknown Source)
    at com_facebook_presto_$gen_PageProcessor_4069.process(Unknown Source)
    at com.facebook.presto.operator.FilterAndProjectOperator.getOutput(FilterAndProjectOperator.java:91)
    at com.facebook.presto.operator.Driver.processInternal(Driver.java:380)
    at com.facebook.presto.operator.Driver.processFor(Driver.java:303)
    at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:587)
    at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:505)
    at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:640)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by rschlussel** [comment] 2019-04-04 13:58
duplicate of #8711

**Closed by rschlussel** 2019-04-04 13:58 UTC
Labels: bug
