### ISSUE TITLE
Ordering of joined tables on column with same name fails

### ISSUE THREAD

**Issue by chorke** [prestodb/presto#7010] opened 2017-01-06 14:34 UTC
Query like [1] fails with message [2]. Removing one parameter from ORDER BY [3] returns correct result.
I am using PrestoDB of version 0.161.

[1]
SELECT a.intkey, b.intkey FROM SmallA AS a INNER JOIN SmallB AS b on a.intkey = b.intkey ORDER BY 1, 2;
[2]
Query 20170106_142052_04169_k4ss5 failed: Multiple entries with same key: intkey=ASC_NULLS_LAST and intkey=ASC_NULLS_LAST
[1]
SELECT a.intkey, b.intkey FROM SmallA AS a INNER JOIN SmallB AS b on a.intkey = b.intkey ORDER BY 1;

**Comment by martint** [comment] 2017-01-06 16:06
This is a duplicate of https://github.com/prestodb/presto/issues/6905. It will be fixed in the upcoming release (0.162).

**Closed by martint** 2017-01-06 16:06 UTC
