### ISSUE TITLE
Deflake TestBrutalShutdown.testQueryRetryOnShutdown

### ISSUE THREAD

**Issue by elharo** [prestodb/presto#22277] opened 2024-03-21 16:21 UTC
2024-03-21T15:20:39.3275891Z [INFO] Results:
2024-03-21T15:20:39.3276632Z [INFO] 
2024-03-21T15:20:39.3278720Z [ERROR] Failures: 
2024-03-21T15:20:39.3279751Z [ERROR]   TestBrutalShutdown.testQueryRetryOnShutdown:83 expected [5] but found [4]
2024-03-21T15:20:39.3280784Z [INFO] 
2024-03-21T15:20:39.3281407Z [ERROR] Tests run: 3111, Failures: 1, Errors: 0, Skipped: 0
2024-03-21T15:20:39.3282283Z [INFO]

**Comment by kiersten-stokes** [comment] 2024-03-21 19:35
Duplicate of #22125 🙂 I'm going close this in favor of the other since that one has a bit more info

**Closed by kiersten-stokes** 2024-03-21 19:35 UTC
Labels: flaky-test
