### ISSUE TITLE
Pushdown incorrectly handles expressions that can fail

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#5994] opened 2016-08-30 20:53 UTC
```sql
select *
from (
  select table_name, round(row_count / shard_count) rps
  from system.table_stats
  where table_schema = 'xxx' and shard_count >= 5000)
)
where rps <= 10000;
```
```
com.facebook.presto.spi.PrestoException: / by zero
	at com.facebook.presto.type.BigintOperators.divide(BigintOperators.java:101)
	at com_facebook_presto_$gen_PageProcessor_130.filter(Unknown Source)
	at com_facebook_presto_$gen_PageProcessor_130.process(Unknown Source)
	at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:260)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:378)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:301)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:622)
	at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:529)
	at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:665)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ArithmeticException: / by zero
	at com.facebook.presto.type.BigintOperators.divide(BigintOperators.java:98)
	... 11 more
```

**Comment by martint** [comment] 2016-08-30 21:01
Duplicate of https://github.com/prestodb/presto/issues/3232

**Closed** 2016-08-30 21:02 UTC
Labels: bug, duplicate
