### ISSUE TITLE
Support ORDER BY in ARRAY_AGG

### ISSUE THREAD

**Issue by cpcloud** [prestodb/presto#5370] opened 2016-05-27 19:28 UTC
```sql
SELECT ARRAY_AGG(x ORDER BY x) AS x_sorted
SELECT ARRAY_AGG(x ORDER BY y) AS x_by_y
```

PostgreSQL has this as well: https://www.postgresql.org/docs/9.4/static/sql-expressions.html#SYNTAX-AGGREGATES

**Comment by martint** [comment] 2016-05-27 19:32
Duplicate of https://github.com/prestodb/presto/issues/3890

**Closed by martint** 2016-05-27 19:32 UTC
Labels: duplicate

**Comment by cpcloud** [comment] 2016-05-27 19:55
whoops! sorry for the dupe.
