### ISSUE TITLE
Release notes for 0.186

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#9117] opened 2017-10-06 20:33 UTC
## David Phillips       
- [x]  09-22 17:27:25    621dfb51fc Remove total bytes from page source and record cursor
- [x]  09-22 22:28:49    8766ebd3a8 Rename local variables after S3 config extraction
- [x]  09-22 22:28:49    9d6be9a8ed Extract interface for S3 file system configuration
- [x]  09-22 22:28:49    f38ec41d18 Move S3 file system to separate package
- [x]  09-27 18:33:42    82821985dc Update to Airbase 69 and Airlift 0.150
- [x]  09-28 07:49:00    915dbfc552 Simplify CacheLoader creation using lambdas
- [x]  09-28 07:53:28    aee35cc13f Remove redundant cast
- [x]  09-28 15:57:55    b16ab7c761 Fix check for resource group soft memory limit
- [x]  09-29 14:44:45    cc970856c7 Deprecate query queues
- [x]  09-29 14:46:59    ddb5b46db7 Remove class obsoleted by Airlift upgrade
- [x]  09-29 15:33:14    2759105f88 Improve resource groups configuration documentation
- [x]  10-01 11:12:05    f2553c426e Do not ignore trailing characters for json_parse
- [x]  10-02 09:37:35    c6d1d1201a Prevent "FileSystem closed" error for Hive connector
- [x]  10-02 17:32:18    36932bf8b7 Update to Airbase 70
- [x]  10-04 22:43:58    c2d9ad4fa5 Remove maven-buildtime-extension
- [x]  10-06 12:00:20    6a115db1f4 Allow empty password in JDBC driver
- [x]  10-06 12:01:10    b5a7738ab1 Fix warnings in StatementClient
- [x]  10-06 12:15:43    cc7b3c5a1f Fix warnings and cleanup code in SpnegoFilter
- [x]  10-06 12:16:24    fb4076be54 Fix NPE during connector registration cleanup
- [x]  10-06 12:16:48    d07c78ea9c Update to H2 1.4.196
## Haozhun Jin          
- [x]  10-06 12:04:36    01d4e8c344 Add initialCount parameter to ReferenceCount constructor
- [x]  10-06 12:04:36    0ffe958181 Add javadoc to clarify ConnectorSplitSource.isFinished requirement
- [x]  10-06 12:04:36    2a16031311 Refactor TestBufferingSplitSource
- [x]  10-06 12:04:36    2dc27abe0a Make TestBackgroundSplitLoader not use DirectExecutor
- [x]  10-06 12:04:36    3ff9b9cb5e Remove unused field from HivePartitionKey
- [x]  10-06 12:04:36    41e0c1e505 Fix theoretical busy loop in HiveSplitLoader/Source
- [x]  10-06 12:04:36    8385a700c7 Rename NodePartitioning to TablePartitioning
- [x]  10-06 12:04:36    8774deacbc Rename DriverFactory.close to noMoreDrivers
- [x]  10-06 12:04:36    8ac08e9c19 Document guarantee on invocation of OperatorFactory.noMoreOperators
- [x]  10-06 12:04:36    8c9a306438 Rename HiveSplitSource.finished to noMoreSplits
- [x]  10-06 12:04:36    a3f148dc92 Rename OperatorFactory.close to noMoreOperators
- [x]  10-06 12:04:36    a92771483c Mark LookupJoinOperatorFactory as UsedByGeneratedCode
- [x]  10-06 12:04:36    dde112a9a2 Improve TestMetadataManager to avoid stuck test
- [x]  10-06 12:04:36    f8a9db4060 Rename TableLayout.PartitioningColumn to StreamPartitioningColumn
## James Sun            
- [x]  09-25 14:32:14    1b84897791 Fix counting bug in heuristics in DictionaryAwarePageProjection
- [x]  09-25 14:32:14    e95d6febf1 Add yield signals to page projection
- [x]  09-25 14:32:15    7c7af66d56 Restore generated PageProjection class
- [x]  10-05 12:59:45    7bb1acce2d Change constructor interface for VariableWidthBlockBuilder
- [x]  10-05 22:23:49    2010d924d6 Return Work object from GroupByHash.addPage/getGroupIds
- [x]  10-05 22:23:49    3c49aadec2 Yield HashAggregationOperator if memory is not enough for rehash
- [x]  10-05 22:23:49    561deca0c7 Allow GroupByHash to reserve memory
- [x]  10-05 22:23:49    899deb814a Introduce Work interface and use it in BigintGroupByHash
- [x]  10-05 22:23:49    a51db274ae Remove unused putIfAbsent interface
- [x]  10-05 22:23:49    b8b8e3bde3 Use Work interface in MultiChannelGroupByHash
- [x]  10-05 22:23:49    f25c6e0366 Return Work object from HashAggregationBuilder.processPage
## Leiqing Cai          
- [x]  10-04 12:18:04    94379b6102 Add Property node to treat property keys as identifiers
## Martin Traverso      
- [x]  09-23 08:31:33    29a27cf161 Remove unused StreamProperties#exactColumnOrder field
- [x]  09-23 09:50:28    3d2c0d7787 Add missing entries for 0.185 release notes
- [x]  09-25 11:23:48    ad191877f7 Add rmiregistry port to deployment documentation
- [x]  09-27 20:03:50    5f9b803e5c Fix leak in running query counter for failed queries
- [x]  09-28 18:43:47    097b48a43c Add inverse_normal_cdf function
## Nezih Yigitbasi      
- [x]  09-22 15:00:12    3178ffaefd Revert the code cache collection threshold to the previous value
- [x]  09-22 16:28:14    efe0f57790 Add support for geospatial functions
- [x]  09-27 10:07:54    0707f2f21a Add option to enable path style access for hive s3
- [x]  09-28 12:56:00    1a882ddd17 Add ignoreExisting support to metastore createTable interface
- [x]  09-28 12:56:00    613b70e53a Update ConnectorMetadata::createTable to take an ignoreExisting flag
- [x]  10-06 11:13:05    6e97979bb2 Add Bing tile functions
## Rongrong Zhong       
- [x]  09-25 11:40:02    e55de27e93 Separate SessionContext from SessionSupplier
- [x]  09-27 15:04:15    7601508f4e Add support for adding client tags to session
- [x]  10-05 18:36:38    6334482104 Add @Override to interface methods in HttpRequestSessionContext
## Shixuan Fan          
- [x]  09-25 15:35:13    8883b124b1 Implement implicit coercion for ROW type
## Wenlei Xie           
- [x]  09-25 14:26:02    d17082bcc1 Improve hash computation for MapType
- [x]  09-27 17:01:32    09e020bb7e Add detailed documentation for json_format and json_parse
- [x]  09-28 14:25:46    3822a2fc3c Enforce ConnectorSession to be the first parameter of scalar functions
- [x]  09-28 14:25:46    5358a9d6a1 Avoid binding the session per row in MapToMapCast
## Łukasz Osipiuk       
- [x]  09-28 03:36:29    015db8f59f Prevent file leak in FileSingleStreamSpiller
- [x]  09-28 03:36:29    057cad716c Improve testing spill in LookupJoinOperator
- [x]  09-28 03:36:29    066ca44bec Cache LookupSource to avoid construction cost
- [x]  09-28 03:36:29    0af4ad269a Separate build side setup and execution in TestHashJoinOperator
- [x]  09-28 03:36:29    0b0500746b Refactor LookupJoinOperator so that it doesn't keep LookupSource
- [x]  09-28 03:36:29    0fa1baf698 Check no write after read in FileSingleStreamSpiller
- [x]  09-28 03:36:29    12926a5a30 Add utility functions aiding Operator implementations
- [x]  09-28 03:36:29    13244b6b36 Unblock probe side as soon as all partitions ready or spilling
- [x]  09-28 03:36:29    1a4ac73ed9 Rename PartitionFunction to BucketPartitionFunction
- [x]  09-28 03:36:29    27217332d6 Add partitioningSpillerFactory parameter to innerJoinOperatorFactory
- [x]  09-28 03:36:29    3d8296a7c4 Change PartitionedLookupSourceFactory synchronization to RW-lock
- [x]  09-28 03:36:29    3ed413c976 Make probe's, build's hashChannel an OptionalInt
- [x]  09-28 03:36:29    3feff14e7f Keep calling build driver in TestHashJoinOperator after build is complete
- [x]  09-28 03:36:29    47716762ab Update java doc after introducing yield signal
- [x]  09-28 03:36:29    534de2e158 Make LocalPartitionGenerator implement PartitionFunction
- [x]  09-28 03:36:29    55008c8893 Change Page.mask signature to be more object-oriented
- [x]  09-28 03:36:29    589101fabb Extract join operator factory creation in TestHashJoinOperator
- [x]  09-28 03:36:29    600a1a7c78 Add overview spill docs
- [x]  09-28 03:36:29    6105b95967 Extend TestingTaskContext to inject TaskStateMachine
- [x]  09-28 03:36:29    7849928271 Add PartitioningSpiller
- [x]  09-28 03:36:29    814066077a Ensure field initialization in ActualProperties.Builder
- [x]  09-28 03:36:29    87777fc31f Update stream property derivations for Join Spill
- [x]  09-28 03:36:29    8b98dcf281 Calculate checksum of spilled LookupSource
- [x]  09-28 03:36:29    8c238ff0d9 Pass spilling parameters to HashBuildOperator & LookupJoinOperator
- [x]  09-28 03:36:29    959469a56a Close spill files as soon as they are read
- [x]  09-28 03:36:29    95ad82b475 Add spill for join
- [x]  09-28 03:36:29    978d20c0a7 Refactor supplying partition to PartitionedLookupSourceFactory
- [x]  09-28 03:36:29    abcc2140e5 Lazy create partition spillers to avoid spilling locations skew
- [x]  09-28 03:36:29    ac6ae4d6cf Add getAllSpilledPages method to SingleStreamSpiller
- [x]  09-28 03:36:29    b298a0e078 Refactor JoinProbe so that it doesn't keep LookupSource
- [x]  09-28 03:36:29    ba98c10770 Ensure constant number of LookupJoinOperators
- [x]  09-28 03:36:29    c44528b821 Introduce PartitionedConsumption
- [x]  09-28 03:36:29    c4686678d9 Add spilling properties documentation
- [x]  09-28 03:36:29    e14523f59b Try index compaction before spilling in HashBuilderOperator
- [x]  09-28 03:36:29    e7ed1e1e9d Reorder methods in HashBuildOperator to match lifecycle
- [x]  09-28 03:36:29    ef75ca377f Change memory revoking finish to continuations
- [x]  09-28 03:36:29    f730422524 Add getPages method to PagesIndex
- [x]  09-28 03:36:29    ff30473baf Provide thread safe AggregatedMemoryContext implementation

**Comment by wenleix** [comment] 2017-10-06 21:51
##  General 
- Fix excessive GC overhead caused by map to map cast.

**Comment by losipiuk** [comment] 2017-10-06 22:33
General:

* Add spill to disk for join.

**Comment by nezihyigitbasi** [comment] 2017-10-06 22:33
General
--------
- Add various geospatial functions including functions for processing Bing maps tiles, please see :doc:`/functions/geospatial` for details.


Hive
-----
- Add support for path style access to the S3 file system using the ``hive.s3.path-style-access`` configuration parameter.

SPI Changes
-----------

* Update ConnectorMetadata::createTable() interface to take an ignoreExisting boolean flag.

.. note::
    This is a backwards incompatible change to SPI,
    so if you have written a connector, you will need to update your code before
    deploying this release.

**Comment by rongrong** [comment] 2017-10-06 23:51
I'm not sure whether this needs to be in release notes:
General
 * Add support for adding client tags to session

**Comment by highker** [comment] 2017-10-07 00:42
General Changes:
- Prevent a query that contains "expensive" functions (for example, regular expression functions) from not releasing CPU resource or keeping running after it has been killed.
- Reduce memory usage when building data of varchar or varbinary types.
- Estimate memory usage for "group by" framework more precisely to prevent out of heap memory crash.

**Comment by nezihyigitbasi** [comment] 2017-10-09 18:43
General
- * Add ``query_max_execution_time`` session property and ``query.max-execution-time``
  config property. Queries will be marked as FAILED after they execute for more than the specified duration.

**Comment by shixuan-fan** [comment] 2017-10-10 06:20
General

- Fix operations on implicitly coercible ROW type expressions.

**Comment by raghavsethi** [comment] 2017-10-11 21:22
- Change `maxRunning` property in resource group configuration to be called `hardConcurrencyLimit`

**Closed** 2017-10-13 19:10 UTC
