### ISSUE TITLE
Error in OptimizeMixedDistinctAggregations

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#7246] opened 2017-01-30 21:06 UTC
```
java.lang.IllegalStateException: Duplicate key xxx
java.util.stream.Collectors.lambda$throwingMerger$0(Collectors.java:133)
java.util.HashMap.merge(HashMap.java:1253)
java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1320)
java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
com.facebook.presto.sql.planner.optimizations.OptimizeMixedDistinctAggregations$Optimizer.createGroupIdNode(OptimizeMixedDistinctAggregations.java:359)
com.facebook.presto.sql.planner.optimizations.OptimizeMixedDistinctAggregations$Optimizer.visitMarkDistinct(OptimizeMixedDistinctAggregations.java:216)
com.facebook.presto.sql.planner.optimizations.OptimizeMixedDistinctAggregations$Optimizer.visitMarkDistinct(OptimizeMixedDistinctAggregations.java:91)
com.facebook.presto.sql.planner.plan.MarkDistinctNode.accept(MarkDistinctNode.java:95)
com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:85)
com.facebook.presto.sql.planner.optimizations.OptimizeMixedDistinctAggregations$Optimizer.visitAggregation(OptimizeMixedDistinctAggregations.java:134)
com.facebook.presto.sql.planner.optimizations.OptimizeMixedDistinctAggregations$Optimizer.visitAggregation(OptimizeMixedDistinctAggregations.java:91)
com.facebook.presto.sql.planner.plan.AggregationNode.accept(AggregationNode.java:206)
com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:85)
com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:74)
java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
java.util.Iterator.forEachRemaining(Iterator.java:116)
java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:75)
com.facebook.presto.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:39)
com.facebook.presto.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:23)
com.facebook.presto.sql.planner.plan.PlanVisitor.visitProject(PlanVisitor.java:40)
com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:92)
com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:85)
com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:74)
java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
java.util.Iterator.forEachRemaining(Iterator.java:116)
java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:75)
com.facebook.presto.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:39)
com.facebook.presto.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:23)
com.facebook.presto.sql.planner.plan.PlanVisitor.visitSort(PlanVisitor.java:105)
com.facebook.presto.sql.planner.plan.SortNode.accept(SortNode.java:88)
com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:85)
com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:74)
java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
java.util.Iterator.forEachRemaining(Iterator.java:116)
java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:75)
com.facebook.presto.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:39)
com.facebook.presto.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:23)
com.facebook.presto.sql.planner.plan.PlanVisitor.visitProject(PlanVisitor.java:40)
com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:92)
com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:85)
com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:74)
java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
java.util.Iterator.forEachRemaining(Iterator.java:116)
java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:75)
com.facebook.presto.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:39)
com.facebook.presto.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:23)
com.facebook.presto.sql.planner.plan.PlanVisitor.visitOutput(PlanVisitor.java:50)
com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:82)
com.facebook.presto.sql.planner.plan.SimplePlanRewriter.rewriteWith(SimplePlanRewriter.java:33)
com.facebook.presto.sql.planner.optimizations.OptimizeMixedDistinctAggregations.optimize(OptimizeMixedDistinctAggregations.java:85)
com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:120)
com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:111)
com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:297)
com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:276)
com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:234)
com.facebook.presto.execution.resourceGroups.InternalResourceGroup.lambda$startInBackground$1(InternalResourceGroup.java:478)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:745)

**Comment by martint** [comment] 2017-01-30 21:08
Duplicate of https://github.com/prestodb/presto/issues/7214

**Closed by martint** 2017-01-30 21:08 UTC
Labels: bug, duplicate
