### ISSUE TITLE
Failed product test sql_tests.testcases.hive_tpch.q17

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#6527] opened 2016-11-04 16:04 UTC
```
2016-11-04 05:33:20 INFO: [117 of 362] sql_tests.testcases.hive_tpch.q17 (Groups: tpch)
2016-11-04 05:34:26 INFO: FAILURE     /    took 65.7 seconds
2016-11-04 05:34:26 SEVERE: Failure cause:
java.lang.AssertionError: Not equal rows:
0 - expected: 348406.05000000000|
0 - actual:   347372.94714285710|
	at org.assertj.core.api.AbstractAssert.failWithMessage(AbstractAssert.java:114)
	at com.teradata.tempto.assertions.QueryAssert.containsExactly(QueryAssert.java:238)
	at com.teradata.tempto.assertions.QueryAssert.matches(QueryAssert.java:101)
	at com.teradata.tempto.internal.convention.sql.SqlQueryConventionBasedTest.test(SqlQueryConventionBasedTest.java:95)
	at com.teradata.tempto.internal.convention.ConventionBasedTestProxyGenerator$ConventionBasedTestProxy.test(ConventionBasedTestProxyGenerator.java:120)
	at com.teradata.tempto.hive_tpch.q17(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at com.teradata.tempto.runner.TemptoRunner.run(TemptoRunner.java:96)
	at com.teradata.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:69)
	at com.teradata.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:57)
	at com.facebook.presto.tests.TemptoProductTestRunner.main(TemptoProductTestRunner.java:30)

**Comment by kokosing** [comment] 2016-11-07 06:35
I see it is passing on master? Was this fixed or is this intermittent?

**Comment by electrum** [comment] 2016-11-07 06:58
This is intermittent.

**Comment by fiedukow** [comment] 2016-11-07 12:02
https://github.com/prestodb/presto/pull/6529
Fix is already in.
@kokosing is working on additional tests

**Comment by kokosing** [comment] 2016-11-07 12:30
Test for the root cause issue is here: https://github.com/prestodb/presto/pull/6546

**Comment by kokosing** [comment] 2016-11-07 12:31
I am closing this as it should be already fixed, in case it reoccurs again please reopen it.

**Closed by kokosing** 2016-11-07 12:31 UTC
