### ISSUE TITLE
[Native] - SELECT TIMESTAMP '1960-01-22 3:04:05.1' returns wrong timestamp value if the input string had fraction of seconds 

### ISSUE THREAD

**Issue by mknegi** [prestodb/presto#21061] opened 2023-10-06 16:26 UTC
## Current Behavior

```
presto:tpch> SELECT TIMESTAMP '1960-01-22 3:04:05.1';
     _col0
-------------------------
 2544-08-11 02:38:38.809

Note:-> This is a wrong result. Problem seems to be only when the fraction part of the timestamp is supplied.

presto:tpch> SELECT TIMESTAMP '1960-01-22 3:04:05';
     _col0
-------------------------
 1960-01-22 03:04:05.000

presto:tpch> explain SELECT TIMESTAMP '1960-01-22 3:04:05.1';
                                                     Query Plan
--------------------------------------------------------------------------------------------------------------------
 - Output[PlanNodeId 5][_col0] => [expr:timestamp]
         Estimates: {source: CostBasedSourceInfo, rows: 1 (9B), cpu: 9.00, memory: 0.00, network: 0.00}
         _col0 := expr (1:16)
     - Project[PlanNodeId 1][projectLocality = LOCAL] => [expr:timestamp]
             Estimates: {source: CostBasedSourceInfo, rows: 1 (9B), cpu: 9.00, memory: 0.00, network: 0.00}
             expr := TIMESTAMP'1960-01-22 03:04:05.100'
         - LocalExchange[PlanNodeId 139][ROUND_ROBIN] () => []
                 Estimates: {source: CostBasedSourceInfo, rows: 1 (9B), cpu: 0.00, memory: 0.00, network: 0.00}
             - Values[PlanNodeId 0] => []
                     Estimates: {source: CostBasedSourceInfo, rows: 1 (9B), cpu: 0.00, memory: 0.00, network: 0.00}
                     ()
```

**Comment by aditi-pandit** [comment] 2023-10-09 03:10
@ashokku2022 : Ashok, lets find an owner for this in your team.

**Comment by ashokku2022** [comment] 2023-10-09 15:55
@aditi-pandit assigning it to @rrando901, thanks!

**Comment by rrando901** [comment] 2023-10-23 18:32
@mknegi Are you still able to reproduce this issue on your end? I am running on commit [ceffc7e](https://github.com/rrando901/presto/commit/ceffc7e74cf9775171cb0a3d752253ef99b9a57e) and cannot reproduce the issue.

```
presto:tpch> SELECT TIMESTAMP '1960-01-22 3:04:05.1';
          _col0          
-------------------------
 1960-01-22 03:04:05.100 
(1 row)
presto:tpch> SELECT TIMESTAMP '1960-01-22 3:04:05';
          _col0          
-------------------------
 1960-01-22 03:04:05.000 
(1 row)
presto:tpch> explain SELECT TIMESTAMP '1960-01-22 3:04:05.1';
                                                     Query Plan                                                     
--------------------------------------------------------------------------------------------------------------------
 - Output[PlanNodeId 5][_col0] => [expr:timestamp]                                                                  
         Estimates: {source: CostBasedSourceInfo, rows: 1 (9B), cpu: 9.00, memory: 0.00, network: 0.00}             
         _col0 := expr (1:16)                                                                                       
     - Project[PlanNodeId 1][projectLocality = LOCAL] => [expr:timestamp]                                           
             Estimates: {source: CostBasedSourceInfo, rows: 1 (9B), cpu: 9.00, memory: 0.00, network: 0.00}         
             expr := TIMESTAMP'1960-01-22 03:04:05.100'                                                             
         - LocalExchange[PlanNodeId 143][ROUND_ROBIN] () => []                                                      
                 Estimates: {source: CostBasedSourceInfo, rows: 1 (9B), cpu: 0.00, memory: 0.00, network: 0.00}     
             - Values[PlanNodeId 0] => []                                                                           
                     Estimates: {source: CostBasedSourceInfo, rows: 1 (9B), cpu: 0.00, memory: 0.00, network: 0.00} 
                     ()                                                                                             
                                                                                                                    
(1 row)
```

**Comment by mknegi** [comment] 2023-10-26 15:54
@rrando901 - Yes, I am still seeing this issue. I am on the lakehouse/develop branch though.

**Comment by yzhang1991** [comment] 2023-10-26 18:27
Today I merged the OSS master into the `develop` branch Manoj used to test and Manoj confirmed that the issue is no longer reproducible. I will close this as a won't fix.

**Closed by yzhang1991** 2023-10-26 18:27 UTC
Labels: bug, tests, prestissimo
