### ISSUE TITLE
Jdbc Based Connector: split the query into multiple splits by auto_increment columns

### ISSUE THREAD

**Issue by xumingming** [prestodb/presto#12135] opened 2018-12-26 13:22 UTC
Currently, Jdbc related connector produce only one split for query: https://github.com/prestodb/presto/blob/3060c65a1812c6c8b0c2ab725b0184dbad67f0ed/presto-base-jdbc/src/main/java/com/facebook/presto/plugin/jdbc/BaseJdbcClient.java#L230-L240

I propose to enhance this part, we can detect whether the table have any auto_increment column, if it does, we can split the query by the auto_increment value range. i.e.

```sql
select * from hello 
```

becomes:

```sql
select * from hello where id >=1 and id <=1000;
select * from hello where id >=1001 and id <=2000;
...
```

I believe this works because it is a preferred practice to have an auto_increment key in relational database table design. How does this sound to you?

**Comment by sajjoseph** [comment] 2018-12-27 20:11
Have you looked at this issue - https://github.com/prestodb/presto/issues/10832
Looks like both are for similar concerns.

**Comment by electrum** [comment] 2018-12-27 20:40
Closing as a duplicate of #10832

**Closed by electrum** 2018-12-27 20:41 UTC
