### ISSUE TITLE
Count(*) on empty relation return NULL when optimize_mixed_distinct_aggregations is turned on

### ISSUE THREAD

**Issue by kokosing** [prestodb/presto#9962] opened 2018-02-14 13:40 UTC
```
presto:tiny> set session optimize_mixed_distinct_aggregations = true;
SET SESSION
presto:tiny> SELECT count(*),count(distinct nationkey) FROM (SELECT * FROM nation EXCEPT SELECT * FROM nation);
 _col0 | _col1
-------+-------
 NULL  |     0
(1 row)
```

**Comment by kokosing** [comment] 2018-02-14 13:44
It can be reproduced even with simpler query:
```
presto:tiny> SELECT count(*),count(distinct a) FROM (select 1 where false) t(a);
 _col0 | _col1
-------+-------
 NULL  |     0
(1 row)
```

**Comment by martint** [comment] 2018-02-14 15:17
Duplicate of https://github.com/prestodb/presto/issues/8894

**Closed by martint** 2018-02-14 15:17 UTC
Labels: bug
