### ISSUE TITLE
[native] TPC-DS SF 1K regression in q9

### ISSUE THREAD

**Issue by aditi-pandit** [prestodb/presto#20854] opened 2023-09-13 17:57 UTC
The TPC-DS 1K (native vs java) show regression in only q9 numbers. The plans are clearly different. Investigate the underlying issue.

##
Java plan https://gist.github.com/aditi-pandit/709ebe0df0aa1445ed5c1a5e1a71f4fc
Native plan https://gist.github.com/aditi-pandit/dcd3d32fe973a3e65c9c82836ed58e55

## Your Environment

* Presto version used: 0.284
* Deployment (Cloud or On-prem): Cloud

**Comment by aditi-pandit** [comment] 2023-09-13 17:59
@ClarenceThreepwood @aaneja @bmckennaah

**Comment by ClarenceThreepwood** [comment] 2023-09-13 22:56
IIUC - you are seeing a different join order for q9 for native vs java cluster. Are the configs/parameters identical for both clusters? How do we verify that?

Is the performance worse compared to some run in the past (you say regression)?

**Comment by aditi-pandit** [comment] 2023-09-13 23:05
@ClarenceThreepwood : Worse is only comparison between java and C++. Have clarified. 
@wanglinsong : Please can you provide the info of the config parameters for the clusters.

**Comment by ClarenceThreepwood** [comment] 2023-09-13 23:22
So the Java plan (with 32 fragments) is the plan that Presto has always produced for this query. The native plan (with 16 fragments) is the new one and I'm not sure what caused that to change. On paper the native plan is the better one - but it surprisingly performs worse

**Comment by aaneja** [comment] 2023-09-14 05:06
Looking at the plans in more detail I see that the Native plan, which supports parquet pushdown **sometimes takes more CPU for the same scan** than the Java one :


## For count(*) with filterPredicate = ss_quantity_174 BETWEEN (INTEGER'41') AND (INTEGER'60')

### Java
```
- Aggregate(PARTIAL) => [count_475:bigint]
            CPU: 70.00ms (0.02%), Scheduled: 244.00ms (0.03%), Output: 1052 rows (9.25kB)
            Input avg.: 2266.76 rows, Input std.dev.: 1683.32%
            count_475 := "presto.default.count"(*) (35:8)
        - ScanFilterProject[table = TableHandle {connectorId='hive', connectorHandle='HiveTableHandle{schemaName=tpcds_sf1000_parquet, tableName=store_sales, analyzePartitionValues=Optional.empty}', layout='Optional[tpcds_sf1000_parquet.store_sales{domains={ss_quantity=[ [["41", "60"]] ]}}]'}, grouped = false, filterPredicate = ss_quantity_174 BETWEEN (INTEGER'41') AND (INTEGER'60'), projectLocality = LOCAL] => []
                Estimates: {source: CostBasedSourceInfo, rows: 2879987999 (24.14GB), cpu: 14399939995.00, memory: 0.00, network: 0.00}/{source: CostBasedSourceInfo, rows: 2591989199 (21.73GB), cpu: 28799879990.00, memory: 0.00, network: 0.00}/{source: CostBasedSourceInfo, rows: 2591989199 (21.73GB), cpu: 28799879990.00, memory: 0.00, network: 0.00}
                CPU: 769.00ms (0.25%), Scheduled: 2.14s (0.28%), Output: 2384635 rows (0B)
                Input avg.: 11875.39 rows, Input std.dev.: 1683.15%
                LAYOUT: tpcds_sf1000_parquet.store_sales{domains={ss_quantity=[ [["41", "60"]] ]}}
                ss_quantity_174 := ss_quantity:int:10:REGULAR (37:1)
                Input: 12492911 rows (22.65MB), Filtered: 80.91%
```

ScanFilterProject CPU : **CPU: 769.00ms (0.25%)**

### Native
```
- Aggregate(PARTIAL)[PlanNodeId 5931] => [count_475:bigint]
            CPU: 814.00ms (0.14%), Scheduled: 1.06s (0.04%), Output: 112 rows (3.50kB)
            Input avg.: 4911523.95 rows, Input std.dev.: 405.22%
            count_475 := "presto.default.count"(*) (35:8)
        - TableScan[PlanNodeId 72][TableHandle {connectorId='hive', connectorHandle='HiveTableHandle{schemaName=tpcds_sf1000_parquet_varchar, tableName=store_sales, analyzePartitionValues=Optional.empty}', layout='Optional[tpcds_sf1000_parquet_varchar.store_sales{domains={ss_quantity=[ [["41", "60"]] ]}}]'}, grouped = false] => []
                Estimates: {source: CostBasedSourceInfo, rows: 527855263 (4.42GB), cpu: 0.00, memory: 0.00, network: 0.00}
                CPU: 17.15s (3.04%), Scheduled: 1.45m (3.37%), Output: 550090682 rows (0B)
                Input avg.: 4911523.95 rows, Input std.dev.: 405.22%
                LAYOUT: tpcds_sf1000_parquet_varchar.store_sales{domains={ss_quantity=[ [["41", "60"]] ]}}
                ss_quantity:int:10:REGULAR
                    :: [["41", "60"]]
                Input: 550090682 rows (0B), Filtered: 0.00%
                Raw input: 2879987999 rows (3.58GB), Filtered: 80.90%
```

Since Native supports parquet filter pushdown, the `filterPredicate = ss_quantity_174 BETWEEN (INTEGER'41') AND (INTEGER'60')` is completely pushed to the connector and we see a `TableScan` node instead of a `ScanFilterProject`

TableScan CPU : **CPU: 17.15s (3.04%)**

## For "avg"("ss_ext_discount_amt") for ss_quantity_300 BETWEEN (INTEGER'61') AND (INTEGER'80')

### Java
```
- Aggregate(PARTIAL) => [avg_479:varbinary]
            CPU: 2.00s (0.65%), Scheduled: 2.77s (0.36%), Output: 1053 rows (37.56kB)
            Input avg.: 25435.48 rows, Input std.dev.: 521.62%
            avg_479 := "presto.default.avg"((ss_ext_discount_amt_304)) (56:8)
        - ScanFilterProject[table = TableHandle {connectorId='hive', connectorHandle='HiveTableHandle{schemaName=tpcds_sf1000_parquet, tableName=store_sales, analyzePartitionValues=Optional.empty}', layout='Optional[tpcds_sf1000_parquet.store_sales{domains={ss_quantity=[ [["61", "80"]] ]}}]'}, grouped = false, filterPredicate = ss_quantity_300 BETWEEN (INTEGER'61') AND (INTEGER'80'), projectLocality = LOCAL] => [ss_ext_discount_amt_304:decimal(7,2)]
                Estimates: {source: CostBasedSourceInfo, rows: 2879987999 (147.52GB), cpu: 40319831986.00, memory: 0.00, network: 0.00}/{source: CostBasedSourceInfo, rows: 2591989199 (132.77GB), cpu: 80639663972.00, memory: 0.00, network: 0.00}/{source: CostBasedSourceInfo, rows: 2591989199 (132.77GB), cpu: 103967566763.90, memory: 0.00, network: 0.00}
                CPU: 30.93s (10.02%), Scheduled: 1.14m (8.91%), Output: 26783556 rows (229.88MB)
                Input avg.: 133155.94 rows, Input std.dev.: 521.64%
                LAYOUT: tpcds_sf1000_parquet.store_sales{domains={ss_quantity=[ [["61", "80"]] ]}}
                ss_ext_discount_amt_304 := ss_ext_discount_amt:decimal(7,2):14:REGULAR (58:1)
                ss_quantity_300 := ss_quantity:int:10:REGULAR (58:1)
                Input: 140213204 rows (780.07MB), Filtered: 80.90%
```

ScanFilterProject CPU : **CPU: 30.93s (10.02%)**


### Native
```
- Aggregate(PARTIAL)[PlanNodeId 5991] => [avg_479:varbinary]
            CPU: 6.97s (1.24%), Scheduled: 26.34s (1.02%), Output: 112 rows (5.24MB)
            Input avg.: 4911423.49 rows, Input std.dev.: 405.22%
            avg_479 := "presto.default.avg"((ss_ext_discount_amt_304)) (56:8)
        - TableScan[PlanNodeId 118][TableHandle {connectorId='hive', connectorHandle='HiveTableHandle{schemaName=tpcds_sf1000_parquet_varchar, tableName=store_sales, analyzePartitionValues=Optional.empty}', layout='Optional[tpcds_sf1000_parquet_varchar.store_sales{domains={ss_quantity=[ [["61", "80"]] ]}}]'}, grouped = false] => [ss_ext_discount_amt_304:decimal(7,2)]
                Estimates: {source: CostBasedSourceInfo, rows: 527855263 (27.04GB), cpu: 4560655339.60, memory: 0.00, network: 0.00}
                CPU: 40.46s (7.18%), Scheduled: 3.19m (7.40%), Output: 550079431 rows (4.45GB)
                Input avg.: 4911423.49 rows, Input std.dev.: 405.22%
                LAYOUT: tpcds_sf1000_parquet_varchar.store_sales{domains={ss_quantity=[ [["61", "80"]] ]}}
                ss_ext_discount_amt_304 := ss_ext_discount_amt:decimal(7,2):14:REGULAR (58:1)
                ss_quantity:int:10:REGULAR
                    :: [["61", "80"]]
                Input: 550079431 rows (4.45GB), Filtered: 0.00%
                Raw input: 2879987999 rows (14.12GB), Filtered: 80.90%
```

TableScan CPU : **CPU: 40.46s (7.18%)**

## Possible bug
The above observation is however, not consistent. At times the native filtered parquet scans are **faster**
I do see that the underlying schemas used are different:
Native schema - `tpcds_sf1000_parquet_varchar`
Java schema - `tpcds_sf1000_parquet`


## Summary / Next steps
Lets do a benchto test between Native and Java for just a filtered scan **on the same schema** :  
```
EXPLAIN SELECT 1
FROM hive.tpcds_sf1000_parquet.store_sales
WHERE (
        "ss_quantity" BETWEEN 41 AND 60
    )
```

and
```
EXPLAIN SELECT 1
FROM hive.tpcds_sf1000_parquet_varchar.store_sales
WHERE (
        "ss_quantity" BETWEEN 41 AND 60
    )
```

This should clearly show the difference in CPU and if parquet filtered scans are consistently faster/slower than Java's ScanFilterProject

I suspect, however, that the fact that we're querying different schemas is the root cause

**Comment by aaneja** [comment] 2023-09-14 07:58
The table definitions for `store_sales` in both schemas is exactly the same, so we can rule out schema differences as a root cause as well :
```
 CREATE TABLE hive.tpcds_sf1000_parquet_varchar.store_sales (                          
    "ss_sold_date_sk" bigint,                                                          
    "ss_sold_time_sk" bigint,                                                          
    "ss_item_sk" bigint,                                                               
    "ss_customer_sk" bigint,                                                           
    "ss_cdemo_sk" bigint,                                                              
    "ss_hdemo_sk" bigint,                                                              
    "ss_addr_sk" bigint,                                                               
    "ss_store_sk" bigint,                                                              
    "ss_promo_sk" bigint,                                                              
    "ss_ticket_number" bigint,                                                         
    "ss_quantity" integer,                                                             
    "ss_wholesale_cost" decimal(7,2),                                                  
    "ss_list_price" decimal(7,2),                                                      
    "ss_sales_price" decimal(7,2),                                                     
    "ss_ext_discount_amt" decimal(7,2),                                                
    "ss_ext_sales_price" decimal(7,2),                                                 
    "ss_ext_wholesale_cost" decimal(7,2),                                              
    "ss_ext_list_price" decimal(7,2),                                                  
    "ss_ext_tax" decimal(7,2),                                                         
    "ss_coupon_amt" decimal(7,2),                                                      
    "ss_net_paid" decimal(7,2),                                                        
    "ss_net_paid_inc_tax" decimal(7,2),                                                
    "ss_net_profit" decimal(7,2)                                                       
 )                                                                                     
 WITH (                                                                                
    external_location = 's3a://oss-presto-tpcds-benchmark/sf1000/parquet/store_sales', 
    format = 'PARQUET'                                                                 
 )  

  CREATE TABLE hive.tpcds_sf1000_parquet.store_sales (                                  
    "ss_sold_date_sk" bigint,                                                          
    "ss_sold_time_sk" bigint,                                                          
    "ss_item_sk" bigint,                                                               
    "ss_customer_sk" bigint,                                                           
    "ss_cdemo_sk" bigint,                                                              
    "ss_hdemo_sk" bigint,                                                              
    "ss_addr_sk" bigint,                                                               
    "ss_store_sk" bigint,                                                              
    "ss_promo_sk" bigint,                                                              
    "ss_ticket_number" bigint,                                                         
    "ss_quantity" integer,                                                             
    "ss_wholesale_cost" decimal(7,2),                                                  
    "ss_list_price" decimal(7,2),                                                      
    "ss_sales_price" decimal(7,2),                                                     
    "ss_ext_discount_amt" decimal(7,2),                                                
    "ss_ext_sales_price" decimal(7,2),                                                 
    "ss_ext_wholesale_cost" decimal(7,2),                                              
    "ss_ext_list_price" decimal(7,2),                                                  
    "ss_ext_tax" decimal(7,2),                                                         
    "ss_coupon_amt" decimal(7,2),                                                      
    "ss_net_paid" decimal(7,2),                                                        
    "ss_net_paid_inc_tax" decimal(7,2),                                                
    "ss_net_profit" decimal(7,2)                                                       
 )                                                                                     
 WITH (                                                                                
    external_location = 's3a://oss-presto-tpcds-benchmark/sf1000/parquet/store_sales', 
    format = 'PARQUET'                                                                 
 )    ```

**Comment by majetideepak** [comment] 2023-09-14 11:15
@aaneja Can we do a sanity check of table row count in both the data sets?

**Comment by aaneja** [comment] 2023-09-25 09:20
## Reg the plan difference w.r.t plan fragmentation
With native queries, we are running queries with hive filter pushdown enabled (this is required by native). This pushes the filters down to the scan node, and the call to `AddExchanges` does not need to add an extrac remote exchange 

### Without filter pushdown
```
exchange (scope=REMOTE_STREAMING, partitioning=PartitioningScheme{partitioning=Partitioning{handle=BROADCAST, arguments=[]}, outputLayout=[avg], hashChannel=Optional.empty, replicateNullsAndAny=false, bucketToPartition=Optional.empty})
    single aggregation over ()
        exchange (scope=REMOTE_STREAMING, partitioning=PartitioningScheme{partitioning=Partitioning{handle=SINGLE, arguments=[]}, outputLayout=[ss_ext_discount_amt_20], hashChannel=Optional.empty, replicateNullsAndAny=false, bucketToPartition=Optional.empty})
            project, Assignments ({ss_ext_discount_amt_20=ss_ext_discount_amt_20}), Outputs ([ss_ext_discount_amt_20]):
                filter (predicate = BETWEEN(ss_quantity_16, 1, 20))
                    scan (HiveTableHandle{schemaName=tpcds_sf1_parquet_with_col_stats, tableName=store_sales, analyzePartitionValues=Optional.empty}) Constraints [Current (Optional[{}]), Enforced(Optional[{}])]
```

### With filter pushdown
```
single aggregation over ()
    exchange (scope=REMOTE_STREAMING, partitioning=PartitioningScheme{partitioning=Partitioning{handle=SINGLE, arguments=[]}, outputLayout=[ss_ext_discount_amt_20], hashChannel=Optional.empty, replicateNullsAndAny=false, bucketToPartition=Optional.empty})
        scan (HiveTableHandle{schemaName=tpcds_sf1_parquet_with_col_stats, tableName=store_sales, analyzePartitionValues=Optional.empty}) Constraints [Current (Optional[{ss_quantity:int:10:REGULAR=com.facebook.presto.common.predicate.Domain@144786dd}]), Enforced(Optional[{}])]
```

See https://gist.github.com/aaneja/3c6b0887f97fc2b084b63e95cdfe15d1 for details

**Comment by yzhang1991** [comment] 2023-11-15 17:42
@yingsu00 Can you suggest what would be a good action item for this one?

**Comment by aaneja** [comment] 2023-11-16 08:42
IMO we should retest this with FRC and data cache turned off for both Java and similarly turn off any caching for Native clusters. Post that if we do not see a regression in Q9 we can close this issue

**Comment by wanglinsong** [comment] 2023-12-14 08:46
Here are the latest test results.
There is no regression in total_split_cpu_time_ms.
native / java : 872220 / 7347447

**Closed by wanglinsong** 2023-12-14 08:46 UTC
Labels: bug
