### ISSUE TITLE
Can not able to connect to Kerberos secure kafka

### ISSUE THREAD

**Issue by dhiarum** [prestodb/presto#8059] opened 2017-05-18 14:01 UTC
Hi Team,

I have Kerberos secure Kafka and i wanted to use kafka connector in presto for the same. But i could not able to use it. Could you please let me know if we have any option to do it here?

**Comment by cawallin** [comment] 2017-05-18 15:33
No, it's not supported. This issues is a duplicate of https://github.com/prestodb/presto/issues/7990, so I'm going to close it.

**Closed by cawallin** 2017-05-18 15:33 UTC
