### ISSUE TITLE
Kafka 0.9 Support

### ISSUE THREAD

**Issue by jofusa** [prestodb/presto#5130] opened 2016-04-27 18:28 UTC
The kafka connector currently does not support the new 0.9 protocol. Is there are plans to support newer versions of kafka?

**Comment by maciejgrzybek** [comment] 2016-07-20 17:23
Closing since I've confirmed that Kafka connector works perfectly fine with Kafka 0.10.

**Closed by maciejgrzybek** 2016-07-20 17:23 UTC
