### ISSUE TITLE
ParquetCompressionUtil doesn't handle LZOP

### ISSUE THREAD

**Issue by dabaitu** [prestodb/presto#8290] opened 2017-06-18 22:20 UTC
@zhenxiao - who probably has the most context.
It looks like ParquetCompressionUtil is used by the optimized ParquetReader and used to read dictionary page when predicate push down is turned on.
When I turn on either of those session settings, we get the following exception
`2017-05-31T23:48:45.957Z	ERROR	remote-task-callback-20	com.facebook.presto.execution.StageStateMachine	Stage 20170531_234845_00014_svyw2.2 failed
com.facebook.presto.spi.PrestoException: Error opening Hive split viewfs://hadoop-dw2-nn.smf1.twitter.com/logs/presto_query_completion/2017/05/30/11/presto_query_completion_2017-05-30-11_smf1-m-00000.lzo.parquet (offset=0, length=63008): Malformed input: offset=86
	at com.facebook.presto.hive.parquet.ParquetHiveRecordCursor.createParquetRecordReader(ParquetHiveRecordCursor.java:388)
	at com.facebook.presto.hive.parquet.ParquetHiveRecordCursor.<init>(ParquetHiveRecordCursor.java:161)
	at com.facebook.presto.hive.parquet.ParquetRecordCursorProvider.createRecordCursor(ParquetRecordCursorProvider.java:92)
	at com.facebook.presto.hive.HivePageSourceProvider.createHivePageSource(HivePageSourceProvider.java:179)
	at com.facebook.presto.hive.HivePageSourceProvider.doCreatePageSource(HivePageSourceProvider.java:109)
	at com.facebook.presto.hive.HivePageSourceProvider.lambda$createPageSource$0(HivePageSourceProvider.java:88)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1698)
	at com.facebook.presto.hive.HivePageSourceProvider.createPageSource(HivePageSourceProvider.java:87)
	at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorPageSourceProvider.createPageSource(ClassLoaderSafeConnectorPageSourceProvider.java:44)
	at com.facebook.presto.split.PageSourceManager.createPageSource(PageSourceManager.java:56)
	at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:219)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:303)
	at com.facebook.presto.operator.Driver.lambda$processFor$6(Driver.java:234)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:537)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:229)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:623)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:458)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.airlift.compress.MalformedInputException: Malformed input: offset=86
	at io.airlift.compress.lzo.LzoRawDecompressor.decompress(LzoRawDecompressor.java:264)
	at io.airlift.compress.lzo.LzoDecompressor.decompress(LzoDecompressor.java:36)
	at com.facebook.presto.hive.parquet.ParquetCompressionUtils.decompress(ParquetCompressionUtils.java:119)`

It doesn't look like LzoDecompressor from aircompressor handles LZOP. If HadoopLzopInputStream from aircompressor is public I could use that to decompress files with ".lzo" extension and put this change in ParquetCompressionUtil.
Is there suppose to be a generic decompressor from aircompressor that will decompress an InputStream with a codec param that I'm not finding.
The LzopCodec in aircompressor is not hooked up yet to Presto, right?

Is there an easy way around this? If not, is it the correct way to modify LzoDecompressor from aircompressor(have it use HadoopLzoInputStream or HadoopLzopInputStream), and remove the redundant chunk by chunk decompression logic in ParquetCompressionUtils?

Thanks!
Tom

**Comment by zhenxiao** [comment] 2017-06-19 03:28
Hi Tom,

I think due to license issues, LZO jar is not released with Presto. Usually, I will work around it by adding the following LZO jar into Presto Hadoop connector path:
http://www.oberhumer.com/opensource/lzo/download/

Yes, we could try adding aircompressor support for LZO.

**Comment by dabaitu** [comment] 2017-06-19 16:00
@zhenxiao but in the case of using the optimized reader or reading the Parquet dictionary when predicate push down is enabled, copying the LZO jar to Hadoop connector path won't help, right? In those cases, we are using the aircompressor lzo decompression which right now doesn't handle lzop.

**Comment by dain** [comment] 2017-06-19 18:03
Aircompressor does handle LZOP (https://github.com/airlift/aircompressor/blob/master/src/main/java/io/airlift/compress/lzo/LzopCodec.java#L33).  If it is not working correctly, please file an issue with that project.

**Comment by dabaitu** [comment] 2017-06-19 18:46
@dain right, that works with the ParquetRecordReader. The issue here is that there's another ParquetReader(ParquetPageReader) that doesn't use the LZO and LZOP codecs from aircompressor, and fails when reading LZOP files.
The right change is probably still here in Presto, to have the PageReader use the codecs from aircompressor.

**Comment by zhenxiao** [comment] 2017-06-19 18:54
@dabaitu you are correct, yes, the problem is in ParquetPageReader does not handle LZOP using Aircompressor. Could file a ticket adding that support in ParquetPageReader

**Comment by nezihyigitbasi** [comment] 2017-06-21 17:30
created a followup issue #8318, so closing this one.

**Closed by nezihyigitbasi** 2017-06-21 17:30 UTC
